### PR TITLE
Breaking changes for linear solving

### PR DESCRIPTION
**Pull request by joschmitt**
Removes some workarounds to the linear solving that were introduced to stay compatible with OSCAR 1.0.

This will first of all break Nemo. ~Until I have a working branch there, I leave this here as draft. Maybe I need to change something again.~

### CODE REVIEW

**Comment by lgoettgens** [comment]
The downstream tests didn't run since we already bumped the version here. Have you verified that this together with https://github.com/Nemocas/Nemo.jl/pull/1730 will still work in Hecke and Oscar?

**Comment by joschmitt** [comment]
> The downstream tests didn't run since we already bumped the version here. Have you verified that this together with [Nemocas/Nemo.jl#1730](https://github.com/Nemocas/Nemo.jl/pull/1730) will still work in Hecke and Oscar?

No, I was fooled by the green CI. I run the tests locally now.

**Comment by joschmitt** [comment]
Nemo and Hecke tests work with https://github.com/Nemocas/Nemo.jl/pull/1730 and https://github.com/thofma/Hecke.jl/pull/1471.
The OSCAR tests just got killed with "signal 6". I try again.

**Comment by fingolfin** [comment]
So is this good to go for the upcoming breaking release then?

**Comment by joschmitt** [comment]
> So is this good to go for the upcoming breaking release then?

I hope so. I'm still trying to run the OSCAR tests locally (in my second attempt they seem to get stuck somewhere). I don't expect any problems with OSCAR though.

**Comment by joschmitt** [comment]
The OSCAR (master) tests finished now with AbstractAlgebra@js/solveagain, Nemo@js/solveagain and Hecke@js/solveagain.

**Pull request merged**
