### PR TITLE
Universal poly ring

### PR DESCRIPTION
**Pull request by wbhart**
Example:

```
julia> using AbstractAlgebra
[ Info: Precompiling AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> R = UniversalPolynomialRing(ZZ)
Universal Polynomial Ring

julia> x1 = gen(R, "x")
x

julia> x, y = gens(R, ["x", "y"])
(x, y)

julia> x
x

julia> y
y

julia> -x
-x

julia> x + y
x + y

julia> x1+y
x + y

julia> z = gen(R, "z")
z

julia> x*z
x*z
```

Fixes https://github.com/Nemocas/Nemo.jl/issues/724

Also adds mpoly_type.

### CODE REVIEW

**Review by tthsqe12 — COMMENTED** [review]
1. "UnivPoly" looks like an abbreviation for "univariate polynomial"
2. The gen function modifies the ring. Is thread-unsafety the new standard for everything AA/Nemo/Hecke/Oscar?
3. I cannot see anyone using this for serious computations. Therefore, it seems it is for convenience/top level demo purposes.
	However, the usage is anything but convenient because we have many functions that accept MPolyElem's.
	Since !(x isa MPolyElem), in order to use them, we would have to extend by hand the methods with this new type (or use the .p member to get the actual MPolyElem)
4. This gives now a third incompatible way to use ZZ["x"], the others being PolynomialRing(ZZ, "x") and PolynomialRing(ZZ, ["x"]),
   and a second incompatible way to use ZZ["x", "y"], the other being PolynomialRing(ZZ, ["x", "y"])

```julia
julia> using Nemo

julia> R = UniversalPolynomialRing(ZZ)
Universal Polynomial Ring over Integer Ring

julia> x = gen(R, "x")
x

julia> x isa MPolyElem
false
```

**Comment by wbhart** [comment]
1. What would you suggest instead? It's just a cut and paste for the most part.
2. Nothing I can do about this. It is obviously a requirement for the design since the number of variables has to increase.
3. Unfortunately I did not understand this point. Did I forget the AbstractAlgebra on some of the MPolyElems? If so, I can certainly change that. It should work just fine with Nemo MPolyElems.
4. Eventually functions for conversion will be added. I am still thinking out the interface. I will not attempt to deal with this in the current PR, but will think out the interface carefully when I do https://github.com/Nemocas/Nemo.jl/issues/723

**Comment by tthsqe12** [comment]
For point 3, these universal poly rings do not have elements that belong to MPolyElem. Therefore, all of the stuff (in other packages) that is written for MPolyElem does not apply. To use this new type, we would have to extend the methods (yuck...) or call something like `get_mpoly_elem(x)` before passing the universal polynomial element `x` to the function other function.

**Comment by wbhart** [comment]
Ah I see. Perhaps it isn't clear, but all of the MPoly interface is implemented here, except:

1) Ideal division (couldn't be bothered, no one is using it)
2) Factorisation (it only exists in Nemo, so will have to be implemented there, but this isn't a major job)
3) Anything else that only exists in Nemo and not AbstractAlgebra that I overlooked.

I'm not sure I understand your complaint precisely. It seems you would like the UniversalPolynomialRing to not be a universal polynomial ring but to be an ordinary MPolyRing. I don't think that makes any sense. It exists to do things that MPolyRing does not and cannot do.

**Comment by tthsqe12** [comment]
But, what if you want to do MPolyElem stuff on these things? The fact that this interface works inside AA does not change the fact that other packages have signatures `f(::MPolyElem)`. In order to use f, you would have to call `f(get_mpoly_elem(x))`.

**Comment by tthsqe12** [comment]
could we implement `convert(::type{MPolyElem}, ::UnivPolyElem)` and have it work smoothly?

**Comment by thofma** [comment]
No, this does not make any smoother.

**Comment by wbhart** [comment]
I guess those interfaces would have to use Union{MPolyElem, UnivPolyElem} instead, assuming those functions actually made sense for UnivPolyElem, which they probably would not.

The universal polynomial ring is to make up for symbolic functionality that we don't have. It isn't to add another interface for computing in Z[x, y]. The idea is you are writing some complex mathematical function, but at some point you have a purely symbolic problem. You coerce your MPolys into the universal polynomial ring, do your symbolic manipulation there, pull polynomials back out again (using an interface I have not thought up yet), and continue on with your computation in MPoly.

**Comment by wbhart** [comment]
To answer your question another way, I cannot make UnivPolyElem <: MPolyElem as the latter distinguishes rings Z[x, y] and Z[x, y, z], whereas the former considers one an extension of the other. There is only one universal polynomial ring for each coefficient ring (and ordering). That is not the case for MPoly, and nor should it be. So one cannot be made to belong to the other.

**Comment by tthsqe12** [comment]
Ok. Eventually we will see the interface for "pull polynomials back out again". Now, hmm, what do you have in mind for "do your symbolic manipulation there"? I don't see anything symbolic here or elsewhere in AA. If the purpose here is to add symbolic functionality, I see no reason do it this way: all you are doing is creating a polynomial ring with an unlimited number of variables. If by proper symbolic functionality, you mean doing stuff like creating the expression `:(x^n+y^n)`, then, say, replacing n by `2`, x by `:(a+b)` and y by `:(a-b)` to get the (non-expanded!) symbolic expression `:((a+b)^2+(a-b)^2)`, then, say, asking the system to try to convert this to an `MPolyElem`, I think that could be useful.

**Comment by wbhart** [comment]
Our system isn't symbolic at all, and this is no exception. What I mean is that there are manipulations that can be done in a symbolic system that cannot be done in our system. I don't want to add symbolics per se, just alternative functionality that could accomplish some of the same tasks (probably by providing a map of variables).

See https://github.com/Nemocas/Nemo.jl/issues/723 for an example of something that is currently difficult to do in our system.

One way to handle such things is to provide powerful ways to coerce into a universal ring and then back out again. As I say, I don't have the idea for the interface worked out yet. But it'll probably be similar to our evaluation interface but with a dictionary of variables or something similar. But that's a project for another rainy day.

**Comment by tthsqe12** [comment]
Ok, I will add a comment to that issue.

**Pull request merged**
