### PR TITLE
Move some functions from Hecke to AbstractAlgebra/Misc.

### PR DESCRIPTION
**Pull request by wbhart**
Notes:

* This PR will break Hecke; please merge the Hecke PR mentioned below at the same time or shortly after this one
* This PR does not break Nemo
* I have not moved Matrix.jl stuff or jordan.jl (it proved too difficult to do in one go and will be done in the future)
* I have not updated the version of AbstractAlgebra
* I had to change one of the tests for Localization.jl in Hecke.jl for inv(L()) for a L localization of FlintZZ
* I did not move the tests for Localization to make it easier to see in Hecke.jl what I had to change and they require Nemo
* numerator and denominator of localization did not appear to be defined with the canonicalise flag, so I added that
* I have restricted some types to RingElement
* I have done only a very light amount of cleaning up; the intention is to get it moved before filling it out with tests/docs/bugfixes/similar functionality
* All tests in Hecke pass locally on my machine after the move

It is clear I need to write some developer documentation very soon. There were some very difficult to track down bugs due to not following conventions and rules we have established there.

### CODE REVIEW

**Comment by thofma** [comment]
Great, thanks!

> * This PR will break Hecke; please merge the Hecke PR mentioned below at the same time or shortly after this one

We need first a new release.

> * I have done only a very light amount of cleaning up; the intention is to get it moved before filling it out with tests/docs/bugfixes/similar functionality

When you write "move", do you mean merging and releasing a new version or just merging? There are some name changes we should do before tagging. In paricular `ispower` (in view of https://github.com/Nemocas/Nemo.jl/issues/862#issuecomment-669289362) and `isin` (should be `in`).

**Comment by thofma** [comment]
P.S.: I will do the renaming/rebasing in https://github.com/thofma/Hecke.jl/pull/149.

**Comment by wbhart** [comment]
I had in mind to release a new version and get Hecke using this new version. I'm ok with changing some names though. I imagine there will be more changes to names to come, though most of the stuff I moved was relatively uncontroversial. The controversial stuff I have mention in the notes I emailed to you guys. You can feel free to deal with that stuff as you wish.

**Comment by thofma** [comment]
OK. My thought was that changing the name after the release would be (again) breaking, so we needed yet another breaking release.

**Comment by wbhart** [comment]
There's no rush from my point of view. The AbstractAlgebra PR is certainly breaking and I marked it as such.

I'll be working on developer documentation for the next little while, so feel free to hold this PR as long as you want. So long as you guys prevent it from bitrotting by regularly rebasing the Hecke portion, I'm fine with it waiting until the next breaking release.

The whole intention here was to have one large block moved with a single breaking release to minimise the agitation. Of course I was able to move much less than I previously wanted to in a single release, but that's another story.

**Pull request merged**
