### PR TITLE
Retire legacy printer

### LINKED ISSUE #710: Add `expressify` method for SparsePoly, replacing its `show` method
As far as I can tell, that's the last remaining user of `show_minus_one`, `needs_parentheses` and `displayed_with_minus_in_front` in AbstractAlgebra. There is one other, in Nemo.jl, see https://github.com/Nemocas/Nemo.jl/issues/938.

### PR DESCRIPTION
**Pull request by tthsqe12**
hopefully closes #710
Also, this should work with nemo both before and after https://github.com/Nemocas/Nemo.jl/pull/943
Main changes here are:
   - displayed_with_minus_in_front and show_minus_one are gone. I hope they will not be missed.
   - needs_parentheses remains for backwards compatibility, and the docs say to use expressify
   - The precedence of unary minus has been moved higher and +, -, *, / are all left associative. This brings printing more inline with julia's specifications.
   - Printing of the `Fac{T}` type is now correct: it simply wasn't possible with the `needs_parentheses` interface.

So this is printed correctly:
```
julia> R, (x, y) = ZZ["x", "y"]; Fac(R(-1), Dict(x*y => 2))
-(x*y)^2
```

!!!Edit!!!!
The functions `displayed_with_minus_in_front` and `show_minus_one` remain in AbstractAlgebra.jl for export, but they are not used within.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@thoma I may have gotten the order wrong here. We might have to add the symbols back for export. not sure exactly...

**Comment by wbhart** [comment]
It hasn't been merged yet, though seems to pass tests anyway. But I marked it as breaking so it won't be merged until things happen as set out in #711

**Comment by tthsqe12** [comment]
@wbhart I edited the top comment. What would break is the following situation:
another package attempts to print its AA objects via calling displayed_with_minus_in_front and show_minus_one only to find out that they are not defined any more. Should the backwards compatibility section be `displayed_with_minus_in_font(x) = false` and `show_minus_one(x) = false`?

It turns out that Hecke is the only package that actually uses AA's displayed_with_minus_in_front and show_minus_one. Nemo.jl creates its own versions and Singular.jl uses the Nemo versions. So it is an absolute mess.

**Comment by wbhart** [comment]
I'm afraid that I don't recall what the functions exactly do. You might have to refer to the docs.

But if AA no longer uses them, then you are right to remove them from all other packages, right?

**Comment by thofma** [comment]
The only problems are packages which could have been calling these functions themselves. I added a rough fallback definition and a proper deprecation. This should be good to go.

**Pull request merged**
