### PR TITLE
require square matrices for one(::MatSpace), and add tests for #514

### PR DESCRIPTION
**Pull request by rfourquet**
Continuation of #514.

### CODE REVIEW

**Comment by johannes-hoffmann** [comment]
Should `isone` then also be restricted to square matrices?

**Comment by rfourquet** [comment]
> Should isone then also be restricted to square matrices?

Yes I think so. The generic definition of `one` is 

>   Return true if x == one(x); if x is an array, this checks whether x is an identity matrix.

**Comment by johannes-hoffmann** [comment]
And the none-generic ones like the following?
https://github.com/Nemocas/AbstractAlgebra.jl/blob/6581c130ce70f9deb0f4ac58363a1959853ec746/src/generic/Matrix.jl#L257-L277

**Comment by rfourquet** [comment]
> And the non-generic ones like the following?

Yes. As the generic "meaning" of the function `one` is to return a multiplicative identity, the generic meaning of the funtion "isone" is to tell whether the argument is the multiplicative identity, which is not the case for non-square matrices.

**Comment by johannes-hoffmann** [comment]
So we agree that the function I quoted does not follow this line of argument, since it does not check whether the input is actually a square matrix?

**Comment by rfourquet** [comment]
Yes. I had noticed the disrepancy too and was thinking to make a PR to change that and see if others were fine with this change.

**Comment by fieker** [comment]
On Mon, Oct 28, 2019 at 08:47:46AM -0700, Johannes Hoffmann wrote:
> Should `isone` then also be restricted to square matrices?
the debate is error vs false?
or accepting of "diagonal" rectangular ones?

**Comment by rfourquet** [comment]
Oh I may have misunderstood. I think `isone(a)` should be `true` only when `a` is square, but I prefer `false` rather than an error on non-square matrices. (Sidenote: `isone` is usually implemented this way in Julia, e.g. `isone([1 0]) == false`).

**Comment by johannes-hoffmann** [comment]
Sorry for the missunderstanding, I just wanted to bring the inconsistent behavior of `isone` to your attention. I am completely fine with `isone` returning `false` for everything that is not a true multiplicative identity (including non-square matrices).

**Pull request merged**
