### PR TITLE
Remove MPolyRing(R::Ring, n::Int)

### PR DESCRIPTION
**Pull request by fingolfin**
Analogue to PolyRing(), this one doesn't seem to be used at all

### CODE REVIEW

**Comment by fingolfin** [comment]
HeckeCI failures look like https://github.com/thofma/Hecke.jl/issues/1526 i.e. unrelated to this PR

**Comment by lgoettgens** [comment]
I think this is technically a breaking change to Oscar. Do we care about that? If yes, this should be deprecated instead of removed.
But in any case, the change should be made in a breaking release of AA.

**Comment by fingolfin** [comment]
`MPolyRing` is an undocumented function, and not even exported. I don't think we generally consider removing such a function a breaking change.

**Comment by lgoettgens** [comment]
I agree with the missing documentation, however it is indeed exported:
```julia
julia> using Oscar
  ___   ____   ____    _    ____
 / _ \ / ___| / ___|  / \  |  _ \   |  Combining ANTIC, GAP, Polymake, Singular
| | | |\___ \| |     / _ \ | |_) |  |  Type "?Oscar" for more information
| |_| | ___) | |___ / ___ \|  _ <   |  Manual: https://docs.oscar-system.org
 \___/ |____/ \____/_/   \_\_| \_\  |  Version 1.0.3

julia> MPolyRing(QQ, 2)
Multivariate polynomial ring in 2 variables x1, x2
  over rational field

julia> Base.isexported(Oscar, :MPolyRing)
true

julia> Base.isexported(Oscar.AbstractAlgebra, :MPolyRing)
true
```
I am not perse against this change, I definitely support all of this cleanup. But I wanted to mention things like this to make it a conscious decision and not some accidental result.

**Pull request merged**
