### PR TITLE
Make use of DensePoly.mullow_fast! in AbsSeries multiplication.

### PR DESCRIPTION
**Pull request by wbhart**
If this works out ok I'll also make use of it in mul! and repeat the whole exercise for RelSeries (in later PRs).

### CODE REVIEW

**Comment by thofma** [comment]
Is it working out?

**Comment by wbhart** [comment]
For me it is. I meant if it was accepted by others.

**Comment by thofma** [comment]
@tthsqe12 @fieker

**Review by tthsqe12 — APPROVED** [review]
Looks fine by me. I guess AbsSeries{GFElem{BigInt}} is missing in the test code?

**Comment by wbhart** [comment]
The test code doesn't test all possible rings. I didn't add test code for this because it was already there.

**Pull request merged**
