### PR TITLE
Rename `isFOO` to `is_FOO`

### PR DESCRIPTION
**Pull request by fingolfin**
See https://github.com/oscar-system/Oscar.jl/pull/1246#issuecomment-1092730935 for some background

CC @thofma @fieker @thomasbreuer

### CODE REVIEW

**Comment by thofma** [comment]
Hm, so is the plan to change the functions from `is* ` to `is_` one at a time?

**Comment by fingolfin** [comment]
Let's rename "all" at once. I've done a first step by adding a new macro `@alias` as proposed on https://github.com/oscar-system/Oscar.jl/issues/1265 (feel free to suggest an alternative name)

Assuming tests pass, we can rename more here, then make a new release.

At a later point, most uses of `@alias` could be replaced by equivalent `@deprecated` statements, or simply be removed.

**Comment by fingolfin** [comment]
For future work: I found the symbols rename by checking which symbols starting with `is` are exported by the module; of course this should be screened for wrong matches like `isomorphism`:
```julia
filter(x->startswith(string(x), "is"), names(AbstractAlgebra))
```
I also checked for `set` and `has` but these seemed to be fine, perhaps with exception of `setpermstyle` which I ignored for now.

Then I used the following shell script to mass rename the affected symbols; this could be applied to other packages (and later extended with more symbols).

It is really dumb because I generated it with a regex from the list of symbols to rename... if someone wants to rewrite it into something better (perhaps a julia script), feel free!

```sh
#!/bin/sh
#
git ls-files | xargs perl -pi -e 's;\biscompatible\b;is_compatible;'
git ls-files | xargs perl -pi -e 's;\bisconstant\b;is_constant;'
git ls-files | xargs perl -pi -e 's;\bisdegree\b;is_degree;'
git ls-files | xargs perl -pi -e 's;\bisdivisible_by\b;is_divisible_by;'
git ls-files | xargs perl -pi -e 's;\bisdomain_type\b;is_domain_type;'
git ls-files | xargs perl -pi -e 's;\bisexact_type\b;is_exact_type;'
git ls-files | xargs perl -pi -e 's;\bisgen\b;is_gen;'
git ls-files | xargs perl -pi -e 's;\bishessenberg\b;is_hessenberg;'
git ls-files | xargs perl -pi -e 's;\bishnf\b;is_hnf;'
git ls-files | xargs perl -pi -e 's;\bishomogeneous\b;is_homogeneous;'
git ls-files | xargs perl -pi -e 's;\bisinvertible\b;is_invertible;'
git ls-files | xargs perl -pi -e 's;\bisinvertible_with_inverse\b;is_invertible_with_inverse;'
git ls-files | xargs perl -pi -e 's;\bisirreducible\b;is_irreducible;'
git ls-files | xargs perl -pi -e 's;\bisisomorphic\b;is_isomorphic;'
git ls-files | xargs perl -pi -e 's;\bismonic\b;is_monic;'
git ls-files | xargs perl -pi -e 's;\bismonomial\b;is_monomial;'
git ls-files | xargs perl -pi -e 's;\bismonomial_recursive\b;is_monomial_recursive;'
git ls-files | xargs perl -pi -e 's;\bisnegative\b;is_negative;'
git ls-files | xargs perl -pi -e 's;\bispopov\b;is_popov;'
git ls-files | xargs perl -pi -e 's;\bispower\b;is_power;'
git ls-files | xargs perl -pi -e 's;\bispower_with_root\b;is_power_with_root;'
git ls-files | xargs perl -pi -e 's;\bisprobable_prime\b;is_probable_prime;'
git ls-files | xargs perl -pi -e 's;\bisreverse\b;is_reverse;'
git ls-files | xargs perl -pi -e 's;\bisrimhook\b;is_rimhook;'
git ls-files | xargs perl -pi -e 's;\bisrref\b;is_rref;'
git ls-files | xargs perl -pi -e 's;\bissnf\b;is_snf;'
git ls-files | xargs perl -pi -e 's;\bissquare\b;is_square;'
git ls-files | xargs perl -pi -e 's;\bissquare_with_sqrt\b;is_square_with_sqrt;'
git ls-files | xargs perl -pi -e 's;\bissquarefree\b;is_squarefree;'
git ls-files | xargs perl -pi -e 's;\bissubmodule\b;is_submodule;'
git ls-files | xargs perl -pi -e 's;\bissymmetric\b;is_symmetric;'
git ls-files | xargs perl -pi -e 's;\bisterm\b;is_term;'
git ls-files | xargs perl -pi -e 's;\bisterm_recursive\b;is_term_recursive;'
git ls-files | xargs perl -pi -e 's;\bistriu\b;is_triu;'
git ls-files | xargs perl -pi -e 's;\bisunit\b;is_unit;'
git ls-files | xargs perl -pi -e 's;\bisunivariate\b;is_univariate;'
git ls-files | xargs perl -pi -e 's;\bisweak_popov\b;is_weak_popov;'
git ls-files | xargs perl -pi -e 's;\biszero_column\b;is_zero_column;'
git ls-files | xargs perl -pi -e 's;\biszero_row\b;is_zero_row;'
```

**Comment by thofma** [comment]
OOM?

**Comment by fingolfin** [comment]
Note that the following symbols start with `is` but are *not* exported and I did not (yet?) deal with them. Perhaps I should, but then perhaps they should also be exported?
```
 :islocked
 :ismonomial_monomial
 :ispower_moduli
 :isreduced_form
 :isskew_symmetric
```

**Comment by fingolfin** [comment]
All the `has` functions start with `has_` (except for `hash` 😂 ), verified via tab completion as I was lazy:
```
julia> AbstractAlgebra.has
has_attribute        has_left_neighbor    hashindex
has_bottom_neighbor  hash                 hashp_seed
```
For `set` we see `setcoeff!` -- but confusingly there is also `set_coefficient!`; how are those two related?

Moreover there is `setpermstyle`

**Comment by wbhart** [comment]
The following are internal and should not be exported:

```
 :islocked (something internal for WeakDict) 
 :ispower_moduli (something internal for some ispower function)
 :isreduced_form (something internal for Submodule)
```

The following should be tested, documented and exported. It appears to be implemented correctly.

```
 :isskew_symmetric
```

The following is not used anywhere and it seems to be intended to be used generically, though its purpose is unclear from its name. It could be a candidate for removal if it is not used anywhere in Oscar.

```
 :ismonomial_monomial
```

**Comment by fingolfin** [comment]
> `:setindex` was so-named because of Julia's `:setindex`

Just to make sure I don't misunderstood: did you mean `setcoeff!` instead of the first `setindex`?

Regarding `set_coefficient!`, that one is really strange. There are only a handful commits even referencing it, all listed below. The first one introducing was ee4f225f0d36a49673c716bf01ee1f75a75ee394 from 2021-08-17 made by @wbhart 

- c391690ee Update docs/src/laurent_polynomial.md
- 37aa2827c allow polynomial interface example to work in oscar too
- adea04a98 fix divexact and divides
- 3a816a653 doc test fix
- ff8b41924 fix some broken LaurentPoly tests
- ee4f225f0 Implement set_coefficient! for univariate polynomials. (#986)

So I wonder if this was an accident and `set_coefficient!` should be merged with `setcoeff!` (under which name is another quetsion)

**Comment by fingolfin** [comment]
See also PRs #1154 and #1155

**Comment by thofma** [comment]
I would leave the `set_coeff[...]` business as is and just merge this PR here once it is rebased.

**Comment by wbhart** [comment]
Re `setindex`, yes thanks, that was a typo.

Re `set_coefficient`, it is now looking like it is a user safe version of `setcoeff` that sets the length and `normalises`. The other is an internal `setcoeff` used for the constructor.

I don't recall the discussion that led to this, so I'm not sure what this was in association with.

**Comment by wbhart** [comment]
The only issue referring to 'set_coefficient' is https://github.com/Nemocas/AbstractAlgebra.jl/issues/1019 which isn't very illuminating unfortunately.

**Comment by wbhart** [comment]
Ah, here is a PR which explains what 'set_coefficient' was about:

https://github.com/Nemocas/AbstractAlgebra.jl/pull/986

**Comment by fingolfin** [comment]
Rebased

**Pull request merged**
