### PR TITLE
Force coerce

### PR DESCRIPTION
**Pull request by fieker**
to be filled with life in Hecke/Oscar

currently not used at all in AA/Nemo to be minimally invasive

### CODE REVIEW

**Comment by thofma** [comment]
Was about to change the keyword to `throw_error` and do something else (to help with https://github.com/JuliaLang/julia/pull/32817). I will prepare a PR.

**Comment by thofma** [comment]
The compiler will not specialize if the argument type is `::Function`, see https://github.com/JuliaLang/julia/pull/32817/files#diff-8e08993d2cda98b5a210c3094dee2858.

**Comment by fieker** [comment]
On Fri, Apr 03, 2020 at 01:22:55AM -0700, thofma wrote:
> The compiler will not specialize if the argument type is `::Function`, see https://github.com/JuliaLang/julia/pull/32817/files#diff-8e08993d2cda98b5a210c3094dee2858.
> 
I am nut sure I understand where this is relevant or applies to.

**Comment by thofma** [comment]
```
g(f::Function, x) = f(x)
g2(f::T, x) where T = f(x)
```
`g` is very slow and `g2` is as fast as `f`.

But you are right, it doesn't matter here. We don't call `op` here.

(But still the keyword argument could have a better name.)

**Comment by fieker** [comment]
On Fri, Apr 03, 2020 at 01:29:24AM -0700, thofma wrote:
> ```
> g(f::Function, x) = f(x)
> g2(f::T, x) where T = f(x)
> ```
> `g` is very slow and `g2` is as fast as `f`.
But, the signature of g2 does no longer show f to be a function
g2(f::T, x) where {T <: Function} = f(x)

I'll use this upstream. Thanks
> 
> But you are right, it doesn't matter here. We don't call `op` here.
> 
> (But still the keyword argument could have a better name.)
I'll change this

**Pull request merged**
