### PR TITLE
Don't cache the SparsePolyRing when evaluating MPoly

### PR DESCRIPTION
**Pull request by thofma**
A long running job was crashing my computer because of this. I refactored it a bit so that the evaluate function creates the SparsePolyRing only once.

### CODE REVIEW

**Comment by wbhart** [comment]
I don't understand why this makes a difference. Shouldn't the caching prevent creating a new cached object every time in the original code. Unless either the symbol or the ring was being modified every time the function was called, I don't see why it would crash?

Or are you working around a compiler bug?

**Comment by thofma** [comment]
The original version cached the SparsePolyRings. So after evaluations of multivariate polynomials for 10000 different base rings, the cache was full of those SparsePolyRings. It crashed because there was no memory left.

**Comment by wbhart** [comment]
Ah, I see. That makes sense, thanks.

**Comment by thofma** [comment]
Thanks

**Pull request merged**
