### PR TITLE
feat: fix generalized indexing

### PR DESCRIPTION
**Pull request by thofma**
- make A[i::Int, js::Array] return a Vector and support views

### CODE REVIEW

**Comment by thofma** [comment]
Split off from #1565, since it is easier this way.

**Comment by thofma** [comment]
This is breaking, but I want to add it in this 0.37.* round.

**Comment by lgoettgens** [comment]
> This is breaking, but I want to add it in this 0.37.* round. Or maybe not.

If this is breaking, we cannot include it in 0.37.2. Instead, this has to wait for 0.38.0

**Comment by thofma** [comment]
Yeah, 0.38.0 it is

**Pull request merged**
