### PR TITLE
recursive mul_karatsuba

### PR DESCRIPTION
**Pull request by tthsqe12**
This turned out to be less useful that anticipated.
The Karatsuba algorithm needs to depend on a cutoff, and it usually has to be fairly high?
The `mul_karastuba(a, b)` works without a cutoff argument. How can I add a keyword argument `mul_karastuba(a, b, cutoff = 100)` to use my new code, but still use the old code without a keyword argument? Or maybe we scrap the old code? Or maybe we scrap this new code?

### CODE REVIEW

**Comment by fieker** [comment]
On Thu, Mar 04, 2021 at 06:09:51AM -0800, tthsqe12 wrote:
> This turned out to be less useful that anticipated.
> The Karatsuba algorithm needs to depend on a cutoff, and it usually has to be fairly high?
Depends on the rings... if arithmetic in the base_ring is expensive, a
cutoff at 2 is fine.
> The `mul_karastuba(a, b)` works without a cutoff argument. How can I add a keyword argument `mul_karastuba(a, b, cutoff = 100)` to use my new code, but still use the old code without a keyword argument? Or maybe we scrap the old code? Or maybe we scrap this new code?
You can do two functions:
mul_karastuba(a::T, b::T)
mul_karastuba(a::T, b::T, cuttoff:Int)
by not having a default value this are 2 functions... as long as you
always gove the cutoff value its fine. Otherwise rename yours?

**Comment by wbhart** [comment]
Or put the optional argument after a semicolon, or give it a default value.

**Comment by wbhart** [comment]
The cutoff should not be high. Generic code is intended for rings for which there is no C implementation, and therefore fairly complex rings. Otherwise the garbage collection overhead kills it.

**Comment by wbhart** [comment]
Some rings such as number fields support delayed reduction. You should also do this for best performance. See the developer documentation near the end of the Nemo documentation.

**Comment by wbhart** [comment]
Would be interested in seeing some timings and seeing how things behave asymptotically.

**Comment by tthsqe12** [comment]
@wbhart if you have a problem with the delayed reduction in macc_classical, please let me know.

**Comment by wbhart** [comment]
Yeah, unbalanced stuff is hard. You need the unbalanced toom-n algorithms (assuming you are not working in characteristic dividing n). But then we really grind the Jit to a halt.

**Comment by wbhart** [comment]
David Harvey (I think) implemented a generic FFT in Sage for asymptotically fast generic poly/series mul. But I don't know how successful that was. Asymptotic stuff is just hard in the presence of gc/jit/type inference.

**Comment by wbhart** [comment]
As for delayed reduction, I believe you have to use addmul_delayed_reduction! as mul_red! is not a guaranteed part of the interface as far as I recall. This is written up in the developer notes here:

https://nemocas.github.io/Nemo.jl/dev/developer/topics/#Delayed-reduction

**Comment by wbhart** [comment]
By the way, does your first and second call to @time mul_karatsuba really show the jit overhead? In a loop like that it looks like a lot of the code will already be compiled by the time the second iteration of the loop comes around.

It might make sense to restart Julia between each time, just to see what the real overhead is.

**Comment by wbhart** [comment]
Oh wait, I see your second call is with a different cutoff.

**Comment by thofma** [comment]
I think we should get this merged, to not let it bitrot forever.

**Comment by wbhart** [comment]
That's a good idea. It isn't used anywhere at present, and the timings show that it would be a bad idea to just replace the mul_classical with this as it could be a 100 times slowdown for small multiplication.

The next step (after this is merged?) is to come up with a tuning mechanism per ring, with a generic fallback for rings we haven't tuned for explicitly.

I still want to know how much the Jit time is affected before we switch this on. In the multivariate gcd code I wrote, I learned that it is almost universally a bad idea to just implement lots of algorithms with cutoffs in Julia, as you end up waiting 6 seconds for the Jit for a 0.1s operation (and that was gcd where the complexity is much higher than it is here)!

Also note that this is a slowdown for unbalanced stuff until really quite large inputs. There is no chance whatsoever that we can implement all the unbalanced Toom algorithms that would be needed to fix that and have the Jit give good results. Take a look in GMP/MPIR some time to see how many tens of thousands of lines of code this is, and how complex those algorithms are!

You are much better finding ways to reduce multiplication in other rings to integer operations and letting GMP take care of it.

**Comment by tthsqe12** [comment]
Ok. I will resolve the conflicts.

**Comment by tthsqe12** [comment]
@wbhart There is nothing wrong with this if you want to merge it so it doesn't continue to rot.

**Pull request merged**
