### PR TITLE
Comment some test and add more CI coverage

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
Presumably master is still version 1.2, hence the failure continues?

**Comment by thofma** [comment]
Yes, I updated the condition. Let's see what CI says now.

**Comment by kalmarek** [comment]
master has been 1.3.0-DEV since April?

https://github.com/JuliaLang/julia/blob/master/VERSION

**Comment by thofma** [comment]
Sure but
```julia
julia> v"1.3.0-DEV.100" < v"1.3"
true
```

**Comment by thofma** [comment]
Probably the test should be `VERSION >= v"1.3-DEV`, but I am too lazy to change it again :)

**Pull request merged**
