### PR TITLE
Move rand from Misc to Poly.jl.

### PR DESCRIPTION
**Pull request by wbhart**
I assume everyone is happy with the fact that it doesn't necessarily return a poly of the given degree, but up to that degree (depending on how many zero coefficients are randomly generated). The existing rand function also has this property.

### CODE REVIEW

**Comment by thofma** [comment]
I know that this has this property. I am not too happy with it. Are you happy with it? Is @fieker happy with it?

**Comment by wbhart** [comment]
I think it would be more useful if it just gave the degree asked for.

There are some things that bother me a little with the current random code. It requires reproducibility, so instead of doing rand(n:m) for the degree, it calls rand(rng, n:m) and so on. Hopefully everything will be ok if we check iszero on the randomly generated coeffs before using them.

But the other thing that bothers me is it calls rand(n:m) every iteration of the loop. And my guess is this does not give a very uniform distribution of random degrees, as any iteration of the loop could change the endpoint to something random and small.

I think we should perhaps overhaul some of the random functions.

**Comment by thofma** [comment]
I agree that it would be more useful if the degree had this behavior. I guess we can overhaul this after we moved it?

**Comment by wbhart** [comment]
Yeah I can add it to my list of things to work on.

**Pull request merged**
