### PR TITLE
Attempt to canonicalise more in fraction fields

### PR DESCRIPTION
**Pull request by wbhart**
Currently polynomials over Q and elements of Q are canonicalised. But fraction fields of polynomials over Q can end up with horrendous coefficients due to lack of canonicalisation. We attempt to canonicalise a little more aggressively.

### CODE REVIEW

**Comment by wbhart** [comment]
@fieker Can you tell me if this already solves your canonicalisation problem?

You have to add my AbstractAlgebra repo as a remote, e.g. as wbhart, fetch, then check out wbhart/canonicalisation

**Comment by tthsqe12** [comment]
Counterpoint: nowhere in the definition of "fraction field of an integral domain" is there a notion of "canonical fraction" or "hashing". If one wants to (1) have a fraction field over a base ring without a gcd, and (2) hash

**Comment by tthsqe12** [comment]
Sorry, a finger may have slipped here or there. These devices can be trickey contraptions.

**Comment by fieker** [comment]
This came up since `RationalFunctionField(QQ, "t")` is implemented interms of `Generic.Fractions`. And in `Q(t)` I'd like to have useful hashing and canonical reps.
I'll test Bill's fix on my code next.

**Comment by wbhart** [comment]
We'd need some kind of homomorphic hashing then. On my machine the current code already becomes useless by the time you raise an element to the power 4. Rational function fields are just incredibly slow, but they are infinitely slower if you canonicalise everything all the time.

**Comment by tthsqe12** [comment]
What kind of elements do you have that raising to the 4th power is a problem?

**Comment by wbhart** [comment]
Oh sorry, I meant a matrix raised to the power 4. My bad.

**Comment by tthsqe12** [comment]
Find, but how big are the matrix entries interms of coeffs and degree?

**Comment by wbhart** [comment]
Here is my exact code:

```
julia> using Nemo

julia> R, x = PolynomialRing(QQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> K = FractionField(R)
Fraction field of Univariate Polynomial Ring in x over Rational Field

julia> S = MatrixSpace(K, 10, 10)
Matrix Space of 10 rows and 10 columns over Fraction field of Univariate Polynomial Ring in x over Rational Field

julia> M = rand(S, 0:5, -10:10)
[         (-1//3*x^4 + 1//21*x^3 - 1//6*x^2 + 2//9*x - 1//15)//(x^4 - 1//24*x^3 + 1//3*x^2 - 8//3*x - 3//7)                             (15//4*x^4 - 27//80*x^3 - 9//16*x^2 - 21//16*x + 9//16)//x   (-3//10*x^5 - 1//2*x^4 + 1//18*x^3 - 1//18*x + 1)//(x^5 - 5//27*x^4 + 1//6*x^3 + 1//6*x^2 - 1//15*x + 7//30)                                                  (-4//7*x^2 - 18//5*x + 28//9)//(x^5 + 4//7*x^4 + 7*x^3 + 4//3*x^2 - 16//3*x)                                                          (-35//6*x + 14//3)//(x^3 + 21//2*x^2 + 7//12*x + 7//54)                                                                                                3            (-1//15*x^4 + 2//5*x^3 + 2//45*x^2 - 1//20*x + 3//40)//(x^3 - 1//10*x^2 - 8//35*x + 8//15)                                                                                 9//14//(x^2 + 5//28*x + 15//28)                                                                (16*x^2 + 2)//(x^2 - 8*x - 8)                                                   (-4*x^3 - 6*x^2 - 8//3*x - 16//7)//(x^2 + 1//3*x + 4//3)]
[                                 (-40//27*x^4 + 20//3*x^3 - 16//9*x^2 - 16//27*x - 4//9)//(x^3 - 4//3*x^2)                         (-2//5*x^4 - 1//3*x^3 + 3//10*x^2 + 5//2*x - 1//5)//(x + 9//7)                                                                     -16//5//(x^5 - 8//7*x^2 + 4//5*x + 16//25)                                                                                         (-30//7*x^2 - 40*x + 80//7)//(x + 10)                                                         (6*x^5 + 3//2*x^4 + 42*x^2 + 12//5*x - 6)//(x^2 - 24//5)                                                                    -1//30*x^3 - 7//24*x^2 + 4//3                                                            -7//5//(x^3 - 35//2*x^2 - 35//32*x - 7//8)   (1//18*x^4 + 2//27*x^3 - 5//3*x^2 - 5//42*x - 1//2)//(x^5 + 1//12*x^4 - 3//2*x^3 - 1//9*x^2 + 2//27*x - 5//6)                                               (-x^3 + 5//6*x^2 - 5//2*x - 1//4)//(x - 7//16)                    (7//3*x^3 + 70//81*x^2 + 7//9*x - 7//81)//(x^4 + 14//9*x^3 - 49//72*x^2 - 49//54*x - 1)]
[                    (x^5 + 2//3*x^4 + 1//3*x^3 + 6//7*x^2 + 2//9*x - 1//10)//(x^3 + 6//5*x^2 + 1//2*x + 3)                                                            2//3//(x^2 + 1//3*x - 4//9)         (5*x^5 + 16//9*x^4 + 3//5*x^3 + 7//4*x^2 - 3//4*x + 2)//(x^5 - 2*x^4 + 3*x^3 + 18//7*x^2 + 1//4*x + 2)                                                                                               -5//54//(x^2 + 7//30*x - 1//14)                                                                        -3//4*x^4 - 9*x^3 + 8//3*x^2 + 9//4*x + 3       (-2//15*x^4 - 1//27*x^3 + 1//36*x^2 + 2//15*x + 1//15)//(x^3 - 8//63*x^2 + 2//9*x + 2//45)                                                  (-6//5*x + 15//2)//(x^3 + 3//4*x^2 + 3//2*x - 21//8)                                  (9//4*x^3 - 15//2*x^2 + 10*x + 3//4)//(x^5 + x^3 - 20//9*x^2 - 20//3*x + 9//2)                                              2*x^4 + 6//5*x^3 - 14//9*x^2 + 32//27*x - 28//9                                        (-7//18*x - 5//63)//(x^4 - 4//45*x^3 - 1//12*x^2 + 5//27*x - 2//27)]
[                                   (x^4 + 8//7*x^3 - 56//3*x^2 - 8//7*x + 20//9)//(x^2 - 32//21*x + 16//9)                                                       (1//5*x^3 + x^2 - 2//3)//(x + 4)                                           (32//9*x - 20//81)//(x^4 - 5//9*x^3 + 40//63*x^2 + 16//27*x + 8//27)                                                               9//20//(x^5 - 15//8*x^4 + 1//8*x^3 - 15//8*x^2 + 3//4*x - 9//4)                   (-1//4*x^5 + 4*x^4 + 8//7*x^3 + 1//2*x + 9//2)//(x^5 + 10//9*x^4 + 7//6*x^3 + 3//5*x^2 - 8//5)                                         (-3//4*x^4 + 3*x^3 - 7//2*x^2 - 12*x + 4//3)//(x + 2//3)   (-2//15*x^5 + 3//5*x^4 + 2//9*x^3 + 1//5*x^2 - 4//25*x - 1//4)//(x^3 - 4//35*x^2 - 3//25*x - 8//25)                                                                                         -2*x^2 + 32//5*x + 9//5                                                            50//7//(x^3 + 5//28*x^2 + 9//7*x)                                                                    -7//15*x^3 + 7//10*x^2 - 7//4*x + 7//40]
[                                                                           (-5//2*x)//(x^2 - 18//5*x + 12)   (5*x^4 + 2*x^3 - 6*x^2 + 3//5*x - 20//7)//(x^4 - 1//2*x^3 + 12*x^2 + 8//7*x - 10//7)                                                          -2//3//(x^4 - 4//15*x^3 - 10//9*x^2 - 2//3*x - 4//15)                                       (7*x^3 - 7//8*x^2 + 21//20*x + 7//20)//(x^4 + 63//4*x^3 + 49//24*x^2 + 7//12*x - 14//3)                               (-50//9*x^4 + 15*x^3 + 4//3*x^2 - x - 5//2)//(x^3 - 35//27*x^2 - 25//6*x - 50//21)                                           -5//9//(x^4 + 8//27*x^3 - 4//9*x^2 - 16//9*x + 10//27)                                                                   10//3*x^3 + 20//3*x^2 - 40//9*x - 1                                                           (2//5*x^2 - 16//45*x + 8//27)//(x^2 - 8//9*x - 5//18)       (9//16*x^2 + 15//4*x - 1//4)//(x^5 - 3//2*x^4 + 3//4*x^3 + 3//4*x^2 - 3//8*x + 15//14)                         (25//28*x^4 - 25//14*x^3 - 20//7*x^2 - 45//28*x - 15//7)//(x^2 + 40//7*x + 10//21)]
[                                           (-3//2*x + 12//7)//(x^4 + 12//7*x^3 + 5//2*x^2 + 6//5*x - 3//5)                                                    5//2//(x^3 - 3*x^2 - 7//8*x - 1//8)                                                                               (2//9*x + 1//2)//(x^2 + 2*x + 1)   (8//15*x^5 - 4//9*x^4 + 2//45*x^3 + 20//81*x^2 + 4//9*x + 8//9)//(x^5 + 32//27*x^4 + 4//9*x^3 - 2//27*x^2 - 4//45*x - 2//9)                                          (4//3*x^4 - 5//9*x^3 - 5//21*x^2 + 4//3*x + 5//3)//(x^2 + 35//18*x + 5)                                                                                -2//21*x + 15//14                                                            (40//9*x^2 + 10//9*x - 25//18)//(x + 2//3)                                                                                            7*x^2 - 35//16*x - 2                                                                (-15//8*x - 5//2)//(x + 5//3)                                      (20//9*x^3 + 1//3*x^2 - 20//27*x - 25//12)//(x^3 - 5//12*x^2 + 35//3)]
[(-1//6*x^5 - 1//14*x^4 + 3//7*x^3 + 1//4*x^2 - 1//2*x - 5//2)//(x^4 - 1//3*x^3 + 5//4*x^2 + 1//6*x - 2//5)                                  6//49//(x^4 - 3//35*x^3 + 3//7*x^2 - 2//49*x + 1//14)               (27//40*x^4 + 81//8*x^3 + 21//8*x^2 - 45//8*x + 9//40)//(x^5 - 27//16*x^4 + 3//8*x^3 - 9//4*x^2)                                                                            (25//8*x^3 + 35//4*x - 25//18)//(x^2 - x + 25//16)   (5*x^5 - 5//2*x^4 - 15*x^3 + 15*x^2 + 7*x - 15//4)//(x^5 - 10//7*x^4 + 50//7*x^3 - 25//2*x^2 - 25//2*x + 5//9)                            (-42*x^4 - 36*x^3 - 15//2*x^2 - 12*x + 6)//(x^3 + 6*x^2 - 4*x - 6//5)                 (-5*x^4 + 15//16*x^3 + 15*x^2 + 5//3*x - 25//18)//(x^3 + 15//8*x^2 + 15//4*x - 15//2)                                                                      (-4//9*x - 3//10)//(x^2 - 8//15*x - 2//15)             (1//16*x^5 + 5//6*x^4 - 5//4*x^3 - 1//5*x^2 - 1//2*x - 3)//(x^3 + 7//10*x^2 - 1)                                  (-1//2*x^5 + 1//2*x^4 + 3//4*x^3 - 1//4*x^2 - 2//3*x + 5//18)//(x - 7//8)]
[               (-1//40*x^5 + 9//32*x^4 - 3//32*x^3 + 1//4*x^2 - 5//24*x - 3//16)//(x^3 + 5//8*x^2 - 7//72)                                                         50//3//(x^2 - 50//7*x + 10//3)                                              (2//15*x^3 - 2//15*x - 1//7)//(x^3 + 3//35*x^2 + 8//45*x - 3//10)                                                                                      (15//7*x + 10)//(x^2 - 21//10*x + 3//10)                                                      1//2*x^5 + 9//8*x^4 - 3//16*x^3 - 1//8*x^2 + 1//36*x + 1//3                                (4//25*x^2 - 64//25*x + 6//5)//(x^3 - 4//5*x^2 - 48//35*x - 4//5)                                                                              9//4*x^2 + 4//9*x - 3//2                                                                                          5//(x^2 - 4*x + 1//20)                       (-3//20*x^3 + 15//16*x^2 + 9//32*x - 9//20)//(x^3 - 1//2*x^2 - 3//5*x)   (-x^4 + 6*x^3 + 40//27*x^2 + 12//5*x - 10//3)//(x^5 - 4//3*x^4 + 14//3*x^3 - 8//21*x^2 + 40//3*x + 8//9)]
[                                   (3//2*x^5 + 1//2*x^4 + 8//3*x^3 - 4//7*x^2 - 3//4*x - 2//9)//(x + 8//3)                   (-4//21*x^4 - 20//21*x^3 - 2//21*x^2 + 16//7*x - 16//49)//(x + 4//7)                                       (5//3*x^2 - 5//6*x + 5//3)//(x^5 + 5*x^4 - 5//9*x^3 + 25//21*x + 40//27)                                                                                                    3//4*x^3 - 3//4*x^2 - 9//4                                                          15//16//(x^4 - 25//24*x^3 + 25//32*x^2 - 5//8*x + 5//8)   (4//5*x^5 + 40//7*x^4 + 5*x^3 - 24*x^2 + 8//3*x - 8)//(x^4 + 4*x^3 - 4//7*x^2 + 8//3*x - 4//9)                                                                     -8*x^3 + 6//7*x^2 + 4//9*x - 8//7                                                                                                          27//14                                           (-5//6*x^2 - 5//4*x + 5//8)//(x^2 - 4//3*x - 1//2)                                                                              1//2//(x^2 - 5//8*x - 15//14)]
[                                                                  (-2//5*x^3 + 9//5*x - 6//5)//(x + 9//25)                                                              -9//2*x^3 + 7//4*x - 5//2                                                                                             4//3//(x^2 - 2//9)                             (5//8*x^3 + 25//4*x^2 - 25//12*x + 25//6)//(x^5 + 35//16*x^4 + 2*x^3 - 5//4*x^2 + 5//4*x - 15//2)                                                         (-8//7*x^5 + 1//3*x^4 - 4*x^3 - 10*x^2 + 18//7)//(x - 2)                                           -1//9//(x^4 - 2//25*x^3 - 1//20*x^2 + 1//20*x + 9//70)                                                         -15//7//(x^3 - 45//14*x^2 + 54//7*x - 18//35)                                                                                    -21//4*x^2 - 7//6*x + 35//16   (20//27*x^3 + 2//15*x^2 + 14//3*x - 14//3)//(x^4 - 4//3*x^3 + 20//27*x^2 + 2//27*x - 2//3)                                                             (3//16*x^3 - 1//10*x^2 + 7//12*x)//(x - 5//14)]

julia> @time M^4;
  2.503805 seconds (3.17 M allocations: 726.828 MiB, 0.37% gc time)
```

**Comment by tthsqe12** [comment]
wow, that is terrible.
```julia
julia> R, x = PolynomialRing(QQ, "x");

julia> S = MatrixSpace(R, 10, 10);

julia> M = rand(S, 0:5, -10:10);

julia> @time M^4;
  0.450413 seconds (531.43 k allocations: 30.201 MiB, 1.64% gc time, 99.60% compilation time)

julia> @time M^4;
  0.001719 seconds (625 allocations: 49.906 KiB)

julia> K = FractionField(R)
Fraction field of Univariate Polynomial Ring in x over Rational Field

julia> S = MatrixSpace(K, 10, 10)
Matrix Space of 10 rows and 10 columns over Fraction field of Univariate Polynomial Ring in x over Rational Field

julia> M = rand(S, 0:5, -10:10);

julia> @time M^4;
  2.561824 seconds (3.79 M allocations: 709.090 MiB, 0.65% gc time, 20.52% compilation time)

julia> @time M^4;
  2.210345 seconds (3.13 M allocations: 675.598 MiB, 6.68% gc time)

```

**Comment by fieker** [comment]
This does fix "my" problems, thanks!

**Comment by wbhart** [comment]
Ok, then let's merge it. I did NOT test that Frank/Thomas' example that we worked on a couple of years ago still runs at an acceptable speed.

**Pull request merged**
