### PR TITLE
extend change_base_ring to matrix algebras

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by wbhart** [comment]
You don't need to write Generic in front of MatrixElem because you are already in Generic. But I guess this is not a major problem.

We also have a MatrixAlgebra-test.jl, where MatrixAlgebra stuff is tested. It's not such a big deal if the test code isn't moved to there, but in theory it probably should be in there. I mainly just wanted to make you aware of it, in case you didn't know.

**Comment by rfourquet** [comment]
> You don't need to write Generic in front of MatrixElem because you are already in Generic. 

I wrote it only in the docstring, as `MatrixElem` is not exported.

> We also have a MatrixAlgebra-test.jl, where MatrixAlgebra stuff is tested. It's not such a big deal if the test code isn't moved to there, but in theory it probably should be in there. I mainly just wanted to make you aware of it, in case you didn't know.

I'm well aware of that indeed, there is a tension between separating code into files related to specific objects, and DRY. Here the `change_base_ring` code is defined only once in `Matrix.jl`, and for tests it would be pure duplication to put it both in `Matrix-test.jl` and `MatrixAlgebra-test.jl`, meaning more work when the tests are updated. I will of course update according to what the maintainers recommend!

**Comment by thofma** [comment]
Do you agree that we should start exporting `Generic.MatrixElem` from AA? It is the type that one needs when writing code for arbitrary matrices in the AA + Nemo ecosystem.

**Comment by wbhart** [comment]
@rfourquet Of course you are right. No need to change the code here.

@thofma I am not sure if we can make it work. But if we can, I have no objection.

**Comment by wbhart** [comment]
@rfourquet Could you also add a check that you get a MatrixAlgebraElem out if you start with one going in? Looks like that will have to be a separate PR, as @thofma just merged this. No need to wait for this test before issuing a release.

**Comment by rfourquet** [comment]
> Could you also add a check that you get a MatrixAlgebraElem out if you start with one going in?

Good idea, cf. #416

**Pull request merged**
