### PR TITLE
tests: use an easy to include setup file

### PR DESCRIPTION
**Pull request by rfourquet**
When wanting to run a specific test/testset, it's easy to copy-pase it
into the REPL, but it can be annoying to find the setup-code, like
constants or functions defined usually at the top of the test file.
All this setup code is here put in test/setup.jl, so that it's always
predictable (and easy) what one has to do to inject to required
dependencies in the REPL: `include("test/setup.jl")`.

Another nice thing to have is to be able to run one single test file. But it's currently not always supported (e.g. `include("test/generic/Matrix-test.jl")` won't work). So I also propose to conditionally include the "setup.jl" file at the top of test files (which need setup), so that they can be run independently. I currently did it only for "Matrix-test.jl" and will continue if the idea is supported. This looks like
```julia
if !@isdefined SETUP
   include("../setup.jl")
end
```

### CODE REVIEW

**Comment by fieker** [comment]
In Hecke (and possibly Nemo) we implemented
Hecke.test_module(file, false)
or similar, running only that file in the same session...

**Comment by rfourquet** [comment]
Yes, I had a similar idea for a future PR, mimicking what is available in Julia: `Base.runtests(list_of_test_names)`.

**Comment by fieker** [comment]
On Wed, Nov 27, 2019 at 06:30:55AM -0800, Rafael Fourquet wrote:
> Yes, I had a similar idea for a future PR, mimicking what is available in Julia: `Base.runtests(list_of_test_names)`.
> 
Difference being that "our" version can run selected tests in the same
julia or not.
runtests can not

**Comment by rfourquet** [comment]
> Difference being that "our" version can run selected tests in the same julia or not.

I noticed yes. I can see the usefulness of "in the same julia" when hacking a routine at the REPL and having the tests take the changes into account immediately, do you have another use case?

**Comment by fieker** [comment]
On Wed, Nov 27, 2019 at 07:41:13AM -0800, Rafael Fourquet wrote:
> > Difference being that "our" version can run selected tests in the same julia or not.
> 
> I noticed yes. I can see the usefulness of "in the same julia" when hacking a routine at the REPL and having the tests take the changes into account immediately, do you have another use case?
> 
Yes/ no:

using global assignments one can recover intermediate results in failing
tests to invesigate them in the REPL.
So its more of the same...

**Comment by thofma** [comment]
Addtionally, it is faster since you don't have to compile everything over and over again.

**Comment by rfourquet** [comment]
Makes sense, thanks.

**Comment by rfourquet** [comment]
The problem this was trying to address is mostly solved for me with `ReTest`. The rare cases where I'd still like to have a setup.jl file is not enough motivation, so I will close but I can update the PR if someone has an interest.

**Pull request closed without merging**
