### PR TITLE
Turn permutation groups into iterators

### PR DESCRIPTION
**Pull request by thofma**
I always want to do this without the `element` function.

### CODE REVIEW

**Comment by kalmarek** [comment]
:+1: 

we could delete `elements` function then and keep only the unsafe `elements!`

**Comment by thofma** [comment]
Good idea, but then I don't know where to put the docstring.

**Comment by kalmarek** [comment]
I think it should be ok to replace the existing docstrings with something like this:
https://gist.github.com/kalmarek/238a807da33da7065eca3b3dfed35e07

(new part of `perm.md` starting at line 164)

**Comment by kalmarek** [comment]
no, but we can establish this and other things in Tübingen the next week ;-)

**Comment by wbhart** [comment]
Oh dear, the nightlies are not working again.

**Pull request merged**
