### PR TITLE
Move divhigh, mulhigh_n and divexact_low from Misc. Add tests.

### PR DESCRIPTION
**Pull request by wbhart**
Let me know if you want these three documented.

Note that there were bugs in these, so Hecke tests may now fail as I have corrected their implementation.

I also sped up the third function using unsafe operators.

### CODE REVIEW

**Comment by thofma** [comment]
Can you rebase? Then we see the downstream tests and also if Hecke is failing.

**Comment by wbhart** [comment]
Did you already rebase it? It doesn't seem to need rebasing at the moment.

**Comment by thofma** [comment]
No, it does not need it, but it would be good if we would do it. Then the downstream will be run that I added in #799.

**Comment by wbhart** [comment]
Done

**Comment by thofma** [comment]
Sorry, but I think your master was not up to date, so it is still missing #799. I tried again doing it myself and I still cannot push directly to your branch. Very strange.

**Comment by thofma** [comment]
Ah oops, it is working, thanks. Ignore my last comment.

**Comment by wbhart** [comment]
Have you tried making yourself a maintainer?

**Comment by wbhart** [comment]
I did rebase it a second time. Indeed the latest patch wasn't in.

**Comment by wbhart** [comment]
All the failures here seem to be due to unsatisfiable requirements for package Oscar, which doesn't seem related to this PR.

Any chance it could be merged? Or is there something else I need to do here?

**Comment by thofma** [comment]
Yes, this is expected. This is good to go from my part. @fieker?

**Pull request merged**
