### PR TITLE
More sub-matrix access functions

### PR DESCRIPTION
**Pull request by johannes-hoffmann**
Just some things I stumbled upon when working with sub-matrices:
* minor update on one existing `getindex` function to match the others
* added `getindex` functions to support `M[1, 2:3]`, `M[4:7, 5]`, `M[5, :]`, `M[:, 2]` for `M` of type `MatElem` to return the indicated sub-matrices

### CODE REVIEW

**Comment by kalmarek** [comment]
we should probably implement the whole [`AbstractArray` interface](https://docs.julialang.org/en/v1/manual/interfaces/index.html#man-interface-array-1).
`similar` parts were just done by @rfourquet. All the building blocks are in `Base` (like bounds checking, converting multi-indexes, etc.), we only need to check which of the defaults don't work for `MatSpaceElem`s

**Comment by johannes-hoffmann** [comment]
I must admit I have no idea why the Julia 1.1 tests for module intersection failed, but at least they failed consistently.

If there are already plans for work in this area feel free to close this PR.

**Comment by wbhart** [comment]
@kalmarek There are some parts of the AbstractArray interface we cannot implement, due to the fact that they rely on Julia magic which results in types that cannot be passed to C libraries, like Flint.

Our current thinking is it would be a bad idea to support functionality which we could not implement in Nemo. We'd like to keep being able to say to people that if there code works in AbstractAlgebra it probably works in Nemo (but faster). It's not quite true at present, but it's close enough to being true that we could actually make it true with a very small amount of work.

**Comment by wbhart** [comment]
@kalmarek It's more complicated than that. Suppose someone starts with a Nemo matrix, then takes a view of it, then calls a Nemo function on it. There's no way the code can just automatically accept the view instead of a Nemo matrix as it has to be passed to a C function.

What you are proposing is that we would either have to duplicate all the Nemo functions to accept views (and then convert them back to real Nemo matrices), or that we would have to duplicate all the Nemo functionality in AbstractAlgebra, which simply isn't practical (Flint is over 300,000 lines of code).

So as I see it, there is literally no way to do what you want to do.

**Comment by wbhart** [comment]
.... at least not without one hell of a lot of work, which we don't have the resources for.

**Comment by kalmarek** [comment]
@wbhart I might be mis-reading the docs, but there is no mention of views in AbstractArray interface...

**Comment by wbhart** [comment]
Probably we didn't document it yet. I guess we should.

**Comment by kalmarek** [comment]
I meant: Julia's `AbstractArray` interface which I suggest implementing does not require us to support views of any kind. 
Your argument above is more of "we can't write signatures such that they accept both `MatElem`s and `View`s" which is a completely orthogonal issue. I only suggest implementing a bunch (5? 7?) additional functions so that we can have slicing, broadcasting and iteration as julia users are used to.

**Comment by wbhart** [comment]
Apparently I misunderstood. I'm in favour of implementing all the Julia functions that we can meaningfully support for Nemo matrices.

**Pull request merged**
