### PR TITLE
Refactor `polysubst.jl`

### PR DESCRIPTION
**Pull request by lgoettgens**
Contains https://github.com/Nemocas/AbstractAlgebra.jl/pull/1888 to avoid conflicts.

This goes in hand with Nemocas/Nemo.jl#1933, but should hopefully be non-breaking on its own. Let's wait for CI to verify that.

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]

**Comment by fingolfin** [comment]
Fine by me but unfortunately it breaks HeckeCI tests:
```
Error During Test at /home/runner/.julia/packages/Hecke/p6Ffl/test/NumField/Hilbert.jl:1
  Got exception outside of a @test
  MethodError: (::ZZPolyRingElem)(::zzModPolyRingElem) is ambiguous. Candidates:
    (f::PolyRingElem)(a::PolyRingElem) in AbstractAlgebra at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Poly.jl:3363
    (f::ZZPolyRingElem)(a::RingElem) in Nemo at /home/runner/.julia/packages/Nemo/0TzOv/src/polysubst.jl:27
    (f::PolyRingElem)(a::RingElem) in AbstractAlgebra at /home/runner/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Poly.jl:3371
    (f::ZZPolyRingElem)(a) in Nemo at /home/runner/.julia/packages/Nemo/0TzOv/src/polysubst.jl:16
  Possible fix, define
    (::ZZPolyRingElem)(::PolyRingElem)
```
Also OscarCI with a similar one

**Comment by thofma** [comment]
Good look with the ambiguities.

It is a bit hard to check that this does not introduce regressions. Accidentally this could change things that used to compute `f(g)` as `compose(f, g)` to suddenly use `evaluate(f, g)` instead.

**Comment by lgoettgens** [comment]
The ambiguities only occur if we only have this patch in but not the one for Nemo. So let me mark this as breaking, and we can apply it with the next breaking release.

Regarding @thofma s comment: I don't see how this could be possible. The only difference is that if one calls `f(g)` for different types of Polys, then this gets delegated to `subst` via a different call function than before.

Edit: maybe there are some changes regarding stacks of poly rings. I'll play around with it

**Comment by thofma** [comment]
> Regarding @thofma s comment: I don't see how this could be possible. The only difference is that if one calls `f(g)` for different types of Polys, then this gets delegated to `subst` via a different call function than before.

All I was trying to say is that we (the reviewers) have to check a bit more carefully, since for many argument combinations, both `compose(f, g)` and `evaluate(f, g)` give the right result, and so regressions are not detected by the tests.

**Comment by fingolfin** [comment]
> since for many argument combinations, both compose(f, g) and evaluate(f, g) give the right result, and so regressions are not detected by the tests.


OK but if there are combinations were only one (or neither 😨 ) gives right results, then surely the very first thing we should do is to add those to the tests ... :-)

**Comment by thofma** [comment]
OK, let's do this.

**Review by thofma — APPROVED** [review]

**Pull request merged**
