### PR TITLE
Add elementary row/column operations

### PR DESCRIPTION
**Pull request by thofma**
Closes https://github.com/Nemocas/Nemo.jl/issues/621.

@wbhart I don't understand where to put the documentation. Where in the documentation do I have to put the `@docs add_row(....)` block? There is `matrix.md`, `matrix_spaces.md` and `matrix_algebras.md`. I wanted to put it next to `swap_rows`, but it is in `matrix_spaces.md` and weirdly the docstring of `swap_rows` is never included. Just this `swap_rows(::MyMat)` stuff.

### CODE REVIEW

**Comment by wbhart** [comment]
If it is a required part of the general matrix interface which must be implemented by all matrix implementations, e.g. by Singular.jl and Gap.jl matrices, then it goes in matrix_spaces.md.

If it's generic functionality provided by AbstractAlgebra for all matrix types that implement our interface, then it goes in matrix.md. If it is specific to just matrix algebras then it goes in matrix_algebras.md.

We probably should rearrange our docs a bit. For example, matrix_spaces.md should probably be renamed matrix_interface.md. We should probably also distinguish generic and abstract as we've previously discussed.

The problem is so far most acute for modules. We have some methods that are specific to our particular implementation of modules over a euclidean domain that are neither required methods for other implementations, nor generic methods provided for any implementation of modules that follows our interface. Moreover, it is totally unclear what the relation of submodules and quotient modules and snf modules and module homomorphisms is to this hierarchy.

**Comment by thofma** [comment]
I added the documentation and also the other two functions that were asked for.

I also bumped the Documenter version and made the doctests pass.

**Comment by wbhart** [comment]
The docs did not build.

**Comment by thofma** [comment]
Yeah wrong Documenter version. I fixed it.

**Pull request merged**
