### PR TITLE
Fix for #334

### PR DESCRIPTION
**Pull request by thofma**
I had to disable some tests, because they are really failing. But I prefer first push this here.

### CODE REVIEW

**Comment by thofma** [comment]
P.S.: Waiting for a fix in julia will take forever. So I fixed it by rewriting the type gymnastics using more julia idiomatic constructs.

**Comment by thofma** [comment]
Hmm, still failing on nightlies.

**Comment by thofma** [comment]
This should be good to go @wbhart

**Comment by wbhart** [comment]
The nightlies still look like they are hanging. Or do they just need restarting?

**Comment by thofma** [comment]
We are ignoring the nightlies since a few months

**Comment by wbhart** [comment]
Thanks @thofma I will close this out on my todo list and close the ticket.

**Pull request merged**
