### PR TITLE
Make use of karatsuba where practical.

### PR DESCRIPTION
**Pull request by wbhart**
This contributes to the karatsuba part of #761.

### CODE REVIEW

**Comment by wbhart** [comment]
This will have to be redone. Apparently the new mul_karatsuba is not hooked up properly. One can only call it by calling Generic.mul_karatsuba and only then with a cutoff!

So I have to do all the timings again and rewrite this code. Argh!

**Comment by wbhart** [comment]
Actually, I don't see a way to use the new mul_karatsuba. I can only specify a length crossover, which is going to depend on the number of bits of the polynomials at each iteration, which I can't compute in advance. For now we can use the original mul_karatsuba as implemented in this PR.

**Comment by thofma** [comment]
Could the failure on 1.6 be related or is it a fluke?

**Comment by wbhart** [comment]
Hmm, it seems like it could be related. I better investigate.

**Comment by wbhart** [comment]
I can reproduce it. It is failing in characteristic 4*2^i. I have no idea why; it's a simple identity with no divisions. I've overlooked something somewhere.

**Comment by wbhart** [comment]
Ah, in those characteristics the leading coefficients can vanish, so it needs normalising. I'll push a fix in a minute.

**Pull request merged**
