### PR TITLE
Change Array to Vector or Matrix; run CI doctests with Julia 1.6

### LINKED ISSUE #961: Doctests don't work in Julia 1.6 due to Array{T, 1} -> Vector{T}

### PR DESCRIPTION
**Pull request by fingolfin**
This should only be merged once @wbhart (and anybody else) is done moving things around (well, and once tests pass). As soon as that's the case, I can regenerate the first commit, which was made using these commands:

    git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*2\s*\}/Matrix{\1}/g'
    git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'
    git ls-files | xargs perl -pi -e 's/Array\{([^{}]+(\{((?>[^{}]+)|(?2))*\})?),\s*1\s*\}/Vector{\1}/g'

Resolves #961

### CODE REVIEW

**Comment by thofma** [comment]
I initially thought that we wanted to change only the doctests, but I am also happy if we change everything.

**Comment by thofma** [comment]
Are you happy with this @wbhart?

**Comment by wbhart** [comment]
Sure, but please don't merge it before merging my large patch. This one was done using automated tools. Mine was not.

**Comment by thofma** [comment]
I plan to rebase and merge this and then make a new patch release. Afterwards we merge the breaking PRs. Does this sound ok @wbhart?

**Comment by wbhart** [comment]
Should be ok.

**Pull request merged**
