### PR TITLE
add derivation and jacobi to src/generic/MPoly.jl

### PR DESCRIPTION
**Pull request by heiderich**
The function `derivative` allows to compute the partial derivatives of a multivariate polynomial in `MPoly`.
The function `jacobi` computes the partial derivatives of a multivariate polynomial with respect to all generators of the parent ring.

Note: In the long term it might be preferable to implement these functions for `MPolyElem`. Currently however there seems to be no interface in `MPolyElem` to access the exponents. Therefore I propose this implementation in `MPoly`.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for the contribution.

There should be a docstring for jacobi, and the docstrings for jacobi and derivative should be used (with examples) in the docs/src/mpolynomial.md file.

Also, do we have an isgen function that we can use, instead of creating the list of generators every time to compare with? This seems particularly inefficient.

Also, there should be a simple test for jacobi, even if it just computes it for one polynomial and compares the output. This is to make sure the function is callable. But you might also think about any corner cases. Does it compute the correct answer without crashing in those corner cases (degree 0, or something like that).

**Comment by fieker** [comment]
While we're discussing, what about a rename to jacobi_matrix or so?
jacobi could also refer to the jacobi_symbol on (univariate)
polynomials...

Greetings
 Claus

**Comment by wbhart** [comment]
The prototype in the docstrings need correction. For example:

```
jacobi(f::MPoly{T})::Array{MPoly{T},1}
```

should be

```
jacobi{T <: AbstractAlgebra.RingElem}(f::MPoly{T})::Array{MPoly{T},1)
```

(Note the correction of the final parenthesis also.)

and

```
derivative(f::MPoly{T}, x::MPoly{T})
```

should be

```
derivative{T <: AbstractAlgebra.RingElem}(f::MPoly{T}, x::MPoly{T})
```

Also, the examples shouldn't simply be included in a random place in the docs. There should be a section for derivative and another section for Jacobi matrix. You then need to use the @docs code section to import the docstrings into the docs, as we do for some of the other generic functionality.

I've probably told you the wrong file to put the docstrings and examples in. They should probably go in mpolynomial_rings.md. However, I guess this would be optional functionality rather than required functionality, so we probably need to add a new section for that, immediately under the optional functionality section.

Obviously, in the long run, we'll want the docs in the file I said, but only when the functions work for all multivariate types. MPoly is a little unusual in that regard. It is an interface that is still being developed, and so there are no generic implementations available for all multivariate types, at present.

**Comment by heiderich** [comment]
I think one needs the generators in order to construct the derivative. But I constructed the list of generators twice. I changed this so that it is only constructed once.

I added a docstring for `jacobi`.

The name `jacobi` was inspired by the terminology of Singular, see 

https://www.singular.uni-kl.de/Manual/4-1-1/sing_271.htm

only that I used `jacobi` instead of `jacob`. The idea was that one may later on define other functions with the same name `jacobi` that take an array of polynomials or an ideal as an input. For the function implemented right now, the name `jacobi_matrix` would not be appropriate in my opinion, as it does not return a matrix, but a one-dimensional array. Should we have different names for these functions or a common one?

I illustrated the use of `derivation` and `jacobi` in `docs/src/mpolynomial.md`. I am however not sure what you mean by

> the docstrings for jacobi and derivative should be used (with examples) in the docs/src/mpolynomial.md file.

**Comment by fieker** [comment]
jacobi is better than jacob.

But

jacobi is too general, if you're not doing commutative algebra, and not
thinking singular, then you would expect different things
I don't mind not calling it jacobi_matrix, but maybe it should define
an ideal? 
What is the mathematical specification here?

To me, many of the singular names are horrible sine they do not permit
extension of the system to different areas of mathematics. They are
purely meaningful to commutative algebra. This is too narrow...

**Comment by fredrik-johansson** [comment]
I agree, ``jacobi`` to me could mean Jacobi symbol, Jacobi polynomial, Jacobi elliptic function, Jacobi sum...

https://en.wikipedia.org/wiki/List_of_things_named_after_Carl_Gustav_Jacob_Jacobi

**Comment by heiderich** [comment]
I agree that the name is too generic. Following the idea of @fieker that the output should be an ideal, maybe we could call it `jacobian_ideal`. This would make sense for single polynomials as input as well as for ideals (or arrays of polynomials). This also has the advantage that the order of the variables of the parent ring does not matter (currently I do not make any claim about the order of the elements returned). What do you think? What is the data structure for ideals in AbstractAlgebra?

**Comment by heiderich** [comment]
@wbhart: I guess you mean

`jacobi{T <: AbstractAlgebra.RingElem}(f::MPoly{T})::Array{MPoly{T},1}`

instead of 

`jacobi{T <: AbstractAlgebra.RingElem}(f::MPoly{T})::Array{MPoly{T},1)`

Right?

**Comment by wbhart** [comment]
Hopefully my additional comments above answer your questions. If not, take a look at how some of the other interfaces are documented for some clues on how to do it. And if still unsure, ask away.

**Comment by fieker** [comment]
On Tue, Jun 19, 2018 at 05:52:21AM -0700, Florian Heiderich wrote:
> I agree that the name is too generic. Following the idea of @fieker that the output should be an ideal, maybe we could call it `jacobian_ideal`. This would make sense for single polynomials as input as well as for ideals (or arrays of polynomials). This also has the advantage that the order of the variables of the parent ring does not matter (currently I do not make any claim about the order of the elements returned). What do you think? What is the data structure for ideals in AbstractAlgebra?

Better idea - but here we it the limit if AbstractAlgebra: this is
probably a better goal for oscar/ singular. In order to do anything
useful with ideals we'd need Groebner-bases. I don't think we want to
(re)implement them in AbstractAlgebra...

What is the goal of this?

**Comment by heiderich** [comment]
Finally I would be interested in Groebner basis computations. I am not sure how this is supposed to be done finally in OSCAR. Maybe there would be conversion functions to Singular polynomials (and back?) at one point?

I could also remove the jacobi function from this pull request.

**Comment by wbhart** [comment]
Sorry, I hadn't realise you were putting the return value on the function, so the prototype I was suggesting is wrong. There's not really any need to do that, especially with an array, since Julia will not convert it for you. And anyway, if the idea is to return an ideal, it certainly shouldn't return a Julia array, which is not an ideal.

I agree that maybe the jacobi function isn't really suited to AbstractAlgebra.jl. It seems to fit better with Singular.jl for now. Perhaps omit it from this PR.

**Comment by wbhart** [comment]
You are right that eventually there will be a conversion to and from Singular polynomials, defined in Singular.jl. Of course, the representation in AbstractAlgebra.jl is designed to make this conversion as cheap as possible.

Oscar.jl will represent polynomials as AbstractAlgebra polynomials by default. If you make an ideal out of them and ask for a Groebner basis, obviously the polynomials will have to be converted to and from Singular polynomials. This will happen at the top level in Oscar.jl, of course. Oscar.jl will include both AbstractAlgebra.jl and Singular.jl, so it will be able to call functions in both.

**Comment by heiderich** [comment]
> I've probably told you the wrong file to put the docstrings and examples in. They should probably go in mpolynomial_rings.md. However, I guess this would be optional functionality rather than required functionality, so we probably need to add a new section for that, immediately under the optional functionality section.

So you propose to add documentation of an optional `derivative` function of the interface rather than documentation of the concrete implementation for MPoly in this pull request?

> Obviously, in the long run, we'll want the docs in the file I said, but only when the functions work for all multivariate types. MPoly is a little unusual in that regard. It is an interface that is still being developed, and so there are no generic implementations available for all multivariate types, at present.

I am confused. I though MPolyElem is the interface and MPoly an implementation. 

What do you propose to do concerning the documentation of the function `derivative` in MPoly in this pull request and/or the implementation or such a function in the generic interface (MPolyElem)?

**Comment by wbhart** [comment]
Thank you!

**Pull request merged**
