### PR TITLE
add FactoredFractionField

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Can we also just use the ring conformance tests?

Do you plan adding documentation?

**Comment by tthsqe12** [comment]
This is a fun one: the addition of `FracElem`s is defined on the abstract type in `src/Fraction.jl`, which means something like the following can't get to the promotion rules.
```julia
    Zx, x = PolynomialRing(ZZ, "x")
    F = FactoredFractionField(Zx)
    F(1//x) + 1//x
```

**Comment by thofma** [comment]
Do you want to allow this? It is not clear to me what should happen. Do we consider `FactoredFractionField` to be "derived" from `FractionField`?

**Comment by tthsqe12** [comment]
I guess it will have to be disallowed, but do you agree with
```julia
FactoredFracField{T <: RingElement} <: AbstractAlgebra.FracField{T}
FactoredFrac{T <: RingElement} <: AbstractAlgebra.FracElem{T}
```
?

**Comment by thofma** [comment]
Can you elaborate?

**Comment by tthsqe12** [comment]
Since I am not going to write methods `+(::Frac{T}, FactoredFrac{T}), ...`, the only way I am willing to support `Frac{T} + FactoredFrac{T}, ...` is via the promotion system. However, since `Frac{T}` and `FactoredFrac{T}` both belong to the abstract `FracElem{T}` and `FracElem{T} + FracElem{T}` is defined, `Frac{T} + FactoredFrac{T}` never gets to the promotion system and just throws due to incompatible parents.

**Comment by thofma** [comment]
OK, I see. I agree that the binary operations in `src/Fraction.jl` should have signature
```
function +(a::S, b::S) where {S <: FracElem}
``` 
(I think they should not be there at all as fallback versions, but I would ignore this for a moment).

If we change it like this, we will get a nice promotion error that we want, right?

**Comment by tthsqe12** [comment]
Yes, but let's do that in another pr. This one is good to go for now.

**Comment by thofma** [comment]
Nice. The name `push_term!` sounds a bit additively in my ears, which makes this a bit look odd, but probably just my personal opinion.

**Pull request merged**
