### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by thofma**
We need some patch release containing the fixes for the series code.

### CODE REVIEW

**Comment by wbhart** [comment]
Good idea. Are we sure the addeq! and so on are ok now?

**Comment by fieker** [comment]
On Wed, Feb 24, 2021 at 09:25:25AM -0800, wbhart wrote:
> Good idea. Are we sure the addeq! and so on are ok now?
Hard to say. Actually I'd have a different fix for the same problem to
suggest, fixing it differently.

But: 
 - the change should reduce the number of errors 
 - it should not introduce new ones
 - there might (will) be others...

**Comment by thofma** [comment]
I am running tests downstream and then will merge.

**Comment by wbhart** [comment]
If you want to make serious use of the function, I recommend testing every possible overlap of the valuation, poly and precision parts of the series with the parts of the other, including zero length for each. The code has never been seriously tested.

**Pull request merged**
