### PR TITLE
add length() and isempty() for matrices

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by wbhart** [comment]
This should work for Nemo and Singular matrices too if you define it for AbstractAlgebra.MatElem instead of Generic.MatElem. Perhaps you could do that before I merge it. Then you could put some documentation in the matrix.md file which should imply that it is generic functionality provided for all our matrices that satisfy our general interface.

**Comment by rfourquet** [comment]
> if you define it for AbstractAlgebra.MatElem instead of Generic.MatElem.

I defined it for `MatrixElem{T} == Union{AbstractAlgebra.MatElem{T}, AbstractAlgebra.MatAlgElem{T}}`, so it indeed works for `Nemo`.

I now updated the documentation in matrix.md.

**Comment by wbhart** [comment]
Ah yes, I forgot that this Generic union is actually a union of AbstractAlgebra Abstract types. Thanks.

**Comment by rfourquet** [comment]
> AbstractAlgebra.MatElem instead of Generic.MatElem

By the way, `AbstractAlgebra.MatElem === Generic.MatElem`... I'm still confused by sometimes having the same name refer to different objects defined in different modules, like `AbstractAlgebra.MatSpace !== Generic.MatSpace`, I will probably end up drawing a graph of the types to help with understanding the hierarchy.

**Comment by wbhart** [comment]
I don't see why that would be. One is supposed to be an abstract type and the other is supposed to be a union.

**Pull request merged**
