### PR TITLE
enable direct creation of literal column vectors

### PR DESCRIPTION
**Pull request by rfourquet**
And simplify the implementation of typed_hcat and typed_hvcat.

### CODE REVIEW

**Comment by rfourquet** [comment]
Should I add an example showing that to create a 1x1 matrix, the syntax is `ZZ[1;]` ? or is it rare enough / well-known enough?

**Comment by fieker** [comment]
On Tue, Oct 29, 2019 at 01:59:30AM -0700, Rafael Fourquet wrote:
> Should I add an example showing that to create a 1x1 matrix, the syntax is `ZZ[1;]` ? or is it rare enough / well-known enough?
> 
I never encountered this and don't understand it. What is this doing?

**Comment by rfourquet** [comment]
We can create literal matrices with square brackets, within which lines are space-separated entries, and lines themselves are separated by `;`. The special cases of column or row matrices is easy enough to guess, but maybe not so for 1x1 matrices:
```julia
julia> ZZ[1 2; 3 4] # equivalent to ZZ[1 2; 3 4;]
[1  2]
[3  4]

julia> ZZ[1 2] # row matrix
[1  2]

julia> ZZ[1; 3] # column matrix, equivalent to ZZ[1; 3;]
[1]
[3]

julia> ZZ[1] # trying to create a 1x1 matrix
ERROR: MethodError: no method matching getindex(::AbstractAlgebra.Integers{BigInt}, ::Int64)
Closest candidates are:
[...]

julia> ZZ[1;] # create 1 column matrix with only one line, i.e. 1x1
[1]

```

**Comment by fieker** [comment]
On Tue, Oct 29, 2019 at 05:54:50AM -0700, Rafael Fourquet wrote:
> We can create literal matrices with square brackets, within which lines are space-separated entries, and lines themselves are separated by `;`. The special cases of column or row matrices is easy enough to guess, but maybe not so for 1x1 matrices:
I did not know that you can use ZZ as "prefix". Otherwise, I've been
using that

**Comment by wbhart** [comment]
I think we at some point enabled it for ZZ and QQ after some users complained, but only for types that *can* be created from type alone.

We deliberately held off implementing this in general because of the confusion it is likely to result in compared with creating Julia matrices rather than Nemo ones. The current situation is a compromise to stop getting so many complaints.

**Comment by fieker** [comment]
On Tue, Oct 29, 2019 at 07:05:01AM -0700, wbhart wrote:
> I think we at some point enabled it for ZZ and QQ after some users complained, but only for types that *can* be created from type alone.
> 
> We deliberately held off implementing this in general because of the confusion it is likely to result in compared with creating Julia matrices rather than Nemo ones. The current situation is a compromise to stop getting so many complaints.
> 
it works ...
julia> FlintZZ[1 2; 3 4]
[1  2]
[3  4]

julia> typeof(ans)
fmpz_mat

julia> k[1 1; 3 4]
[1  1]
[3  4]

julia> typeof(ans)
AbstractAlgebra.Generic.MatSpaceElem{nf_elem}


don't ask why

**Comment by wbhart** [comment]
Surprising. I'm sure it didn't work reliably two weeks ago.

**Pull request merged**
