### PR TITLE
sub and getindex on matrices: harmonize the arguments they accept

### PR DESCRIPTION
**Pull request by rfourquet**
First, this relaxes `UnitRange` to `AbstractVector`, at no cost, as `sub(a, ::Vector{Int}, ::Vector{Int})` was already implemented. Then, we allow `Int` and `:` arguments in `sub`, so that `sub` and `getindex` accept exactly the same arguments (when there are two of them).

Personally, I would also remove `sub(a, r1::Int, c1::Int, r2::Int, c2::Int)`, it's too easy to get confused with the order of the arguments, and it's so easy to write instead `sub(a, r1:r2, c1:c2)`. 
I would actually remove `sub` completely, as it's redundant with `getindex`. This function was once part of Julia, and was creating views if I remember correctly, but was removed in version 0.5 I think.

DO NOT MERGE: This depends on #524.

### CODE REVIEW

**Comment by wbhart** [comment]
We definitely need to discuss removing sub. I think that is a good idea. The original idea for us was that a view would create a window into part of an existing matrix, so that if you modify the view, you would modify the original matrix.

sub was used to make a copy of part of an existing matrix. The problem is, there is no need to make a copy of the entries in a matrix in order to do this, and yet we currently do that. Once we fixed that, the result would be that the implementation of sub and view would be identical, in which case we should probably get rid of one of them.

Of course, as usual, Flint is slightly different. We have views (called windows in Flint), but they can't be handled quite the same way as in Julia. For example, in Flint objects are always copied when read from a matrix entry. But I still think there is not much point to keeping sub. But we do need to discuss this, as for example, Hecke may be relying on this.

**Comment by wbhart** [comment]
Yes, I probably confused the issue a little here. I'm not talking about getting rid of the functionality of sub, just the actual function, which is redundant. I think that is a good idea.

The implementation is indeed a separate issue. Currently sub (the function) copies, and doesn't need to. We can fix that too, though it will no longer be a function called sub, but some version of getindex.

**Comment by rfourquet** [comment]
> Currently sub (the function) copies, and doesn't need to. We can fix that too, though it will no longer be a function called sub, but some version of getindex.

@fieker suggested "sub and view are different and need to be different."
Currently, `getindex` and `sub` do (more or less) the same thing, i.e. do a copy, views don't. My proposal was to get rid of `sub` (with which @fieker agrees), and to be left with `getindex` and `views`. I interpret you comment as saying that `getindex` could be made to do what `view` does? then there is no function doing a `copy`... Sorry to always cite "what Julia does", but `getindex` on `Matrix` does a copy, and uses `view` for views, I think we should follow suit.

**Comment by thofma** [comment]
Since `sub` and `getindex` do exactly the same, let's remove `sub`. Problem solved.

**Comment by rfourquet** [comment]
I added a commit which removes `sub`.

**Comment by wbhart** [comment]
You misunderstood. It's the fact that a deepcopy of the *entries* is made that I am complaining about. This should not be needed. getindex should make a new matrix, but it should just put the old entries in it, not deepcopies. The view function does not make copies, but it also doesn't make a new marix, but a windiw nto the old one.

**Comment by rfourquet** [comment]
Ok to merge this?

**Comment by wbhart** [comment]
Could you please check that

```
Base.getindex(M::AbstractAlgebra.MatElem, rows, cols)
```

works with Flint matrices, and returns a Flint matrix. Just looking at it, I think it does, but I just want to check before merging this.

**Comment by rfourquet** [comment]
Yes it works. When this is realeased, I will have to reflect the change in `Nemo` which uses `sub`.

**Pull request merged**
