### PR TITLE
Remove adjoint method calling transpose

### PR DESCRIPTION
**Pull request by fingolfin**
In Julia, adjoint is defined to be conjugate transposition. There are rings
(e.g. finite fields of even degree over their base fields) that admit a
canonical involution and where the notion of conjugate transposition is
used as well, and standard in the literature.

As such, I think it is misleading and potentially dangerous to simply map
`adjoint` to `transpose`.

One drawback of removing it is that the notation `a'` won't work anymore for
transposing a matrix.

See also <s>https://github.com/thofma/Hecke.jl/pull/234<s>  and the discussion there, resp. https://github.com/Nemocas/Nemo.jl/pull/1162 and https://github.com/thofma/Hecke.jl/pull/383

This is probably a breaking change, so shouldn't be merged lightly.

### CODE REVIEW

**Comment by fingolfin** [comment]
@wbhart @thofma so, can this be merged (I just rebased it to fix a conflict)? Or if not, what's the hold up? I'll be happy to work on it, if I knew what it is? E.g. are there any downstream package like Hecke that we'd expect to be broken by this?

**Comment by fingolfin** [comment]
Actually should probably first fix Hecke and any other of our packages to replace `x'` by `transpose(x)`. Working on it now

**Comment by wbhart** [comment]
Also the tests fail. Is there an associated fix to AbstractAlgebra or something that I should be looking at?

**Comment by fingolfin** [comment]
Yeah, they failed because after I made this PR, some uses of the `x'` syntax were introduced. I hope I got them all now, but as I can't run the tests locally ...

**Comment by wbhart** [comment]
In this particular case, could you perhaps call the branches in the other repos with the same name as this one so we can see the CI pass across all the packages. What I also find useful is to put a link to this PR in the description of all the others. This just helps alert whoever merges them to consider the PR's together. That approach seems to be working ok for @thofma and me so far and seems to be relatively little effort.

(You are probably already aware of all this already. But it can't hurt to mention it once.)

**Comment by fingolfin** [comment]
Absolutely -- these two PRs simply predate that bit of tooling. Unfortunately, I think I'll have to close and replace one of the two PRs for that. I'll go with the one on Hecke, as I have to update it anyway.

**Comment by fingolfin** [comment]
I've now opened matching PRs in Nemo and Hecke: https://github.com/Nemocas/Nemo.jl/pull/1162 and https://github.com/thofma/Hecke.jl/pull/383

Assuming everything works, we may want to first apply all those changes replacing `x'` by `transpose(x)`, and perform the actual removal of the `adjoint` methods later...

**Comment by wbhart** [comment]
I'm not too bothered either way, but as you see fit.

**Comment by thofma** [comment]
Somehow the downstream tests are failing.

**Comment by thofma** [comment]
I am just gonna mark this breaking and merge soon together with the other breaking PR.

**Pull request merged**
