### PR TITLE
Enable matrix algebras over noncommutative rings

### LINKED ISSUE #1035: enable `MatAlgebra{<:NCRingElem}`?
I don't think a new type for matrices over non-comutative ring is in order.
pros:
- we can have matrices of matrices
- we can have matrices of ncpoly's
- ...

cons:
- figuring out which parts of the current matrix code can be shared with non-comutative rings is a bit of work.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #1035

### CODE REVIEW

**Comment by thofma** [comment]
Love it!

**Comment by wbhart** [comment]
It looks like this is introducing ambiguities for map_entries involving GAP objects. I wonder if @fingolfin could comment on this when he has a chance. 

https://github.com/Nemocas/AbstractAlgebra.jl/runs/5205706833?check_suite_focus=true

Presumably the relevant method in AbstractAlgebra is:

```
map_entries(f, a::MatrixElem{T}) where T <: RingElement
```

which was formerly not restricted to T <: RingElement. As this has introduced an ambiguity rather than a method error, I may need some guidance on whether this is something that can easily be worked around in GAP.jl (presumably) or whether we need to come up with something new here.

**Comment by thofma** [comment]
I think `GAP.jl` would need to do `MatrixElem`. I think `MatElem` more specific.

**Comment by wbhart** [comment]
Thanks @thofma

If that seems feasible then I'll assume that for now.

**Comment by wbhart** [comment]
Do we also want MatrixSpace over noncommutative ring or just MatrixAlgebra?

I don't foresee any complication with having both, but maybe you guys see something?

**Comment by thofma** [comment]
At the moment my only application is `MatrixAlgebra`, but if it is not too much work for MatrixSpaces, I would of course want them too!

**Comment by wbhart** [comment]
It's just test code, as the tests are separated. It's easier to actually have matrix spaces as well from a code point of view.

I will do both.

**Comment by fingolfin** [comment]
Just to clarify: GAP.jl knows nothing about AA, MatrixElem etc., and it should stay that way. Any necessary changes will have to be done in Oscar.

**Comment by wbhart** [comment]
Even worse, this carries over to our types:

```
julia> nrows([R([1 2; 3 4]) R([2 3; 3 4]); R([3 4; 5 6]) R([4 5; 6 7])])
4
```

**Comment by thofma** [comment]
I don't expect too much from julia matrices, so this is fine.

The other issue you mention is a consequence of us allowing the syntax
```
[A B;
 C D]
```
to construct block matrices. I don't know what the best way would be to fix it. I think we should keep the block matrix syntax for convenience. For the tests you could just do `matrix(S, 2, 2, [A, B, C, D])`.

**Comment by wbhart** [comment]
Yes, I can do that. It works at least.

**Comment by thofma** [comment]
The Oscar problem is fixed.

Somehow the documentation needs to be adjusted.

**Comment by wbhart** [comment]
Great! What changes do you want to the docs?

**Comment by thofma** [comment]
If think it would be enough if they would build :)

**Comment by wbhart** [comment]
Oh I see. This PR has a long way to go. Docs will be fixed in the end. I haven't touched them yet.

**Comment by wbhart** [comment]
Also, I don't see how to test this function:

```
block_diagonal_matrix(R::NCRing, V::Vector{<:Matrix{T}}) where T <: NCRingElement
```

It requires a Julia Vector or Julia matrices over a noncommutative ring to test, and as we know, Julia flattens these.

**Comment by thofma** [comment]
Yes, there are multiple definitions of determinant, so there should be not `det` function in the general case.

**Comment by thofma** [comment]
> Also, I don't see how to test this function:
> 
> ```
> block_diagonal_matrix(R::NCRing, V::Vector{<:Matrix{T}}) where T <: NCRingElement
> ```
> 
> It requires a Julia Vector or Julia matrices over a noncommutative ring to test, and as we know, Julia flattens these.

No, I don't think julia flattens them:

```
julia> a = ZZ[1 2; 3 4]
[1   2]
[3   4]

julia> [a, a, a]
3-element Vector{fmpz_mat}:
 [1 2; 3 4]
 [1 2; 3 4]
 [1 2; 3 4]
```

**Comment by wbhart** [comment]
I was hoping to test it when T is a noncommutative type, i.e. type of a matrix algebra element.

**Comment by wbhart** [comment]
```
julia>    R = MatrixAlgebra(ZZ, 2)
Matrix Algebra of degree 2 over Integers

julia>    S = MatrixAlgebra(R, 2)
Matrix Algebra of degree 2 over Matrix Algebra of degree 2 over Integers

julia>    A = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia>    B = [2 3; 4 5]
2×2 Matrix{Int64}:
 2  3
 4  5

julia>    C = [3 4; 5 6]
2×2 Matrix{Int64}:
 3  4
 5  6

julia>    D = [4 5; 6 7]
2×2 Matrix{Int64}:
 4  5
 6  7

julia>    RA = R(A)
[1   2]
[3   4]

julia>    RB = R(B)
[2   3]
[4   5]

julia>    RC = R(C)
[3   4]
[5   6]

julia>    RD = R(D)
[4   5]
[6   7]

julia> Generic.block_diagonal_matrix(S, [[RA RB; RC RD], [RB RC; RA RB]])
ERROR: MethodError: no method matching block_diagonal_matrix(::AbstractAlgebra.Generic.MatAlgebra{AbstractAlgebra.Generic.MatAlgElem{BigInt}}, ::Vector{AbstractAlgebra.Generic.MatAlgElem{BigInt}})
Closest candidates are:
  block_diagonal_matrix(::AbstractAlgebra.NCRing, ::Vector{var"#s159"} where var"#s159"<:Matrix{T}) where T<:Union{NCRingElem, RingElement} at /home/wbhart/.julia/dev/AbstractAlgebra/src/Matrix.jl:309
Stacktrace:
 [1] top-level scope
   @ REPL[64]:1
```

**Comment by thofma** [comment]
Ah, my mistake. I misread the signature. Don't think there is an easier way than doing `M = Matrix(R, undef, 2, 2); M[1, :] = [RA, RB]; M[2, :] = [RC, RD]` to produce some `Matrix` with these matrices as input.

**Comment by wbhart** [comment]
@thofma I've added all the basic methods and test for them. We are up to the more complicated algorithms now.

However, I don't know how we are going to fix the promotion system. Consider multiplying a `ResF{BigInt}` by a `MatAlgElem{AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.ResF{BigInt}}}`. We currently have a test which does this, but it fails with an ambiguity error.

Now that I've added promotion rules for promoting MatAlgElems as noncommutative ring elements it doesn't know which way to do the promotion. It sees an NCRingElement on the left and a MatAlgElem on the right. Which is it promoting to which?

I don't think this is an easy problem to solve.

**Comment by wbhart** [comment]
Actually, I managed to fix that and another promotion issue just by adding more promotion rules. But here is one I don't know how to deal with:

```
promote(::AbstractAlgebra.Generic.MatAlgElem{BigInt}, ::AbstractAlgebra.Generic.NCPoly{AbstractAlgebra.Generic.NCPoly{AbstractAlgebra.Generic.MatAlgElem{BigInt}}})
```

**Comment by thofma** [comment]
I am happy to have a look at the promotions if you think this might help. If possible I would like to get this in before turning to the (mathematically) more challenging examples.

**Comment by wbhart** [comment]
I managed to get all the tests to pass. Here is what I did.

The following were defined for MatrixElem (the union of matrix space elements and matrix algebra elements). I downgraded it to just apply to MatElem since this PR upgrades the promote functions in Rings.jl to handle NCRingElements not just RingElements.

```
function Base.promote(x::MatElem{S}, y::T) where {S <: NCRingElement, T <: NCRingElement}
   U = promote_rule_sym(S, T)
   if U === S
      return x, base_ring(x)(y)
   else
      error("Cannot promote to common type")
   end
end

function Base.promote(x::S, y::MatElem{T}) where {S <: NCRingElement, T <: NCRingElement}
   u, v = Base.promote(y, x)
   return v, u
end
```

I think this is the right way to do things. The only promote functions should be the ones in Rings.jl and promote functions for objects that are not rings, like MatElem. Everything else should be handled by promote_rules in my opinion.

But I also currently have a number of functions like:

```
==(x::NCPolyElem{T}, y::T) where T <: MatAlgElem

==(x::T, y::NCPolyElem{T}) where T <: MatAlgElem
```

This is to work around the fact that `==` in Rings.jl does not handle NCRingElements. Same for divexact/left/right, *, +, - etc.

I think I should upgrade all these in Rings.jl to handle NCRingElements and remove the functions like the above, since we don't want to have to add functions like that for every pair of noncommutative rings we have in the system. What do you think @thofma?

**Comment by wbhart** [comment]
I agree we should get this in before turning to the more complicated algorithms. I propose to make a list and you can tell me which ones you want me to implement (i.e. ones you really need now and don't want to implement yourself).

**Comment by thofma** [comment]
> I managed to get all the tests to pass. Here is what I did.
> 
> The following were defined for MatrixElem (the union of matrix space elements and matrix algebra elements). I downgraded it to just apply to MatElem since this PR upgrades the promote functions in Rings.jl to handle NCRingElements not just RingElements.
> 
> ```
> function Base.promote(x::MatElem{S}, y::T) where {S <: NCRingElement, T <: NCRingElement}
>    U = promote_rule_sym(S, T)
>    if U === S
>       return x, base_ring(x)(y)
>    else
>       error("Cannot promote to common type")
>    end
> end
> 
> function Base.promote(x::S, y::MatElem{T}) where {S <: NCRingElement, T <: NCRingElement}
>    u, v = Base.promote(y, x)
>    return v, u
> end
> ```
> 
> I think this is the right way to do things. The only promote functions should be the ones in Rings.jl and promote functions for objects that are not rings, like MatElem. Everything else should be handled by promote_rules in my opinion (unless there's a faster way to do an ad hoc operation that we want to implement specially, rather than rely on the generic framework).
> 
> But I also currently have a number of functions like:
> 
> ```
> ==(x::NCPolyElem{T}, y::T) where T <: MatAlgElem
> 
> ==(x::T, y::NCPolyElem{T}) where T <: MatAlgElem
> ```
> 
> This is to work around the fact that `==` in Rings.jl does not handle NCRingElements. Same for ad hoc divexact/left/right, *, +, - etc.
> 
> I think I should upgrade all these in Rings.jl to handle NCRingElements and remove the functions like the above, since we don't want to have to add functions like that for every pair of noncommutative rings we have in the system. What do you think @thofma ?

I agree with your assessment. In `Rings.jl` we should allow `NCRingsElements` and the `MatrixElem` methods you mentioned should be restricted to `MatElem`.

**Comment by wbhart** [comment]
I think I have it working now. We just need to see if the docs build and whether it breaks anything elsewhere in Nemo/Oscar, etc.

**Comment by wbhart** [comment]
It looks like once again Oscar will need to change the signature of a function. It looks like `map_entries` should take `MatrixElem{T} where T <: RingElem` to be at least as specific as AbstractAlgebra.

Or I suppose we could split the AbstractAlgebra function into one for `MatElem{T} where T <: NCRingElem` and one for `MatAlgElem{T} where T <: NCRingElem`, though a change in Oscar is still going to be needed to be at least as specific as AbstractAlgebra. 

What do you think @thofma ?

By the way, doc issues are resolved, so in theory this is the last blocker.

**Comment by wbhart** [comment]
I've removed the WIP and rebased this. If it is still desirable to have this branch, it would need the ambiguity issue to be resolved. Otherwise it's ready from my point of view.

**Comment by tthsqe12** [comment]
Some strange method errir in the oscar ci. Will investigate

**Comment by thofma** [comment]
Fix should be similar to https://github.com/oscar-system/Oscar.jl/pull/1102

**Comment by tthsqe12** [comment]
My 2 cents: I think the transpose function should transpose the entries as well. no?
```
function transpose(x::Mat{T}) where T <: NCRingElement
   y = MatSpaceElem{eltype(x)}(permutedims(x.entries))
   y.base_ring = x.base_ring
   y
end
```

**Comment by thofma** [comment]
Can you elaborate why the transpose should be 'recursive'? It would be a bit awkward if there were no way to just transpose the matrix generically.

**Comment by tthsqe12** [comment]
I don't think (A*B)^T = B^T*A^T works without recursion

**Comment by thofma** [comment]
Yes, transposition on `M_n(S)` will not be an anti-morphism unless one applies an anti-morphism `S -> S`. But this anti-morphism need not exist for `S` and even in the case that `S` is a matrix ring, why do we single out transposition? This makes it impossible to write generic code since `transpose` is now some awkward function doing funny/useless things depending on the base ring.

**Comment by tthsqe12** [comment]
De we want this identity? this is also interesting: https://github.com/oscar-system/Singular.jl/issues/233

**Comment by thofma** [comment]
If you want that identity, just supply the anti-morphism/involution and use a different method. But guessing an involution should not be part of the `transpose(M)` method.

**Comment by tthsqe12** [comment]
ok, then I am fine.

**Pull request merged**
