### PR TITLE
Make powering of matrices by negative powers work.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
I will add a simple test tonight.

**Comment by thofma** [comment]
Merge?

**Comment by wbhart** [comment]
Sorry, let me add a simple test first.

**Comment by rfourquet** [comment]
The one failure on travis seems unrelated:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Pull request merged**
