### PR TITLE
add an AbstractRNG argument to rand methods

### PR DESCRIPTION
**Pull request by rfourquet**
This just adds an RNG argument in a most mechanical way, I will look into making the `rand` methods conform (when possible) to the `Random` API in a subsequent PR.

### CODE REVIEW

**Comment by wbhart** [comment]
@rfourquet Could you check that this doesn't break Hecke before I merge this?

**Comment by rfourquet** [comment]
So it breaks `Nemo` and `Hecke`. How do we handle that? Merge this, release a new version of AA, and then update Nemo and Hecke accordingly? 
I will make a PR against Nemo (and Hecke) to have its `rand` methods accept an option RNG, and see if it works with the current AA release, in which case another option is to update first Nemo and Hecke and then AA.

**Comment by rfourquet** [comment]
> and see if it works with the current AA release

So no it doesn't work, AA needs to be changed first. @thofma Is it too late to include that in AA's 0.6 release?

**Comment by thofma** [comment]
Kind of too late. We can just make a 0.7 right after that. So is the plan to first adjust the other two packages or first to merge this here? I have no preference.

**Comment by rfourquet** [comment]
For Nemo tests to pass with the `rng` argument added, it requires that AA `rand` methods also have the `rng` argument, so this present PR must be merged first if we want to only merge PR whose tests pass.

**Comment by thofma** [comment]
OK, if there are no objection I will merge this soonish.

**Comment by rfourquet** [comment]
Please don't squash when merging, one commit is from @kalmarek

**Comment by kalmarek** [comment]
you can squash if you feel like it ;-)

**Pull request merged**
