### PR TITLE
Force variables to be different in `@varnames_interface`

### PR DESCRIPTION
**Pull request by lgoettgens**
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1761.

Do we consider this a breaking change to AA?

cc @mgkurtz

### CODE REVIEW

**Comment by fingolfin** [comment]
Of course it may break some existing code. But OscarCI is green. So personally I'd be fine declaring the use of multiple variables with identical names a "bug" and so this a fix.

We can talk about it during triage...

**Review by fingolfin — APPROVED** [review]

**Comment by lgoettgens** [comment]
@fingolfin and @wdecker will look at some intersection theory examples

**Comment by fingolfin** [comment]
Yeah we talked about it and I got convinced that we can't do this right now, at least not in this way: e.g. when forming products of varieties, we need to form a "product" of the underlying polynomial rings, which basically means creating a new polynomial ring which has as variables the union of the variables of the initial two rings. 

For various reasons it is useful to keep the names of the input rings. The user may not care, but when they do, this can be super helpful. But obviously it easily leads to a situation with duplicate variable names. Multiple ways to deal with this:
1. just don't, i.e. leave things as they are (I propose that's what we do for the time being)
2. one could provide a function which tries to "fix up" a list of varnames, e.g.: if a variable name occurs a second time, say, `:x`, replace the second instances by, say `:(x')` or :x1`. But of course that could lead to a new collision, so this needs to keep trying new names until it finds one without a collision. But I fear this may make things more confusing for users, not less
3. we could modify this PR to introduce kwarg which control this, say `allow_duplicate_varnames::Bool=false` (or `forbid_duplicates=true` or whatever). Then code which constructs such products can use `allow_duplicate_varnames=true`. However all calling code needs to be adjust, so if we were to go this way, then we should first roll it out with the duplicates check *off* by default; then code in Hecke, Oscar etc. could be adjusted to pass that kwarg; and once that is complete, we could switch the default.


But options 2 and 3 involve quite a bit of work, and I am not sure it's really worth it?

**Review by fingolfin — CHANGES_REQUESTED** [review]
See discussion on issue #1761

**Pull request closed without merging**
