### PR TITLE
Fraction field optimisation

### PR DESCRIPTION
**Pull request by wbhart**
Speeds up addition, subtraction and multiplication of generic fractions (a lot).

### CODE REVIEW

**Comment by thofma** [comment]
There are still some debugging print statements.

**Comment by kalmarek** [comment]
and with those I think it's always good to leave some traces of benchmarking You did ;-)

Could You post example code here in the issue?

**Comment by wbhart** [comment]
Here is the example which is much, much, much faster now. (Provided by Thomas Breuer.) The time further reduces to a fraction of a second with some special cases in the gcd code in Nemo, but we'll take care of this in Flint.

```
julia> f = Nemo.QQ
Rational Field

julia> RR, gens = PolynomialRing( f, ["a","b","c","d"])
(Multivariate Polynomial Ring in a, b, c, d over Rational Field, fmpq_mpoly[a, b, c, d])

julia> a = gens[1]
a

julia> b = gens[2]
b

julia> c = gens[3]
c

julia> d = gens[4]
d

julia> ff = FractionField( RR )
Fraction field of Multivariate Polynomial Ring in a, b, c, d over Rational Field

julia> a = ff(a);

julia> b = ff(b);

julia> c = ff(c);

julia> d = ff(d);

julia> 1+a^-24*b^-24*c^-24*d^-24-a^-24*b^-24*c^-24*d^-18-a^-24*b^-24*c^-18*d^-24+
       a^-24*b^-24*c^-18*d^-18-a^-24*b^-18*c^-24*d^-24+2*a^-24*b^-18*c^-24*d^-18-
       a^-24*b^-18*c^-24*d^-12+2*a^-24*b^-18*c^-18*d^-24-3*a^-24*b^-18*c^-18*d^-18+
       a^-24*b^-18*c^-18*d^-12-a^-24*b^-18*c^-12*d^-24+a^-24*b^-18*c^-12*d^-18-
       a^-24*b^-12*c^-24*d^-18+a^-24*b^-12*c^-24*d^-12-a^-24*b^-12*c^-18*d^-24+
       3*a^-24*b^-12*c^-18*d^-18-2*a^-24*b^-12*c^-18*d^-12+a^-24*b^-12*c^-12*d^-24-
       2*a^-24*b^-12*c^-12*d^-18+a^-24*b^-12*c^-12*d^-12-a^-24*b^-6*c^-18*d^-18
```

**Comment by wbhart** [comment]
I've removed the print statements. It's been a bit distracting trying to code at the meeting.

**Pull request merged**
