### PR TITLE
Remove eye and fix module bugs that did not contribute to its removal.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
I am unable to replicate the failure we are seeing. I don't doubt my code is broken somehow, but I don't know how to trigger the case. I've run exactly the test code that fails with 100,000 iterations and no failure results. I'm unable to see what could cause it to fail, so I don't think I can fix it at present. We have to wait until the same bug manifests some other way.

Obviously this PR has nothing to do with the failure.

**Comment by thofma** [comment]
Can we disable the test?

**Comment by wbhart** [comment]
Why? I can't get it to fail at all. I've run half a million iterations instead of 100 and no failure. I've also run the entire test suite through many times and no failures. I'm trying with Julia 1.1.1 right now, but so far, no failure.

I think it's an Appveyor problem. I suspect it's pulled an old commit or something. Otherwise I don't see how the failure is possible. It's the same bug I already fixed.

**Comment by wbhart** [comment]
After thousands of iterations, I can replicate it on Julia 1.1.1, but not on 1.0.2. I'll investigate.

**Comment by wbhart** [comment]
Ok, I have a failing test case. I'll make a ticket and investigate it. It only fails under Julia 1.1.1, not Julia 1.0.2.

**Comment by thofma** [comment]
If the tests are randomly failing, this renders the tests useless. If I change something, then not all tests will be running and if it fails I will not know why.

**Comment by wbhart** [comment]
I have found the problem. It's a mathematical one, which I currently don't know how to solve. I am thinking about a solution. It's not an easy fix.

I have absolutely no idea why the same code didn't fail on Julia 1.0.2. It's not a Julia issue at least.

**Comment by wbhart** [comment]
All fixed. It now passes 100,000 iterations on Julia-1.1.1.

**Comment by thofma** [comment]
Didn't we have an `ishnf` function somewhere?

**Comment by wbhart** [comment]
I couldn't find one in AbstractAlgebra. There is one for Z in Nemo of course.

**Pull request merged**
