### PR TITLE
Add a bunch of missing ngens method

### PR DESCRIPTION
**Pull request by fingolfin**
Also a few gens and gen methods

Those for `FracField` are moved here from Oscar.jl

### CODE REVIEW

**Comment by thofma** [comment]
Can we add tests for the other new methods? Also, is this breaking?

**Comment by lgoettgens** [comment]
> Can we add tests for the other new methods? Also, is this breaking?

I see no reason why one could consider this a breaking change.

**Comment by lgoettgens** [comment]
That is not breaking AA as we just add features. When removing them from OSCAR, one needs to update the AA compat bound there appropriately to an AA version with this PR. Then everything is non-breaking.

**Comment by lgoettgens** [comment]
I meant "not breaking for users of AA but not Oscar".

This type of warnings is not considered a break in the julia community

**Comment by thofma** [comment]
OK, I see. So far in view of the Oscar project we generally stretched the definition of "breaking" to include the following: Does not inconvenience users or developers of Oscar by indirectly causing warnings or errors.

**Comment by fingolfin** [comment]
I generally agree with @thofma! That said, the OscarCI tests seems to be passing just fine, so I don't think there is any breakage? But to double check, I went to my clone of Oscar, then dev'ed this AA branch for it, and got this:
```
julia> using Revise, Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
WARNING: Method definition ngens(AbstractAlgebra.Generic.LaurentMPolyWrapRing{T, PR} where PR<:AbstractAlgebra.MPolyRing{T} where T<:Union{AbstractAlgebra.RingElem, AbstractFloat, Integer, Base.Rational{T} where T<:Integer}) in module Generic at /Users/mhorn/Projekte/OSCAR/AbstractAlgebra.jl/src/generic/LaurentMPoly.jl:28 overwritten in module Oscar at /Users/mhorn/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly-affine-algebras.jl:234.
  ** incremental compilation may be fatally broken for this module **
```

But for some reason I don't see this warning in the OscarCI job logs?!

Anyway, note that it *does* work afterwards. But I don't know if it would break changes in Oscar CI.

**Comment by thofma** [comment]
The warning is in the log.

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/7150892295/job/19474655006?pr=1522#step:7:3682

**Comment by thofma** [comment]
Thanks @benlorenz. Looking forward to use 1.10 in the downstream tests.

**Comment by fingolfin** [comment]
Yeah, I figured I must just be doing something stupid that caused be to not see it in the logs. And yeah I look forward to 1.10 being used for the tests.


I guess that means we should mark this as breaking then.

**Pull request merged**
