### PR TITLE
Fix/perm on abstract vectors

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by wbhart** [comment]
Do you want me to merge this now, or leave it open to also fix the nightlies?

**Comment by kalmarek** [comment]
Good question: as a safety measure we can wait and I'll rebase onto master after tests on nightlies are fixed

**Comment by wbhart** [comment]
If you like, but I wouldn't hold my breath. The nightlies have apparently been unusable for months. The only reason I mention it here is that the perm tests are broken, according to the nightlies. I don't know if that is related to the issues we've been having with nightlies or not.

**Comment by kalmarek** [comment]
yes, @thofma pointed this out and it seems to be related to changes in `SparseArrays`. I will try to fix that particular problem within this pull, please don't merge

**Comment by wbhart** [comment]
@kalmarek Note that the doctests for perm also now fail.

**Comment by wbhart** [comment]
@kalmarek I fixed the doctest problem.

**Comment by kalmarek** [comment]
@wbhart thanks, I didn't even have the time to investigate yet

**Comment by kalmarek** [comment]
when all is green, we can merge this

**Pull request merged**
