### PR TITLE
Fix #438

### LINKED ISSUE #438: (New) Bug in HNF
```
julia> using AbstractAlgebra
julia> M = matrix(ZZ, BigInt[4 6 2; 0 0 10; 0 5 3])
[4  6   2]
[0  0  10]
[0  5   3]

julia> hnf(M)
[4  1  -1]
[0  5   3]
[0  0  10]
```

It's possible I misunderstand something, but this (the -1) doesn't look right to me.

```
julia> AbstractAlgebra.divrem(-1, 10)
(-1, 9)
```

### PR DESCRIPTION
**Pull request by joschmitt**
This should fix #438.
(Also: Somehow hnf_kb and hnf_kb_with_transform have been exported twice?)

### CODE REVIEW

**Comment by wbhart** [comment]
@joschmitt Wow, that's fantastic, thanks!

I think it is worth adding the failing test case to the test suite so that we don't have future regressions. Could you push an additional commit to add that?

**Comment by joschmitt** [comment]
Yes, of course.

**Comment by thofma** [comment]
Thanks a lot.

Was the HNF wrong in the example because of the normalization or was it total bogus? Just asking to check if the test would catch this.

**Comment by joschmitt** [comment]
The reduction of the columns wasn't done properly (depending on the order of the pivot elements).
For example
```
julia> M = matrix(ZZ, BigInt[4 16 2; 0 0 4; 0 5 5])
[4  16  2]
[0   0  4]
[0   5  5]

julia> hnf(M)
[4  1  -13]
[0  5    1]
[0  0    4]
```
(in the old version of course.)
So, no, it's not just the normalization.

**Comment by thofma** [comment]
Thanks!

**Pull request merged**
