### PR TITLE
Views

### PR DESCRIPTION
**Pull request by wbhart**
* Adds views for generic matrices
* Fix a printing issue in modules
* Remove some duplicate code in modules which I thought was due to the lack of views, but was in fact just due to my lack of care
* Fix some bugs in modules (ngens and Submodule)

Nemo still passes with these changes. There appears to still be a bug in intersection which rarely shows up in the test code. It is unrelated to this PR. I will fix it in a later PR. I mention it only in case it randomly occurs.

### CODE REVIEW

**Comment by wbhart** [comment]
It's ok, I tracked down and killed the bugs that were causing module intersection failures. It passes now after 10000 iterations for each of modules over QQ and ZZ.

**Comment by thofma** [comment]
You forgot to add:
- break everything by renaming the types :)

**Comment by thofma** [comment]
But this is awesome that we have views! I will merge as soon as everything is green.

**Comment by wbhart** [comment]
The changes are not difficult: 

* where you use Type{Mat{T}} where T <: RingElement now, it will almost certainly become Type{S} where {T <: RingElement, S <: Mat{T}}

* where you currently call the constructor Mat{T}(blah) it becomes MatSpaceElem{T}(blah)

* If you ever return the type Mat{T} or assign it to something (I mean the actual type, not a value of that type) then it will become MatSpaceElem{T}. But this case should be extremely rare.

That's basically it. All other occurrences of Mat{T} should remain unchanged.

**Comment by thofma** [comment]
I guess the most important is `MatSpaceElem{T}` instead of `Mat{T}` in the type definition. It would not error but it would make everything slower.

The other are mostly fine since one uses `matrix` to construct matrices most of the time.

**Pull request merged**
