### PR TITLE
enable R["x", "y"] syntax for MPolyRing construction

### PR DESCRIPTION
**Pull request by rfourquet**
I will add documentation if this change gets support.

### CODE REVIEW

**Comment by rfourquet** [comment]
Documentation added.

**Comment by wbhart** [comment]
This obviously causes an ambiguity for R["x"]. What do @fieker and @thofma think?

**Comment by rfourquet** [comment]
Yes, with this added syntax, there is not shorthand for univariate sparse polynomial. So indeed this favors simplicity over absolute consistency, with the premise that the case of wanting a univariate sparse polynomial is rarer.

**Comment by fieker** [comment]
wrong premises: univariates are MUCH MUCH more frequent....
Sorry

**Comment by wbhart** [comment]
Do I understand correctly that this only overloads that syntax for multivariates with at least two variables?

If so, then I think this patch is ok as it only adds new syntax and does not modify the existing syntax for univariates.

**Comment by thofma** [comment]
I would be in favor of this. Sparse univariate polynomials don't show up often enough (at least in my experience) to make this a dangerous ambiguity.

**Comment by rfourquet** [comment]
> Do I understand correctly that this only overloads that syntax for multivariates with at least two variables?

Yes, and it doesn't modify existing syntax.

How likely is it that we implement dense multivariate polynomials and that they are not significanly less generally useful than sparse ones? If so, this multivariate syntax might be reserved for these not-implemented-yet polynomials.

(in my field I used dense multivariate F2-polynomials more than sparse ones)

**Comment by wbhart** [comment]
There's an extremely low probability of that.

**Comment by thofma** [comment]
Claus also gave his OK, so we can go ahead and merge it.

**Pull request merged**
