### PR TITLE
Fix Fraction to accept rational as operand to adhoc +, -, *, ==.

### LINKED ISSUE #1181: Broken ad hoc operations for fractions
```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> x//2
x//2

julia> x//2 + 2//3
ERROR: InexactError: BigInt(4//3)
Stacktrace:
 [1] Integer
   @ ./rational.jl:110 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] setindex!(A::Vector{BigInt}, x::Rational{BigInt}, i1::Int64)
   @ Base ./array.jl:843
 [4] setcoeff!
   @ ~/.julia/dev/AbstractAlgebra/src/generic/Poly.jl:33 [inlined]
 [5] *(a::Rational{Int64}, b::AbstractAlgebra.Generic.Poly{BigInt})
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Poly.jl:770
 [6] *
   @ ~/.julia/dev/AbstractAlgebra/src/Poly.jl:778 [inlined]
 [7] +(a::AbstractAlgebra.Generic.Frac{AbstractAlgebra.Generic.Poly{BigInt}}, b::Rational{Int64})
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/Fraction.jl:320
 [8] top-level scope
   @ REPL[28]:1
```

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #1181

### CODE REVIEW

**Review by tthsqe12 — APPROVED** [review]

**Review by tthsqe12 — COMMENTED** [review]
Alright, I'll add a little test code then merge it

**Comment by wbhart** [comment]
Oh I see I missed the test code for FactoredFrac.

Probably similar functions are entirely missing for TotalRingOfFractions. Then again, it isn't as clear (to me) that they should exist there.

**Comment by tthsqe12** [comment]
wait, we got some problems here

**Review by tthsqe12 — COMMENTED** [review]
wait, we got some problems here

**Review by tthsqe12 — CHANGES_REQUESTED** [review]
For the test code FactoredFraction-test.jl, in the section Generic.FactoredFrac.ZZ.adhoc where 
`FF = FactoredFractionField(ZZ)`, add the following tests
```
    a = FF(-1//3)
    @test (a + 1//2) - 1//2 == a
    @test 1//2 - (1//2 + a) == -a
    @test divexact((a * 1//2), 1//2) == a
    @test divexact(1//2, 1//2 * a) == inv(a)
```

Next, delete the extra currently untested adhoc methods in FactoredFraction.jl. FactoredFraction <: FracElem, and julia is using the generic versions in src/Fraction.jl.

Finally, this will give an error on divexact, so the divexact also needs to split up the numberator and denominator as you have done for +,- and *.

**Comment by tthsqe12** [comment]
hmm. For me, if in generic/FactoredFraction.jl I delete the 8 untested methods
```
function +(a::FactoredFrac{T}, b::Rational) where T <: RingElem
function +(b::Rational, a::FactoredFrac{T}) where T <: RingElem
function -(a::FactoredFrac{T}, b::Integer) where T <: RingElem
function -(a::FactoredFrac{T}, b::Rational) where T <: RingElem
function -(b::Integer, a::FactoredFrac{T}) where T <: RingElem
function -(b::Rational, a::FactoredFrac{T}) where T <: RingElem
function *(a::FactoredFrac{T}, b::Rational) where T <: RingElem
function *(b::Rational, a::FactoredFrac{T}) where T <: RingElem
```
FactoredFraction-test.jl still passes. Then, if add the tests I mentioned above, the fail on divexact.

**Comment by wbhart** [comment]
Ok, I'll try it again. Perhaps it depends on Julia version. I was getting ambiguity errors.

**Comment by tthsqe12** [comment]
1.6 and 1.7 seem to be fine without them for FactoredFrac

**Review by tthsqe12 — APPROVED** [review]

**Pull request merged**
