### PR TITLE
Use @show_name, @show_special for (M)PolyRing

### PR DESCRIPTION
**Pull request by fingolfin**
I suspect this will be breaking in the sense that it'll cause mismatches in docstrings.

It might also affect the book?

### CODE REVIEW

**Comment by lgoettgens** [comment]
This will break some printing in I suppose Algebraic Geometry and/or Schemes chapters.

**Comment by joschmitt** [comment]
The problem we had with this is still not fixed:
```
julia> R, (x, y, z) = QQ["x", "y", "z"];

julia> A, AtoR = quo(R, ideal(R, x))
(Quotient of multivariate polynomial ring by ideal (x), Map: R -> A)

julia> S, (x, y, z) = QQ["x", "y", "z"];

julia> B, BtoS = quo(S, ideal(S, x))
(Quotient of multivariate polynomial ring by ideal (x), Map: R -> B)
```
It says `R` in the last line. This will break the OSCAR doctests where the same ring is created several times but with different names. Or am I doing something wrong/missed something?

**Comment by lgoettgens** [comment]
The example from @joschmitt works as expected. In the doctests, every code block gets executed in its own namespace, so this should no longer be a problem. Note that currently, we dig through the namespace to find a variable name, while before https://github.com/Nemocas/AbstractAlgebra.jl/pull/1594 an object cached its name, which in some cases was from a previous doctest. Thus I think that this should no longer be an issue

**Comment by fingolfin** [comment]
Yeah in the example by @joschmitt we have `R === S`, so this ring effectively has *two* names. This is one of the limitations of this name hack. Which name is "better" if there are multiple?

**Comment by joschmitt** [comment]
Okay, if this has been resolved in another way, I am happy.

**Comment by lgoettgens** [comment]
> Yeah in the example by @joschmitt we have `R === S`, so this ring effectively has _two_ names. This is one of the limitations of this name hack. Which name is "better" if there are multiple?

In https://github.com/Nemocas/AbstractAlgebra.jl/pull/1594 it was decided:
If there was a name previously used for name printing, and this name still points to the correct object, take this. Otherwise, take the first name in alphabetical order.

**Comment by fingolfin** [comment]
We just discussed and @fieker agrees this is the way forward and also other structures should be adapted to use these macros.

Of course it needs to be carefully coordinated as it is breaking...

**Pull request closed without merging**
