### PR TITLE
Move implementation of inv for series over fields to generic, add tests.

### PR DESCRIPTION
**Pull request by wbhart**
Nemo passes with these changes.

Running Hecke tests now. @thofma @fieker the Hecke tests currently take about half an hour to run on my poor laptop. Some individual tests take 5 or 10 minutes to run. Are these testing functionality not tested by the shorter tests, or are they mainly there to keep an eye on performance regressions?

If the latter, is there any possibility of wrapping them in a test for HECKE_TESTLONG or so in ENV? Only you guys actually know what timings to look out for, I presume, as these would be machine specific.

### CODE REVIEW

**Comment by thofma** [comment]
I started working on `short/long` tests last week. I will probably finish it today or tomorrow. We need it if we want to do reverse dependency testing. We will hopefully end up with 10 minutes for the (short) tests. Note that a significant amount of time is spent in compilation.

**Comment by wbhart** [comment]
@thofma That sounds fantastic!

**Comment by wbhart** [comment]
Random test failure seems unrelated. See #778

**Comment by wbhart** [comment]
Hecke passed with these changes.

**Pull request merged**
