### PR TITLE
Add @show_name invocations

### PR DESCRIPTION
**Pull request by fingolfin**
Also update ConstPolyRing show method

### CODE REVIEW

**Comment by lgoettgens** [comment]
@show_name requires the object to have attribute storage enabled

**Comment by fingolfin** [comment]
I don't think so? We specifically wrote it to also work for non-attribute storing types.

But `@show_special` does require it. However I wonder if we should change that, so that one can write `show` methods w/o having to worry about attribute storage being available or not.

But that's for another PR, if at all. For now, perhaps we don't *want* matrix spaces to print by name because they are supposed to be uniquely identified by their base ring plus dimensions. So perhaps I'll instead leave a comment there indicating we deliberately don't use `show_name` and `show_special`.

**Comment by lgoettgens** [comment]
> I don't think so? We specifically wrote it to also work for non-attribute storing types.
> 
> But `@show_special` does require it. However I wonder if we should change that, so that one can write `show` methods w/o having to worry about attribute storage being available or not.

I'll provide a PR that makes show_special a noop in these cases

**Comment by fingolfin** [comment]
With the `ConstPolyRing` changes moved to PR #1894 this is now rather small: on the one hand `MatRing` and `MatSpace` as mentioned before -- but perhaps we ought to retain those as they are?
And then for `NewRing` in the tests. That `show` method is specifically for testing the three printing modes, so perhaps it should also stay as it is.

So in principle I'd be OK with closing this...

**Pull request closed without merging**
