### PR TITLE
Remove hashp_seed

### PR DESCRIPTION
**Pull request by fingolfin**
I don't see what it is good for. Of course that doesn't mean it is important after all! If it is, it'd be good to document that in a comment.

Perhaps @rfourquet remembers why this was added?

### CODE REVIEW

**Comment by tthsqe12** [comment]
What we usually do here is write out the 64 bit constant and then do %Uint. I think the random constants were intended to give different hash values to, for example, the one of ZZ[x] and the one of ZZ[x,x^-1]

**Comment by fingolfin** [comment]
OK, thanks. But why is that necessary? That would only matter if one mixes regular polynomials and Laurent polynomials as, say, keys of a dictionary, wouldn't it?

Actually, it goes even further: it seem this actually causes a bug: things that compare as equal should have equal hashes. This is violated here, it seems:
```
julia> R, x = ZZ[:x]
(Univariate Polynomial Ring in x over Integer Ring, x)

julia> S, y = LaurentPolynomialRing(ZZ, "y")
(Univariate Laurent Polynomial Ring in y over Integer Ring, y)

julia> x == y
true

julia> 5*x^2 == 5*y^2
true

julia> hash(x)
0x27df705deb07c898

julia> hash(y)
0xe2572f352bc2fc94
```

Then again, perhaps the real bug is that this comparison is even allowed (I certainly find it surprising...)

**Comment by thofma** [comment]
I think dictionaries with different ring types are all broken in this regard. For we allow quite a lot of comparisons across different types, but cannot guarantee consistent hashs:
```julia
julia> Qx, x = QQ["x"];

julia> D = Dict()
DDict{Any, Any}()

julia> D[0*x] = 0
0

julia> haskey(D, 0)
false

julia> 0 == 0*x
true

julia> D[0] = 1
1

julia> D
Dict{Any, Any} with 2 entries:
  0 => 1
  0 => 0
```
Dictionaries use `isequal` (with a generic fallback to `==`), which we could overload to also do type checking. Or throwing an error if the types are unequal? I have no idea what is better.

**Comment by tthsqe12** [comment]
> Then again, perhaps the real bug is that this comparison is even allowed (I certainly find it surprising...)

The devs agreed at some point that there is canonical map ZZ[x] -> ZZ[x,x^-1], so the comparison here is as natural as that between elements of ZZ and QQ.

**Pull request closed without merging**
