### PR TITLE
Version 0.43.12

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by lgoettgens** [comment]
Hecke test failed. Maybe @thofma can have a look?

**Comment by fingolfin** [comment]
HeckeCI error:
```
The global RNG seed was 0x75a90a8e2b410bc6ec5d1542e19f6086.

Error in testset AlgAssAbsOrd/PicardGroup.jl:
Error During Test at /home/runner/.julia/packages/Hecke/Pu8AF/test/AlgAssAbsOrd/PicardGroup.jl:74
  Test threw exception
  Expression: test_disc_log_picard(P, mP, O)
  BoundsError: attempt to access ZZMatrix at index [8, 8]
  Stacktrace:
    [1] throw_boundserror(A::ZZMatrix, I::Tuple{Int64, Int64})
      @ Base ./abstractarray.jl:737
    [2] _checkbounds
      @ ~/work/AbstractAlgebra.jl/AbstractAlgebra.jl/src/Matrix.jl:62 [inlined]
    [3] getindex
      @ ~/.julia/packages/Nemo/Mhf6i/src/flint/fmpz_mat.jl:110 [inlined]
    [4] getindex(a::Hecke.FakeFmpqMat, i::Int64, j::Int64)
      @ Hecke ~/.julia/packages/Hecke/Pu8AF/src/LinearAlgebra/FakeFmpqMat.jl:51
    [5] #4451
      @ ./none:0 [inlined]
    [6] iterate
      @ ./generator.jl:47 [inlined]
    [7] _any(f::typeof(identity), itr::Base.Generator{UnitRange{Int64}, Hecke.var"#4451#4452"{Hecke.FakeFmpqMat}}, ::Colon)
      @ Base ./reduce.jl:1226
    [8] any
      @ ./reduce.jl:1215 [inlined]
    [9] any
      @ ./reduce.jl:1141 [inlined]
   [10] is_invertible(a::Hecke.AlgAssAbsOrdIdl{GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}, GroupAlgebraElem{QQFieldElem, GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}}})
      @ Hecke ~/.julia/packages/Hecke/Pu8AF/src/AlgAssAbsOrd/Ideal.jl:1366
   [11] test_disc_log_picard(P::FinGenAbGroup, mP::Hecke.MapPicardGrp{FinGenAbGroup, Hecke.AlgAssAbsOrdIdlSet{GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}, GroupAlgebraElem{QQFieldElem, GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}}}}, O::Hecke.AlgAssAbsOrd{GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}, GroupAlgebraElem{QQFieldElem, GroupAlgebra{QQFieldElem, FinGenAbGroup, FinGenAbGroupElem}}})
      @ Main ~/.julia/packages/Hecke/Pu8AF/test/AlgAssAbsOrd/PicardGroup.jl:4
   [12] macro expansion
```
Maybe a randomization issue, I'll restart the test.

**Comment by fingolfin** [comment]
HeckeCI error went away after re-run

**Comment by thofma** [comment]
What a useless error message. Does not even tell me what the dimension of the matrix is.

**Pull request merged**
