### PR TITLE
add functions lc, lm, lt and lcm

### PR DESCRIPTION
**Pull request by heiderich**
to compute the leading coefficient (lc), the leading monomial (lm)
and the leading term (lt) of a polynomial and the least common multiple
of two polynomials

### CODE REVIEW

**Comment by wbhart** [comment]
* lc can use coeff(f, 1) instead of f.coeff[1], then it will apply to all kinds of polynomials (obviously we should use first(coeffs(f)), but I am ok with delaying this until Singular.jl has the iterators implemented, if you prefer)
* You can change the types for all of these functions to AbstractAlgebra.MPolyElem{T}, so that they don't only accept Generic.MPoly's
* lcm should probably call check_parent, at least for the first part (divrem will already check it of course)
* @thofma @fieker are you guys ok with the lm, lc and lt abbreviations (I am not really opposed to them)

**Comment by heiderich** [comment]
First  AppVeyor failed, because there was a merge conflict (another PR was merged in the meantime). I do not know why it still fails.

**Comment by thofma** [comment]
I am fine with the names.

**Comment by wbhart** [comment]
Your latest commit reintroduced the function coeffs for returning an array. coeffs is now supposed to return an iterator. You also don't need this for your functions.

Could you also add examples and invocations of the documentation in the docs, in mpolynomial.md.

**Comment by heiderich** [comment]
I added the documentation you requested.

> Your latest commit reintroduced the function coeffs for returning an array. coeffs is now supposed to return an iterator. You also don't need this for your functions.

Sorry, I messed up the merge. I edited the merge commit and force-pushed it.

**Comment by wbhart** [comment]
Thanks.

**Pull request merged**
