### PR TITLE
rename perm -> Perm

### PR DESCRIPTION
**Pull request by rfourquet**
As a new "breaking" release of AA is in preparation, here is a breaking change.
Julia's [convention](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Use-naming-conventions-consistent-with-Julia-base/-1) is for types to be CamelCase. All exported types from `AbstractAlgebra` follow this convention, except `perm`. Let's fix this.
```julia
julia> function gettypes(m::Module, only_lower=false; all=false)
           modnames = names(m, all=all)
           if only_lower
               filter!(n -> islowercase(first(String(n))), modnames)
           end
           modobjs = getfield.(Ref(m), modnames)
           filter(x -> x isa Union{DataType,UnionAll,Union}, modobjs)
       end
gettypes (generic function with 2 methods)

julia> gettypes(AbstractAlgebra)
41-element Array{Any,1}:
 AbsSeriesElem
 AccessorNotSetError
 Array
 ErrorConstrDimMismatch
 Fac
 FieldElem
 Union{FieldElem, AbstractFloat, Rational}
 FinField
 FinFieldElem
 FracElem
 FracField
 FunctionalMap
 GroupElem
 IdentityMap
 MPolyBuildCtx
 MPolyElem
 MPolyRing
 Map
 MatAlgElem
 MatAlgebra
 MatElem
 MatSpace
 ModuleElem
 NCPolyElem
 NCRingElem
 NumField
 NumFieldElem
 PolyElem
 PolyRing
 RelSeriesElem
 ResElem
 ResRing
 RingElem
 Union{RingElem, AbstractFloat, Integer, Rational}
 SeriesElem
 SeriesRing
 SetElem
 SetMap
 SimpleNumField
 SimpleNumFieldElem
 perm

julia> gettypes(AbstractAlgebra, true; all=true)
2-element Array{Any,1}:
 AbstractAlgebra.gfelem
 perm

julia> gettypes(AbstractAlgebra.Generic, true)
5-element Array{Any,1}:
 direct_sum_module_elem
 free_module_elem
 quotient_module_elem
 snf_module_elem
 submodule_elem
```

`perm` is the most urgent to fix as it's exported. But `gfelem` should also probably be capitalized. What about `Generic` types? In the list above, they are not re-exported by `AbstractAlgebra`, so they may be considered as internal. Is the end user assumed to be allowed to do `using Generic` ? If yes, exported types should also probably be CamelCased.

### CODE REVIEW

**Comment by kalmarek** [comment]
I'm very much for it.

We can also think about (as a future breaking change) to make `Perm`s parent-less i.e. more in the style of GAP permutations. Any thoughts about it?

**Comment by wbhart** [comment]
We are very much aware of this convention, but we have a different convention to distinguish parent types from element types. It would simply be too much work to rename them all now.

I suggest not exporting the perm type unless Perm is the name of a parent constructor function in which case it should be capitalised.

But even then, I have been told that we are switching to using lower case for some of these, e.g. sub and quo. You aren't going to convince @fieker to change this. He doesn't like capitalised names.

Most Nemo types are lower case, as they correspond to Flint types. Same as Singular.jl types. This just isn't feasible to change.

**Comment by thofma** [comment]
`sub` and `quo` are functions and not type names.

The question is just about making the type names in AbstractAlgebra consistent. Nothing more.

**Comment by wbhart** [comment]
Sure, so long as it is limited to AbstractAlgebra and doesn't have other consequences, I'm ok with it.

**Comment by thofma** [comment]
So you are OK with `FreeModuleElem` instead of free_module_elem`? Just to be sure.

**Comment by wbhart** [comment]
I couldn't care less. I'm just not changing all the names everywhere else.

**Comment by rfourquet** [comment]
> we have a different convention to distinguish parent types from element types

I don't see this convention in AbstractAlgebra, `perm` is the only lower-case elemtent type. Or did I misunderstand?

> Most Nemo types are lower case, as they correspond to Flint types. 

Yes, this is more tricky here. I don't have a strong enough opinion here to fight this battle, but I invite you to look at this Julia [PR](https://github.com/JuliaLang/julia/pull/21654) where I wrapped some low level `GMP` functions, in particular this [discussion](https://github.com/JuliaLang/julia/pull/21654#pullrequestreview-35523102), which got me convince to call the module `MPZ` instead of `mpz`.

**Comment by wbhart** [comment]
I support the change for the AbstractAlgebra module, since it is written in pure Julia and has as one of its many aims to be a contribution back to the Julia community. But I don't support it for types that are named after C library types as in Nemo.jl (flint/arb/antic), Singular.jl (Singular), Gap.jl (Gap), Polymake.jl (Polymake) and so on. It's too hard to police, and a complete waste of time.

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 01:50:44AM -0700, wbhart wrote:
> We are very much aware of this convention, but we have a different convention to distinguish parent types from element types. It would simply be too much work to rename them all now.
> 
> I suggest not exporting the perm type unless Perm is the name of a parent constructor function in which case it should be capitalised.
> 
> But even then, I have been told that we are switching to using lower case for some of these, e.g. sub and quo. You aren't going to convince @fieker to change this. He doesn't like capitalised names.
No, what he doesn't like is to guess if s.th. is a constructur (type) or
a function. Their use is mixed, the distinction not at all clear
(matrix? Matrix?). Any nameing scheme that requires the user to
understand the implementation details to predict names is flawed.
This is why I lobby strongly for anything that a user is ever expected
to call to also be available in lower case.

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 01:20:08AM -0700, kalmarek wrote:
> I'm very much for it.
> 
> We can also think about (as a future breaking change) to make `Perm`s parent-less i.e. more in the style of GAP permutations. Any thoughts about it?
> 
Yep. I am against it.
OK: to me there are 2 different objects
  sigma in S_n
  sigma in union(S_n)
I'm happy if you want both, but they will have to be differnt types and
different parents.
e.g. what is the degree of a permutation? (or whatever the n in S_n is
called)? In the 2nd case it is either random or an error...
In the 1st case, its clear.

In general, the 2nd is more in line for symbolic computations where
there is no parent and you make things up as you go.
The 1st is more in line what we have to do to support number theory (and
most group theory: where this universal parent objects are not good to
handle)
The 2nd is convenient - when applicable. But, as I said, really s.th.
different.

**Comment by kalmarek** [comment]
@fiker `PermGroup`s are constructed on the fly anyway, and the only uses in nemo/AA are  `(P::PermGroup)()` (through `parent(p::perm)()`). In GAP perms of different degrees can be mixed, so it seems that in most of the computations the degree doesn't have to be determined at runtime (it's part of the input). How does Hecke use `PermGroup`? What is the use-case of a degree of a given permutation?

Maybe @ThomasBreuer can chime in?

**Comment by thofma** [comment]
I think you meant @fieker.

**Comment by kalmarek** [comment]
indeed :D

**Comment by ThomasBreuer** [comment]
@kalmarek Concerning GAP's point of view, there is a function `LargestMovedPoint` applicable to both a permutation or a permutation group, with the obvious meaning. GAP does not use `Degree` in this context.
Permutations in GAP do not have parent objects. They are created individually, not as elements associated to a prescribed symmetric group. And groups can then be generated from these permutations.
Internally, a permutation is represented as an array of images, of length at least the `LargestMovedPoint` value. If one enters a permutation in cycle notation (for example (1,2,3)(4,5)) then the internal array is not larger than necessary. In the current implementation, multiplying two permutations with perhaps different internal array length yields a permutation with internal array length the maximum of the two array lengths. Thus a permutation can have different internal representations. Here is an extreme example.
```
gap> pi:= (1,10^5);
(1,100000)
gap> sigma:= pi * (2,3) * pi;
(2,3)
gap> sigma = (2,3);
true
gap> LargestMovedPoint( sigma );
3
gap> SIZE_OBJ( pi );  # the internal size of the permutation
400008
gap> SIZE_OBJ( sigma );
400008
gap> SIZE_OBJ( (2,3) );
14
```

**Comment by fieker** [comment]
On Fri, Sep 27, 2019 at 07:23:59AM -0700, kalmarek wrote:
> @fiker `PermGroup`s are constructed on the fly anyway, and the only uses in nemo/AA are  `(P::PermGroup)()` (through `parent(p::perm)()`). In GAP perms of different degrees can be mixed, so it seems that in most of the computations the degree doesn't have to be determined at runtime (it's part of the input). How does Hecke use `PermGroup`? What is the use-case of a degree of a given permutation?
> 
In Hecke, so far: nil
However, I've extensively used perm grps in Magma (for Galois theory)
and was using defined parents and the degree frequently...
Also: the parent of perm is clearly a group, albeit, in this case, in
infinte one. So very few group theoretical operations will be
supported...
If you have perm operating on MPoly, how do you decide if this is legal?
Makes sense?
To me, there is the balance between convenince and error checking.
Mostly if I mix elements from different structures, its unintended and
I'm happy to get errors.
However, you can clearly get used to the freedom...

**Comment by thofma** [comment]
A group element has a centralizer and a normalizer. So what is the normalizer or centralizer of a parent-less permutation?

When dealing with subgroups, you usually want your permutations to know where they live. Consider for example four copies of S_3 embedded (differently) in S_4. I think that without a proper layer of parents you will quickly become insane :) If you can always multiply everything with everything, you will never know if you multiplied (by accident) the elements in the wrong group.

What do you think about the following? We keep the permutation type as is and allow permutations without parents. 
- `perm"(1, 2)(3, 4)"` (or whatever the notation is) creates a parent-less permutation.
- `G(p)` or `G("(1, 2)(3, 4)")` creates a permutation with parent object `G`.
- You can only multiply two permutations if both are parent-less or both have the same parent.
What do you think?

**Comment by fieker** [comment]
I would goa small step further, the current "perm" gets an (implicit)
perent: the union of all S_n. This is a proper well defined (inifinite)
group S, so it fits the framework.
sub(S, [p_1, ..., p_n]) is difficult: it could be a subgroup of S_n for
the smallest n
sub(S_n, [p_1...]) would be fine - as long as the p_i don't touch
anything > n?
S would be a group - but, propbably without too much functionality, you
should be able to define homomorphisms ending in S, possibly, even using
functions, define homs from S, who kowns.

**Comment by ThomasBreuer** [comment]
@thofma I would distinguish the technical aspect of a parent object (to define which permutations are regarded as equal or can be multiplied, and to allow for early error messages in situations that are regarded as wrong) from the aspect that a parent object (once one has it) can be used also for other purposes.

For example, the question about centralizer and normalizer of a group element (or of a group) belongs to the second aspect. The centralizer C_G(g) of a group element g is defined relative to a group G, and usually (in interesting cases) G will not be a symmetric group; as far as I understand the setup, such a G cannot be the parent object in the technical sense.
(GAP supports an optional `Parent` attribute for groups (not for group elements), in order to be able to store known information about centralizer or normalizer w.r.t. this parent group; for that, GAP has the attributes `CentralizerInParent` and `NormalizerInParent`.)

Supporting elements of algebraic structures in two variants, with or without parent object,  will cause problems if there is (generic) code that tries to access the parent object.
(If there is no such code then this indicates that the parent object is in fact not needed.)
Also, some additional code may arise:
If two permutations with parent are regarded as equal only if they are assigned to the same symmetric group, and if this implies that only the internally stored arrays have to be checked for equality, then one wants the method in question to do just this, whereas the equality check for parentless permutations is more involved.

Introducing special objects as allowed parents, such as the union of all S_n, solves only the problem that one can always access a parent object.
On the other hand, one makes the system more complicated, in particular if one wants to regard the parent objects as algebraic structures, in this case the union of all S_n as a group.
If this object is a valid group then one has to be aware of it wherever a (permutation) group can occur, and may be forced to write code that deals with it.
(In GAP, introducing this object as a permutation group would for example mean that we lose the implication that any permutation group in GAP is finite, without benefit.)

**Comment by wbhart** [comment]
I'm a bit lost by this conversation, so cannot contribute much. But I am confused by something.

Earlier @fieker mentioned that without a layer of parent objects you will not be able to deal easily with different embeddings of S_{n-1} into S_n. But then later he suggested there be a parent object which is the union of all S_n.

This seems like a contradiction to me, as there are n embeddings of S_{n-1} into S_n (unless you identify the elements of the sets being permuted, which you might not want to do).

What is the "current perm"? Are you talking about the perm that @kalmarek has implemented, or the current Gap notion of perm (which is different, as I understand it)?

**Comment by fieker** [comment]
I think this is partly just a clash of cultures: Magma vs Gap
or ??? vs Symbolic

Clearly, group theory can, efficiently, work in both worlds, otherwise
at least one of Gap and Magma could not exist.

Also, the Gap way is more convenient (at least initially) since you do
not need to worry about parents (similar with (in Gap) cyclotomics,
polynomials, ...)
In Magma on the other hand, almost everything starts by creating
parents.

Pro/ Con:
 - this is (intially at least) less convenient
 - every object has a natural, automatic context
   e.g. in Magma (and currently Oscar = Hecke):
   Trace of a cyclo element is well defined, as I know the currect ring.
   In gap this cannot work - unless the source ring and the target ring
   are specified. (or, at least the results are kind of random...)
   (I just tried Trace(E(10)); and Trace(E(10)^10); - clearly they are
   doing different rings - I don't know how to get the trace wrt a fixed
   field...)
 - the "symbolic" approach cannot (well really hard) work in all
   contexts, while the other can.
 - Gap people (and the interface writer(s)) are happier the more gap
   like it is
 - users will get confused about why things work and why not. (or why
   some objects require a parent first, others not)

As I said, I'd "support" this under the understanding that the parent is
the union of S_n, a group in which we cannot do too much. (Similary to
Q/Z or K^* for infinite fields K)
Then this is consistent.
Same can be done for (a version of) cyclos: the abelian closure of Q.
Here norm, trace, charpoly are not well defined...

**Comment by ThomasBreuer** [comment]
@fieker As you write, if the objects do not know the context, one has to provide it in the function call.
In GAP, one can write for example `Trace( CF(15), E(3) )` or, for a trace w.r.t. a field extension, `Trace( CF(15), CF(5), E(3) )`. Without this information, GAP chooses a default context that is based on the given field element.
Analogously, `Factors( R, pol )` computes the factorization of the polynomial `pol` in the polynomial ring `R`, and `Factors( pol )` chooses a default for `R`.

**Comment by kalmarek** [comment]
@thofma this is what I had in mind, but given @ThomasBreuer input it might be even better without carrying parent object at all, e.g.

```julia
mutable struct PermutationGroup <: Group
    n::Int
    gens::Vector{perm}
    base::Vector{perm}
    whatnot::Any

    PermutationGroup(n::Int) = (G = new(n); G.gens = [G(perm"(i,i+1)") for i in 1:n-1]; G)
    PermutationGroup(n, gens) = (G = new(n); G.gens = G.(gens); G)
    PermutationGroup(gens::Vector) = ...
    # other constructors  
end

mutable struct Perm <: GroupElem
    d::Vector{Int}
    parent::PermutationGroup
    other_stuff::Any

    Perm(d::AbstractVector{Int}) = new(d)
    Perm(d::AbstractVector, G::PermutationGroup) = new(d, G)
end

parent(p::Perm) = (isdefined(p.parent) ? p.parent :  PermutationGroup(length(p.d))
```

* A context-free call `centralizer(::perm)` would compute the centralizer in the default context (e.g. the smallest full symmetric group, which contains the permutation)
* `centralizer(p::perm, G::PermutationGroup)` be the centralizer in a `PermutationGroup` `G`, by which I mean a group generated by a set of permutations (with possibly strong generating set, base, etc.) as opposed to `PermGroup` which represents only the full symmetric group at the moment.
* of course one can not rely on the equality of lengths of arrays defining permutations any longer. That will complicate things a bit (or maybe it won't if we correctly overload `getindex`).

* a drawback is that one needs to explicitly pass `G` itself to any context-aware function involving permutations (or maybe it's an advantage??)
* the other one is breaking a generic code which may call `parent(::perm)`; this could be partially amended by creating this _union-style_ finitely supported permutations of NN group, but it seems quite fragile to me (what if `for g in parent(s)...`?)

Anyway, we're just exploring different ideas here, we don't need to commit to any particular solution, but it's very valuable to have this discussion and see what are the options.

**Comment by thofma** [comment]
How is your code snippet different than what I said? Your permutations also have parents.

**Comment by kalmarek** [comment]
@thofma only very slightly: parent-less permutation (i.e. created by `Perm(...)`, or `perm"(...)"`) has the default "context" of the minimal symmetric group which contains it.

Well, I see now that what I wrote is inconsistent ;) going parent-less works perfectly well for `perm`s, but might not play well with the generic group code...

**Pull request merged**
