### PR TITLE
tests: use ReTest package instead of Test

### PR DESCRIPTION
**Pull request by rfourquet**
Basically, this makes it easy to run only a subset of the tests, by filtering them with a `Regex`, which is matched against the "description" of the testsets. As our testsets have predictable descriptions, this works rather well here.

This tries to solve the following problem: say I make a change to `rand` methods on polynomials, and want to test whether my change broke the test suite. It's very unefficient to just run the whole test suite, because typically a bunch of unrelated stuff will be tested before the relevant tests. I usually do the following:
1. copy paste "setup" code from runtests.jl (this would be allieviated with #541)
2. copy paste the "rand" testset from Poly-test.jl
3. if 2) worked, do `include("generic/Poly-test.jl")` (to widen the scope of the tests while still not running everything)
4. if 3) worked, do `include("runtests.jl")` or `]test AbstractAlgebra`

What I often find myself doing is also commenting out a bunch of `include` lines in the "AbstractAlgebra-test.jl" file, and/or in one of the subfiles (e.g. "Ring-test.jl"), followed by `include("runtests.jl")`.

With `ReTest`, you can do the following:
1. do `include("test/tests.jl")` (it takes 6s the first time, and 1s afterwards)
2. do `runtests(AbtractAlgebraTests, "Poly.rand")` (run testsets containing "Poly.rand")
3. if 2) works, do `runtests(AbtractAlgebraTests, r"Generic.Poly")` 
4. if 3) works, do `runtests(AbtractAlgebraTests, "rand")` to test interactions of my changes to `rand` on Poly with other `rand` methods
5. do `runtests(AbtractAlgebraTests)` to test everything

In practice, I have found this workflow more convenient (I have manually replaced `using Test` with `using ReTest` in the last couple of weeks or so when testing), so I would like to invite you to try it out! 

I plan a bunch of improvements to `ReTest`, but it's already very usable as is. The main "problem" currently is with filtering: sometimes, "non-final" testsets (those which contain nested testsets) would often be run because they might contain a testset whose description is matching (partial regex matching is used, but there are usually lots of false positive).

Regarding efficiency, in one run of the whole testsuite, it was slower by maybe 1% compared to using `Test` (this difference might be only noise).

See https://github.com/JuliaTesting/ReTest.jl for a description of the package. Here is a little demo:
```julia
julia> runtests(AbstractAlgebraTests, "Poly.rand")
Test Summary:               |
Generic.MatAlg.inversion... | No tests
Test Summary:          | Pass  Total
Generic.NCPoly.rand... |   16     16
Test Summary:     | Pass  Total
NCRings.powers... |    1      1
Test Summary:        | Pass  Total
Generic.Poly.rand... |   96     96
Test Summary:       |
Generic.LaurentPoly | No tests
Test Summary:              | Pass  Total
Generic.Mat.permutation... |    1      1
Test Summary:             | Pass  Total
Generic.Mat.comparison... |    2      2
Test Summary:         | Pass  Total
Generic.MPoly.rand... |   18     18
```
So when passing `"Poly.rand"` for filtering, this is transformed into `r".*Poly\.rand"`. In the above, few unrelated tests are run because they might contain relevant tests, although their nested testsets are not run (hence "No tests" or only a couple run tests). To be more precise, as you know that the testset is at the toplevel, you can directly pass the `r"\.Poly\.rand"` regex to be more precise:

```julia
julia> runtests(AbstractAlgebraTests, r"\.Poly\.rand")
Test Summary:        | Pass  Total
Generic.Poly.rand... |   96     96
```

### CODE REVIEW

**Comment by thofma** [comment]
What is the problem with the current `test_module` approach?

**Comment by rfourquet** [comment]
> What is the problem with the current test_module approach?

First, it has been slighlly broken since we removed `test_...` functions in favor of using testsets (still the testsets could run). Also, it's now more broken because it doesn't include "setup" code.

But more importantly for me, `ReTest` gives finer control over the specific tests you want to run. Also, it allows to run code out of the box at the REPL without spawning a new julia process, which is practical when using Revise. I know that it could be made to work with `test_module`. But I find useful having a package that does for you and saves you from re-implementing the same `test_module` functionality in multiple packages :shrug:

**Comment by fingolfin** [comment]
This seems useful to me. Not sure of @thofma or @fieker agree, though?

In any case, my one concern would be that somebody who's new to the project would not know how to make use of this ReTest functionality (that would also include me after not using the feature for a month ;-) ). But I think a brief comment at the top of `test/runtests.jl` which explains about ReTest, links to it, and perhaps gives a short usage example or three (taken from the issue description) would take care of that.

**Comment by fieker** [comment]
Is this a standart julia package, guaranteed to be supported? Does this add functionality that justifies yet another external reference?
I'd favour stability over changing infrastructure (yet again).

**Comment by rfourquet** [comment]
> Is this a standart julia package, guaranteed to be supported?

No, it's registered but I'm at the moment the only contributor and probably the only user, so there is risk that it gets unmaintained at one point (low "bus factor").

> Does this add functionality that justifies yet another external reference?

In my biased opinion, yes. It's a generally useful package, but it's the inefficiency of the default `Test` system when working on Oscar packages that prompted me to develop it. But I won't push for it, it's easy enough for me to use it locally.

In any case, the package evolved since this PR (e.g. the "main problem" with filtering mentioned in the OP is fixed), but a couple usability annoyances got introduced, so this might not be the best time to  merge the PR. I estimate that I will need maybe one or two weeks of work on `ReTest` before announcing it on discourse; then it might attract other maintainers. When I will find time for that is another question.

**Comment by rfourquet** [comment]
I released a new version of the package (0.2.0). It's still alpha software, but if someone is interested to try it out, it's now easy to use it without changing the test code. You can do:
```julia
using ReTest, AbstractAlgebra
ReTest.hijack(AbstractAlgebra)
retest(AbstractAlgebraTests, ...)
```

If you want to run tests in parallel, you can do:
```julia
using Distributed
addprocs(2)
@everywhere begin
   using ReTest, AbstractAlgebra
   ReTest.hijack(AbstractAlgebra)
end
retest(AbstractAlgebraTests, ...)
```
I think the benefit of running two workers is more visible with `Nemo`, but I didn't benchmark much. See documentation at https://juliatesting.github.io/ReTest.jl/dev/.

Note that an `AbstractAlgebra` testset is failing in `Distributed` mode (`"Generic.Mat.permutation..."`). A fix (which took me a while to come up with) would be to define
```julia
Base.:(==)(I::Integers,    J::Integers) = false
Base.:(==)(I::Integers{T}, J::Integers{T}) where {T<:Integer} = true
Base.:(==)(I::Rationals,    J::Rationals)  = false
Base.:(==)(I::Rationals{T}, J::Rationals{T}) where {T<:Integer} = true
Base.:(==)(I::Floats,    J::Floats)  = false
Base.:(==)(I::Floats{T}, J::Floats{T}) where {T<:AbstractFloat} = true
```
I can issue a PR with this change if you think it makes sense.

**Comment by thofma** [comment]
So ReTest "just works" without changing any code? 

I am curious about the test failure. Why do we need those methods?

**Comment by rfourquet** [comment]
> So ReTest "just works" without changing any code?

This works on simple enough test codebases by replacing (in the `hijack` function) `using Test` with `using ReTest` and doing that recursively on included files (when `include` is at the toplevel). For example it doesn't work with `Hecke`, I guess because of non-toplevel `include` directives (I'm not sure to which extent something can be done on the `ReTest` side of things).

> I am curious about the test failure. Why do we need those methods?

It's a bit subtle: when there is `@testset "blah" for x in (ZZ,) ...`, the loop iterator (`(ZZ,)`) is evaluated in the main process, so `x == ZZ1` where `ZZ1` is `ZZ` on that process. But when the corresponding testset body is evaluated on process 2, `x` can be compared (e.g. as a base ring) to `ZZ2` where `ZZ2` is `ZZ` on the current second process, so the comparison fails (`ZZ1 != ZZ2`). `ZZ` is supposed to be a singleton object in the system, always equal to itself, but this breaks in a distributed setting. So the equality definitions above fix this, but I guess simply making the types immutable (e.g. `Integers`) and getting rid of the global cache for the objects would fix the problem in a better way (I don't see the reason to have them mutable, as they have no fields, which means comparison of bitstype instances should not be slower than pointer comparison).

**Comment by lgoettgens** [comment]
As ReTest.jl hasn't had any maintenance since Nov 2021, I would not be inclined to use it. Thus closing

**Pull request closed without merging**
