### PR TITLE
Docfixes

### PR DESCRIPTION
**Pull request by sachinkm308**

### CODE REVIEW

**Comment by wbhart** [comment]
Is this ready to merge @sachinkm308 ? Or do you still have something to add?

**Comment by sachinkm308** [comment]
> Is this ready to merge @sachinkm308 ? Or do you still have something to add?

Please go ahead, it is ready to merge @wbhart

**Comment by sachinkm308** [comment]
Sorry accidently closed

**Comment by wbhart** [comment]
Cool. I will try and check it all today if I get time.

**Comment by wbhart** [comment]
In ncpolynomial.md it seems you removed the documentation for evaluate(::NCPolyElem, ::Integer). Was there a reason for that?

**Comment by wbhart** [comment]
In a few cases, the variable names in the prototype in the docstring now don't match the variable names used in the description in the same docstring. For example:

```
@doc Markdown.doc"""
    shift_right(f::AbstractAlgebra.AbsSeriesElem, n::Int)	   
    shift_right(x::AbstractAlgebra.AbsSeriesElem{T}, len::Int) where {T <: RingElement}
> Return the power series $f$ shifted right by $n$ terms, i.e. divided by	> Return the power series $f$ shifted right by $n$ terms, i.e. divided by
> $x^n$.	> $x^n$.
```

Note the variable name has changed to f, but the description still uses x. In such cases, you should change the description to use the same variable name as the prototype. (The prototype is correct, but the textual description is now not correct any more.)

Also, in this particular case, you have two different prototypes for the same docstring. One of them should be removed.

You should look at the "Files changed" tab on the GitHub PR to see cases like this. It will show you what was there before, and what is there now, which will help you figure out which variable names should be changed to what.

**Comment by wbhart** [comment]
In GenericTypes.jl you have

```
CycleDec(ccycles, cptrs, n){T}
```

I think this should be

```
CycleDec{T}(ccycles, cptrs, n) where T
```

It's an exception to the usual rule because it is an inner constructor. I have no idea whether the documentation tool will actually support this or not. Let me know if it causes an error.

**Comment by wbhart** [comment]
In Matrix.jl, could you replace MatrixElem with Generic.MatrixElem (and MatrixElem{T} with Generic.MatrixElem{T}) in all the prototypes in the docstrings. (Do not change any that already have AbstractAlgebra.MatrixElem, only the ones that are just MatrixElem). This was not an error on your part, just something I missed.

**Comment by wbhart** [comment]
Similarly, could you replace LaurentSeriesElem with Generic.LaurentSeriesElem in LaurentSeries.jl.

**Comment by wbhart** [comment]
Similarly in Poly.jl could you replace PolynomialElem with Generic.PolynomialElem, again being careful to get the right ones.

**Comment by wbhart** [comment]
Ok, I have finished this review and will do another after you have made all the above changes. Perhaps you could fix each issue as a separate commit so I can check them one by one. Just push more commits to the same branch. They will automatically show up here. There is no need to make a new PR. Don't forget to rebase against the current master, which looks like it shouldn't cause any problems.

**Comment by wbhart** [comment]
One final thing. When the variable name used to be a capital letter, e.g. R or S, but has been changed to a lower case letter, it might be better to stick with the capital letter (in both the prototype and description in the docstring). Even better would be to change the actual code itself to use this upper case letter instead of the new lower case letter so that the actual function prototype also matches the prototype in the docstring prototype as well as the docstring description. Of course this has to be done carefully, in case this letter has already been used in the function for something else.

**Comment by wbhart** [comment]
Actually, you can probably ignore this last one. Most of the cases I can find is where R was replaced with r, and this is actually correct, as the parameter R wasn't a ring in the first place, but a ring element. Elements should have lower case. So just ignore this last comment about capital letters.

**Comment by sachinkm308** [comment]
> In ncpolynomial.md it seems you removed the documentation for evaluate(::NCPolyElem, ::Integer). Was there a reason for that?

This was because there was an error while running make.jl and was removed to check if it was working and forgot to put it back.

**Comment by sachinkm308** [comment]
> In a few cases, the variable names in the prototype in the docstring now don't match the variable names used in the description in the same docstring. For example:
> 
> ```
> @doc Markdown.doc"""
>     shift_right(x::AbstractAlgebra.AbsSeriesElem{T}, len::Int) where {T <: RingElement}
> > Return the power series $f$ shifted right by $n$ terms, i.e. divided by	
> > $x^n$.
> ```
> 
> Note the variable name has changed to f, but the description still uses x. In such cases, you should change the description to use the same variable name as the prototype. (The prototype is correct, but the textual description is now not correct any more.)
> 
> You should look at the "Files changed" tab on the GitHub PR to see cases like this. It will show you what was there before, and what is there now, which will help you figure out which variable names should be changed to what.
> 
> Note that if you currently have something like $n$ in the description, and it has to be changed to a variable name with more than one letter, e.g. len, then you have to write `len` not $len$. The latter is math mode and means the product of l, e and n. The former means it is a name that appears in code.

This was changed because the function description was updated and i copied the new ones. So the old variables are obsolete in this case. 

Old definition
`shift_right(f::AbstractAlgebra.AbsSeriesElem, n::Int)`

Updated function defintion

`function shift_left(x::AbstractAlgebra.AbsSeriesElem{T}, len::Int) where {T <: RingElement}`

**Comment by wbhart** [comment]
There are still many cases where the arguments that appear in the docstring description don't agree with the argument that appears in the docstring prototype.

Here are the ones I found:

```
LaurentSeries:
==============
LaurentSeriesRing -> Generic.LaurentSeriesRing
LaurentSeriesField -> Generic.LaurentSeriesField
shift_left: len -> n
shift_right: len -> n
truncate: prec -> n
divexact: a, b -> x, y (more than once)

MPoly:
======
gen : i-th -> $i$-th

Matrix:
=======
+, -, * : a, b -> x, y

Poly:
=====
divexact: a, b -> f, g (more than once)
divides: f, g -> z, x
integral: a -> x
resultant_ducos: a, b -> p, q

RelSeries:
==========
shift_left: n -> len
shift_right: n -> len
truncate: n -> prec
divexact: a, b -> x, y (more than once)

Residue:
========
==, isequal: x, y -> a, b (multiple times)

ResidueField:
=============
==, isequal: x, y -> a, b (multiple times)
```

I will merge this PR. Can you pull into your master and start a new branch and PR to fix these.

**Pull request merged**
