### PR TITLE
add iteration for matrix spaces

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by thofma** [comment]
Love it!

**Comment by fieker** [comment]
On Thu, Jan 14, 2021 at 05:26:52AM -0800, thofma wrote:
> Love it!

Apart from being cool and desireable, what is the difference bewtween
ProductIterator in AA and in Base.Iterators?

**Comment by thofma** [comment]
> On Thu, Jan 14, 2021 at 05:26:52AM -0800, thofma wrote: Love it!
> Apart from being cool and desireable, what is the difference bewtween ProductIterator in AA and in Base.Iterators?
> […](#)
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#726 (comment)](https://github.com/Nemocas/AbstractAlgebra.jl/pull/726#issuecomment-760195731)

They are doing quite different things. `Iterators.product` takes a constant number of iterators (constant in the sense of compile time). That is why one has to do splatting and that is why it is slow to compile. It was also quite slow in our experience. Also it does not allow the inplace iteration.

**Comment by thofma** [comment]
(PS: We are already using something like this in Hecke and @rfourquet also had something similar lying around. Having it here is a good idea.)

**Comment by rfourquet** [comment]
> what is the difference bewtween ProductIterator in AA and in Base.Iterators?

The main difference is
1)  you pass in an array with `n` iterators, instead of `n` arguments, so you avoid splatting
2) the shape of `Iterators.product` depends on `n`, i.e. it has `n` dimensions, so it means recompilations each time you have a differen number of iterators.

**Pull request merged**
