### PR TITLE
Square root of all the things

### PR DESCRIPTION
**Pull request by wbhart**
This main purpose of this PR is to provide:

* generic sparse multivariate square root [1] (new algorithm)
* generic univariate square root [1]

There are two functions: sqrt and issquare.

It also adds:

* issquare for integers and rationals
* issquare and sqrt for Z/pZ
* issquare and sqrt for fraction fields

Exact multivariate sqrt (check=false) is about twice as fast as checked mode (at 4000 terms in output). Exact univariate sqrt is only about 20% faster (at 10000 terms in output).

Note this does not provide sqrt for multivariates in Nemo, as this has to be implemented in Flint (which @tthsqe12 and I have agreed to do soon).

The PR makes no systematic attempt to implement the new sqrt interface being discussed.

[1] over an (exact) integral domain in which a sqrt is available

### CODE REVIEW

**Comment by tthsqe12** [comment]
So, _testing if something is a square and getting its square root if it is_ is going to come down to two calls to sqrt_heap on exactly the same input? Good thing you doubled the speed, or else this 2x slowdown would be noticeable. :)

**Comment by wbhart** [comment]
If you want to compute that, just call sqrt_heap once. That is exactly what it does, which is why I wrote it that way.

This PR isn't for fixing the square root interface, but for implementing the square root functionality in the first place.

**Comment by tthsqe12** [comment]
Yeah, I got that. By the way, what is the problem with char 2?

**Comment by wbhart** [comment]
In both the univariate and multivariate cases we divide by 2q_n.

**Comment by wbhart** [comment]
I'm finished with this PR.

**Pull request merged**
