### PR TITLE
Use derivative to cut down number of allocations.

### PR DESCRIPTION
**Pull request by wbhart**
Speeds up relative and absolute series generic exp over rings by:

* computing derivative once to avoid allocations
* using delayed reduction (where available)

Note that this may be breaking, as fit! is not available for Nemo polynomial rings and derivative uses it. I will make a PR to fix this soon.

### CODE REVIEW

**Comment by wbhart** [comment]
See https://github.com/Nemocas/AbstractAlgebra.jl/issues/810 for discussion

**Comment by wbhart** [comment]
Indeed this will break more stuff until https://github.com/Nemocas/Nemo.jl/pull/1029 is merged. Of course that stuff is already broken as it is.

**Comment by thofma** [comment]
Doctests seem to be failing.

**Comment by wbhart** [comment]
OK, I will look.

**Comment by wbhart** [comment]
But note the docs were not touched in this PR.

**Comment by wbhart** [comment]
Nevermind, I see the doctest example is now giving the wrong answer.

**Comment by wbhart** [comment]
Yeah that was a serious bug I had introduced. I'm glad the doctest caught it. I added the doctest example as a test example.

Probably we should not restrict log to series over fields. It probably works just fine over any ring where elements are divisible by integers. Then we could strengthen the tests for exp over exact rings. This wasn't a problem before because we didn't have separate code for exp over a field.

**Comment by wbhart** [comment]
@thofma I think this is ok to merge now.

**Pull request merged**
