### PR TITLE
fix addmul! documentation

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wbhart** [comment]
I'm not even sure the addmul!(a::T, b::T, c::T) should exist. It's not usually possible to implement without allocations.

**Comment by tthsqe12** [comment]
So, only the four arg version?

**Comment by wbhart** [comment]
It's the only thing defined in Rings.jl. Interestingly it is not defined for NCRingElem at all so far as I see.

**Comment by thofma** [comment]
I thought there is a fallback from 3 arguments to 4 arguments (by allocating one more element)?

**Comment by wbhart** [comment]
Maybe, but where is it defined?

**Comment by wbhart** [comment]
Actually NCRingElement is fine. We do define them separately for a few of those. Maybe we should move the generic addmul! into NCRings.jl though.

**Comment by thofma** [comment]
My bad, it exists for some types.

**Pull request merged**
