### PR TITLE
add function "ishomogeneous"

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by wbhart** [comment]
This implementation would be very slow in the case that the polynomial is not homogeneous, as it would still go through summing every exponent vector. I'd prefer a version which stops if it encounters a term which has a different sum. But other than this, everything looks fine.

**Comment by wbhart** [comment]
Oh, except that the docstring needs to be used somewhere in mpolynomial.md.

**Comment by wbhart** [comment]
By the way, doing what I suggest efficiently won't be easy. The length function already goes through all the terms, so to do things efficiently, you only want to use the iszero function, not length. But then you have the problem of getting the sum of the degrees of the first term before checking the others. I leave this as an exercise in working with Julia iterators.

**Comment by sebasguts** [comment]
This assumes that every polynomial is graded via the standard grading. Do we really want to restrict ourselves to this assumption? I would prefer to have rings (and then modules) explicitly graded, and restricting the question if a polynomial is homogeneous to polynomials that actually live in a graded ring.

This way, we could equip rings with several gradings, also non-standard ones, which is necessary for all kinds of geometric computations.

**Comment by heiderich** [comment]
@wbhart I think I addressed your concers in 5fb07c7 and 5a84090.
@sebasguts Yes, this seems to be a good idea. I still pushed my changes anyway, since I had them ready before I saw your comment.

**Comment by thofma** [comment]
I think we need both.

It would be quite cumbersome to first create a new polynomial ring if I want to test if something is homogeneous with respect to the standard grading. Also, the function here can easily extended to handle also other gradings.

**Comment by heiderich** [comment]
@sebasguts What do you imagine concretely? What should be the index set for the grading? The integers? The non-negative integers? Any monoid? Whay types to you imagine for the graded rings / modules then?

**Comment by wbhart** [comment]
@sebasguts If AbstractAlgebra ever implements weighted orderings, we will have to write a version of this function that handles weighted orderings. But that is true of many functions. Until then, we only have to handle the orderings we actually support. Singular.jl will have to handle more, of course.

**Comment by sebasguts** [comment]
This is not really about monomial orderings, this is about degrees.

Currently, AbstractAlebra does not support weighted rights or weighted modules, or whatever. This function assumes that a non-graded ring has (implicitly) the standard grading. That would be fine, but we should then also consider every ring a graded ring.

Last week, we briefly discussed about graded rings, wether graded rings should be non-graded rings with a grading or every ring should be graded, and non-graded rings should be graded rings with the trivial grading. By adding this function, every ring is in principle equipped with the standard grading, which is a third case. IMHO, I would at least call this function
`ishomogeneous_if_the_ring_would_be_graded_with_the_standard_grading` cause this is what it does.

Anyway, I think grading with every finitely presented abelian group should be possible (and is necessary for toric geometry for example).

**Comment by wbhart** [comment]
At the moment we don't really have gradings in AbstractAlgebra. You might not want every ring to have a grading, for performance reasons. So graded rings should probably be specialised types. Even if we had such rings though, I am not knowledgeable about how the ring grading affects homogeneity of polynomials over that ring. Perhaps someone can provide a link where I can read about that.

Having said that, there don't seem to be many options here. Either we have gradings and the function should take that into account when trying to work out whether a polynomial is homogeneous or not, or the function will need additional data passed to it, which would mean it's a different function due to having a different prototype. I don't see any conflict in either case with the very simple function here (except perhaps the documentation will need changing).

I'm certainly not in favour of adding functions such as ishomogeneous_with_bells_and_whistles_and_knobs_for_some_special_application. Functionality should be composable, to get the desired functionality. For example, we are already starting to include functions like depends_on_more_than_one_variable(f), even though length(vars(f)) > 1 is just as clear and less typing anyway. If performance is really needed, such a function should be specially implemented for the application. Such functions shouldn't be placed in the most general library in the system.

And the same is true for gradings. That sounds like something that should be in Singular.jl, or even Oscar.jl. The AbstractAlgebra interface only needs to be compatible with it. Renaming the function in the general library to something obscure isn't the right way to get such compatibility, in my opinion.

Anyway, the first step here is for me to understand what you would expect ishomogeneous to do differently if you had a polynomial over a graded ring? Is there an example of such functionality in Singular that I can look at? As far as I was aware, when setting up a polynomial ring in Singular, only an ordering is given. So gradings weren't even on my radar.

**Comment by wbhart** [comment]
I looked at the Singular Introduction to Commutative Algebra and they only mention graded rings in the context of polynomial rings with weighted orderings, and modules with weighted generators.

So if we follow that model, surely ishomogeneous should use the standard grading for polynomial rings that have weights of 1 (currently all polynomial rings in AbstractAlgebra), and it should respect the weights when we finally have weighted orderings in AbstractAlgebra (we are definitely considering having this). 

So currently I am not understanding the complaint here.

**Comment by wbhart** [comment]
Regarding grading rings with arbitrary finitely presented abelian groups, I don't really know what that means.

Could you sketch out how such an interface might look? Given an arbitrary ring R in the system, what series of commands would I issue to tell it which elements of the ring had which grade?

Also, we don't currently have finitely presented abelian groups in AbstractAlgebra, so I'm not even sure what it would mean.

And do I understand correctly that a polynomial would be homogeneous if every term in the polynomial had the same "degree" (as an element of this finitely presented abelian group)?

**Comment by sebasguts** [comment]
For now, I am going to talk about polynomial rings mostly, but actually this applies to any algebra.

I would think there are two distinct models here:

We can either make every ring a [graded ring](https://ncatlab.org/nlab/show/graded+algebra), so `ishomogeneous` applies to any ring element. Here we would have two choices: Either grade every ring by the trivial monoid, in which case every element is homogeneous, or grade it via the non-negative integers, which means that only certain elements are homogeneous (which is what this function currently assumes).

The second option would to make the ring non-graded. In that case terms like `degree` or `homogeneous` do not really make sense. So if you want to have those terms, your rings are always implicitly graded.

The second option is fine IMHO, the first one has implications. If your ring is graded by default, you need to distinguish between modules and graded modules over that ring. Why do you need to distinguish? Because the set of free modules over the graded version of a ring is larger than the set of free modules over its non-graded version (as you may shift the free modules). Furthermore, the homomorphism sets are very different. If you regard your homomorphisms as a matrix, for graded modules those matrices can only consist of homogeneous elements. Also, the internal homs differ in those categories, but you need them to compute invariants in affine, projective, and toric geometry. All those structures heavily depend on the grading. I suggest you have a look at https://www.singular.uni-kl.de/Manual/4-0-2/sing_2165.htm#SEC2240.

Furthermore, how do you envisage to use rings with a different grading?

I will try to sketch some interface. This is not proper Julia, but rather pseudo-code.
If we would do polynomial rings without grading, this is how we could create graded rings.
```
A = SomeAbelianGroup() #Create an abelian group
R = PolyRing(QQ,["x","y"])
weight1 = SomeElement(A)
weight2 = SomeElement(A)
S = GradedRing(R,[weight1,weight2]) # Create graded ring, deg(x) = weight1, deg(y) = weight2
```

If we would grade rings by default, this is an option
```
R = PolyRing(QQ,["x","y"]) # deg(x)=0, deg(y) =0
S = PolyRing(QQ,["x","y"],[weight1,weight2]) # Create R with the grading above
```

Also, if we decide to grade rings with the standard grading by default
```
R = PolyRing(QQ,["x","y"]) # deg(x)=1, deg(y) =1
S = PolyRing(QQ,["x","y"],[0,0]) # Create R with the trivial grading, as above
```

For a hopefully correct definition of [graded modules and their homomorphisms see here](http://therisingsea.org/notes/GradedModules.pdf). It only covers the standard graded case, but everything can be made more general very easy.

**Comment by wbhart** [comment]
Thanks for the answer, which is helpful. I think grading rings by an arbitrary monoid is not really possible, as it is not supported in Singular, as far as I know. I think the only thing we can put in the interface is that grading is with a non-negative integer, as that is all that is actually possible in Singular.jl.

Singular won't allow constructing modules or ideals, etc., over more general kinds of graded (polynomial) rings from AbstractAlgebra, even if we supported them, as far as I know (correct me if I'm wrong).

Also, to me it seems like ishomogeneous has a well-defined meaning for polynomials where a grading has not been specified. Not everyone is doing toric geometry, and ishomogeneous certainly has other uses. So I think we should think about how to make the currently proposed function consistent with an interface that also allows for graded rings and modules.

But I need to think about this statement, "the set of free modules over the graded version of a ring is larger than the set of free modules over its non-graded version (as you may shift the free modules)" as it seems quite unexpected to me. I have never seen a textbook take grading into account when defining free modules, and polynomials are always given a degree. So either there are a lot of incorrect textbooks out there, or I'm missing something.

**Comment by wbhart** [comment]
Yeah I am not convinced about your statement about there being more free modules over a graded ring than its non-graded counterpart. This has to be false, since the definition of a module does not take grading into account. I could accept that there were more *graded* free modules over a ring with a nontrivial grading, as opposed to the same ring with the trivial grading.

I propose we (implicitly) equip polynomial rings with the standard grading by default. I think all other rings should (implicitly) have the trivial grading by default, though I doubt this will be relevant unless you are defining graded modules, which obviously have to be done differently to modules. I don't think it is important to define ishomogeneous or degree for all rings. But it is easy enough to define the former for all rings if needed.

This approach means we don't violate the principle of least surprise.

It's not clear to me what the relationship between Singular multigradings and the more general gradings that you are talking about, is. (See, we have parenthesis in English too.)

I'm a bit worried about putting non-integer gradings on polynomial rings as part of the interface for polynomials though. Will Gap and Polymake polynomials implement it? I doubt it.

I think this is a concept that should be limited to Singular.jl.

Oscar.jl will have to allow construction of polynomials with multigradings, whatever they are. But they will have to be imlemented behind the scenes as polynomials in that Singular library, not as AbstractAlgebra polynomials. We have no intention of duplicating all the functionality of Singular in AbstractAlgebra.

**Comment by wbhart** [comment]
I should add that I have no idea whether there are fewer morphisms of polynomial rings with the standard grading (as graded rings) than there are ordinary ring homomorphisms, because the definition is totally unclear. It simply says that morphisms of graded rings should "preserve degree", but I have absolutely no idea what that should mean. Is that automatic for the standard grading, In any case, this is a problem for category theorists. No one else cares, because they all know what they mean by a morphism of rings, and that is almost certainly what they are thinking about, whether the ring has a grading or not. You should have to construct the category of graded rings if you want to work with it. If you construct a homomorphism of polynomial rings, it should not be by default associated to the category of graded rings just because polynomial rings have an implicit grading. Again, that would violate the principal of least surprise.

**Comment by wbhart** [comment]
Just to follow up my previous remark: Wolfram has been kind enough to give me a proper definition of morphisms of Gamma-graded rings (for a group Gamma). Apparently by "preserve grading" the definition usually means that the degree is not altered by the homomorphism. However, other kinds of homomorphisms are possible, just not with the standard definition of Gamma-graded rings.

This means the morphisms of Gamma-graded polynomial rings are not the same as standard ring homomorphisms. Whilst they are (in some sense) just ordinary ring homomorphisms, they have the extra condition of preserving the grading and this is real restriction.

**Pull request merged**
