### PR TITLE
Fix Laurent series inplace multiplication

### LINKED ISSUE #229: Laurent series inplace mul incorrect
I was correcting a typo in add! and to catch it in the future added tests for inplace operations. You can check the test code I added at https://github.com/martinra/AbstractAlgebra.jl/tree/laurent_series_add . What I found was this (the results differ in the coefficient for x^-5).

`Generic.LaurentSeries.inplace_binary_ops...`
`Test Failed at ***/AbstractAlgebra.jl/test/generic/LaurentSeries-test.jl:270`
`  Expression: isequal(r, f * g)`
`  Evaluated: isequal(3*x^-12+2*x^-9+3*x^-8+2*x^-7+4*x^-6+4*x^-5+O(x^-4), 3*x^-12+2*x^-9+3*x^-8+2*x^-7+2*x^-6+2*x^-5+O(x^-4))`

When I run other instances, the error shows up for integral domains as coefficient field, so it has probably nothing to do with that.

Perhaps somebody who knows the code better than me can investigate the cause.

### PR DESCRIPTION
**Pull request by thofma**
Fix #229.

In the example of @martinra, the first argument of `mul!` had coefficients that were not zero. But the function was assuming that this is the case. Could you please double check the fix @wbhart?

I think additionially we were violating our aliasing/mutation rules. For the same reason `add!` is also wrong, right? It is not allowed to do what iit s currently doing. If you agree, I will also fix `add!`.

### CODE REVIEW

**Comment by thofma** [comment]
P.S.: @martinra I hope you don't mind if I add your two commits here. I worked on top of them.

**Comment by wbhart** [comment]
We use mul! internally in mul! in Poly.jl, however in that case we check if there is any aliasing first. So your fix will certainly work.

I'm not actually sure what you mean about the code assuming the coefficients are zero. Mul! should write into the coefficients whether they are zero or not.

Are the sz -> sc changes just cosmetic, or was that part of the bug fix.

**Comment by martinra** [comment]
@thofma I'm happy if my code is useful.

The sz -> sc is not only cosmetic. line 1423 uses sc and before the commit the function failed on some examples I used.

**Comment by thofma** [comment]
@wbhart, I think we were violating the convention for the use of Bang functions. Let me quote you from an email exchange we had:

"The rule has always been that arithmetic operations must return new objects (with new contents). There were simply some deepcopys missing in parts of the + and - functions.
It's perfectly fine for coefficients in polynomials or entries in matrices to alias one another. The rule for the unsafe operators is that they can only be used to modify objects that you control, that no one else contains a reference to (or to a part of)."

With this in mind, I also think that the line https://github.com/Nemocas/AbstractAlgebra.jl/blob/67f971d38b79bb00b0f7170d17b35cbe4c10a61f/src/generic/LaurentSeries.jl#L1426 is wrong, since we don't control the object `c.coeffs[i + 1]`. Do you agree?

**Comment by wbhart** [comment]
I don't think this is a problem. The caller of mul! controls c entirely and
c does not alias any other series object, and nor does any part of it,
including its coefficients. The caller is asking us to mutate c because it
is safe to do so. We can certainly also mutate parts of c for the same
reason, I believe.

Can you demonstrate a failure of addition where the outermost call respects
these rules?

The original bug you fixed was because c and b were aliased (presumably)
and it was trying to read from b after modifying c. Your fix works because
it stops modification of b. But the alternative which we make use of in
Poly.jl is to prevent aliasing of b and c (at the start of the function).
In fact, add! does that in the case you are looking at.

**Comment by thofma** [comment]
I do think this is a problem and the same reason why the `add!` code for matrices does not use `add!` on the entries.
https://github.com/wbhart/AbstractAlgebra.jl/blob/f3bd4b3ab7576da984d3a016a1bf74cc1598ee1e/src/generic/MatrixAlgebra.jl#L451-L460
You are only allowed to change where `c.coeffs[i]` points to but not the memory that it currently points to.
```julia
julia> R, x = LaurentSeriesRing(ZZ, 10, 'x')
(Laurent series ring in x over Integers, x+O(x^11))

julia> a = BigInt(1)
1

julia> g = R([a, a, a], 3, 100, 2, 2)
x^2+x^4+x^6+O(x^100)

julia> f = R(BigInt[1, 2, 3], 3, 100, 2, 2)
x^2+2*x^4+3*x^6+O(x^100)

julia> add!(g, f, f)
6*x^2+6*x^4+6*x^6+O(x^100)

julia> g
6*x^2+6*x^4+6*x^6+O(x^100)
```
The entries of `g` do not alias any entry of `f`.

**Comment by wbhart** [comment]
In this example, the coefficients of g alias one another before calling mul!. If you do the following it will work:

g = R([a, deepcopy(a), deepcopy(a)], 3, 100, 2, 2)

Admittedly this is a case that is not covered by what I wrote in that email you quoted. I should add to it that aliasing can't exist inside the object you claim to control.

The thing is, if you can't use the mutating operators recursively, then the cost will be a lot higher. I'm fairly sure we do this all over the place. See for example Poly.jl, which we know is correct.

**Comment by thofma** [comment]
OK. Is this written down somewhere? I have the feeling that everytime I ask, the rules have changed slightly.

And what about the matrix code?

**Pull request merged**
