### PR TITLE
Bump to 0.22

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by tthsqe12** [comment]
I do not approve yet. We missed derivative for laurent poly.

**Comment by thofma** [comment]
Do you plan to add it?

**Comment by tthsqe12** [comment]
Yeah, just give me a couple of hours.

**Comment by thofma** [comment]
Good to go @tthsqe12?

**Comment by tthsqe12** [comment]
This is fine

**Review by tthsqe12 — APPROVED** [review]

**Pull request merged**
