### PR TITLE
Replace == 0 by iszero in MPoly code

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by tthsqe12** [comment]
is 0 the wrong zero?

**Comment by thofma** [comment]
Yes. It is a costly zero.

**Comment by YueRen** [comment]
Just for context: the error arose when working with tropical numbers, where addition is min and multiplication is max. So the integer 0 is not neutral element w.r.t. addition and the integer 1 is not the neutral element w.r.t. multiplication.

**Review by tthsqe12 — APPROVED** [review]
of course this is fine

**Pull request merged**
