### PR TITLE
Matrix algebra

### PR DESCRIPTION
**Pull request by wbhart**
Adds NCRing abstract type, MatrixAlgebra, tests and docs.

Currently you can't build anything over this ring, as we don't have polynomials over noncommutative rings, etc. That will have to come next, I guess.

### CODE REVIEW

**Comment by wbhart** [comment]
This might break Nemo. I will check that before this is merged.

**Comment by wbhart** [comment]
Nemo does break for me, and even in matrix code. But I don't see why.

I create a matrix A over the integers and type A^-1 and it says "Matrix not invertible". But the traceback suggests it has used some generic Julia function for powering by a Val{-1}. However, when I do @which A^-1 it says it is calling the correct Nemo function. So something appears to be broken here in the deep magic. Any ideas?

**Comment by wbhart** [comment]
```
julia> using Nemo

julia> S = MatrixSpace(FlintZZ, 3, 3)
Matrix Space of 3 rows and 3 columns over Integer Ring

julia> A = S([fmpz(2) 3 5; 1 4 7; 9 6 3])
[2 3 5]
[1 4 7]
[9 6 3]

julia> A^-1
ERROR: Matrix not invertible
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] inv(::fmpz_mat) at /home/wbhart/.julia/dev/Nemo/src/flint/fmpz_mat.jl:455
 [3] macro expansion at ./none:0 [inlined]
 [4] literal_pow(::typeof(^), ::fmpz_mat, ::Val{-1}) at ./none:0
 [5] top-level scope at none:0

julia> @which A^-1
^(x::fmpz_mat, y::Int64) in Nemo at /home/wbhart/.julia/dev/Nemo/src/flint/fmpz_mat.jl:389
```

**Comment by wbhart** [comment]
I've always called it dimension. But I don't find an authority for that.

Happy to change it. Do you have any suggestions?

**Comment by wbhart** [comment]
Magma calls it degree, I think. Is that acceptable?

**Comment by wbhart** [comment]
Though I can't find an authority for that either.

**Comment by thofma** [comment]
Degree sounds fine. Regarding the powering error, I remember that I fixed this for ring elements in `src/Rings.jl` of AbstractAlgebra. Maybe one has to adjust the signature to include the noncommutative ring elements.

**Comment by wbhart** [comment]
Yeah, it looks like dimension is used by Magma for something else. So I'll switch it to degree.

**Comment by thofma** [comment]
I think dimension is used for the dimension as defined in linear algebra, aka the length of a basis.

**Comment by wbhart** [comment]
Not sure. They seem to get a dimension of 6 for a 3x3 matrix.

**Comment by wbhart** [comment]
Should all be fixed now. There is also a small fix to Nemo required (PR 490 over there). It was using a generic path for ad hoc multiplication of matrices (which was slow), which no longer exists (due to the fact that arb_mat no longer belongs to RingElem). Everything should be right to go now, once Travis gives its seal of approval.

**Comment by thofma** [comment]
This looks good to me. But can you quickly tell me what is now the abstract supertype for matrices with elements of type `T`?

**Comment by wbhart** [comment]
That hasn't changed. I simply added a union between it and the matrix algebra matrices, so I didn't have to duplicate a lot of code.

**Comment by thofma** [comment]
So `MatElem` is still the correct supertype and it works for both cases, space and algebra?

So if I have code which accepts `MatElem` will it also accept elements from the matrix algebra? Or is there something to adjust?

**Comment by thofma** [comment]
I mean the abstract types.

**Comment by wbhart** [comment]
We could also move the union MatrixElem out to AbstractAlgebra not Generic, since it would make more sense to use it from AbstractAlgebra in Nemo, etc. But I'm not sure if it will actually be needed in Nemo. It's really only used for generic algorithms. Nemo types will have to belong to the supertype for either matrix spaces or matrix algebras and not both.

**Comment by thofma** [comment]
OK, to make it more concrete. I want to write code which accepts `Generic.MatAlgElem{fmpq}` and `fmpq_mat`. What is the correct signature?

**Comment by wbhart** [comment]
Use Generic.MatrixElem. That should cover both. (Of course it includes a lot of extra things as well, but if you want just those types you'll have to write your own union. There is already no type that gives you generic matrices over fmpq and fmpq_mat's.)

**Comment by thofma** [comment]
I don't understand. There is a supertype for `fmpq_mat` and `Generic.Mat{fmpq}`:
```
julia> fmpq_mat <: AbstractAlgebra.MatElem{fmpq}
true
julia> Generic.Mat{fmpq} <: AbstractAlgebra.MatElem{fmpq}
true
```
I thought this was the point of having the abstract super types.

**Comment by wbhart** [comment]
To answer your previous question, nothing has changed with AbstractAlgebra.MatElem. It still only covers matrices from matrix spaces. If you want to cover both matrices from matrix spaces and matrix algebras, you have to use the new union Generic.MatrixElem. Note, Generic.MatrixElem is a union of two abstract types, it's not a new generic type.

As I said, we could move its definition out of Generic, so that it's AbstractAlgebra.MatrixElem, but it is only ever going to be used in Generic anyway, so I don't really see the point, especially since we would then have to prepend AbstractAlgebra in front of every use of it in Generic. If you think this will be too confusing, I can change it. It's just less convenient than what we have, I think.

**Comment by thofma** [comment]
Sorry, there was some confusion. I did not mean exclusively fmpq_mat and Generic.Mat{fmpq}. I understand now.

**Comment by wbhart** [comment]
Yes, you are right, you can use AbstractAlgebra.MatElem{fmpq}, I forgot about that. There is also AbstractAlgebra.MatAlgElem{fmpq} and in fact you can also do Generic.MatrixElem{fmpq}.

```
julia> f(x::Generic.MatrixElem{BigInt}) = 1
f (generic function with 1 method)

julia> A = matrix(ZZ, 3, 3, [1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 2 3]
[4 5 6]
[7 8 9]

julia> f(A)
1
```

**Pull request merged**
