### PR TITLE
Move interfaces out to separate interfaces section

### LINKED ISSUE #918: Move interface sections of documentation out to separate interface section
Some of the information will have to be duplicated/summarised in the relevant sections, but the interface sections are really designed for developers looking to make use of AbstractAlgebra interfaces, not users.

### PR DESCRIPTION
**Pull request by wbhart**
Still to do:

- [X] Move existing interface documentation to an Interfaces chapter
- [x] Replace original sections of the docs with new sections summarising the "required" functionality
- [x] Update dead links in AbstractAlgebra.jl
- [x] Update dead links in Nemo.jl
- [X] Update dead links in Singular.jl
- [x] Make Oscar.jl slurp in the right doc files

Fixes #918 

This is a first attempt at separating the interfaces sections into their own chapter of the manual. It tries to do three things:

* Document our (simplified) random generation.
* Move the interfaces sections into a separate chapter
* Replace them with user documentation that covers all the functionality described in the relevant interface docs.

Where possible, the latter has been added to the existing pages so that users don't have to go searching through multiple pages to find what they are looking for.

As I've done this task, I've started to have ideas about what might be the next steps, in later PR's, to reduce duplication as much as possible:

* Move all examples from the interface docs into the user docs and deduplicate. Remove the existing examples entirely from the interface docs. 
* Make sure all functions that are intended for the user are fully described in the user docs (I've done much of this in this PR, but there may still be cases I've missed, e.g. I probably should have considered deep_copy user facing).
* Add an example section to the Interfaces chapter, which shows how to do a minimal implementation of an AbstractAlgebra ring following the Ring Interface.
* Reduce the interface sections to lists of functions only and retain only comments which are relevant to the implementer, such as *how* the functions should be implemented, rather than *what* they should do, for which the implementer should refer to the relevant sections in the user docs.

If this is uncontroversial I will make tickets for these things.

### CODE REVIEW

**Comment by thofma** [comment]
Is it breaking because other documentations point to the latest dev version and not the latest stable version?

**Comment by wbhart** [comment]
Yep, that's why.

**Comment by thofma** [comment]
Hm, yeah, I guess there is nothing we can do. Even if we make a breaking release, the other documentations will still point to the wrong thing. I guess the only thing we can do is try to minimize the time between merging the PRs.

**Comment by tthsqe12** [comment]
So what is the schedule for this synchronized merge?

**Comment by thofma** [comment]
We should merge all those breaking PR in the near future and then do the dance.

Maybe we want to wait for the `divexact/root` things @wbhart is working on.

**Pull request merged**
