### PR TITLE
Delayed reduction

### PR DESCRIPTION
**Pull request by wbhart**
This causes some functions to use delayed reduction over number fields in Nemo. It doesn't affect anything in AbstractAlgebra itself.

Unfortunately, many of the remaining functions (especially in Poly.jl) will need rewriting entirely to benefit from this trick. However, the trick speeds things up dramatically in MPoly.jl where accumulation is done per output coefficient, rather than in a double loop over input coefficients.

But I will add tickets to do this at some later date.

### CODE REVIEW

**Comment by wbhart** [comment]
Hold off merging this for a bit. I will try to apply the reduction idea to Poly as well by reducing all the coefficients at the end.

**Comment by wbhart** [comment]
This is ready to go.

**Comment by thofma** [comment]
There is no way to test this here, right?

**Comment by wbhart** [comment]
Really needs to be tested in Nemo. It could in theory be done here by implementing a ring with delayed reduction. But as Claus says, we may as well test it using something we actually want to use (number fields).

I did define a number field in Nemo and do some operations to check it wasn't complete rubbish. But yes, it needs decent test code.

**Pull request merged**
