### PR TITLE
powmod -> powermod (addresses Nemo # 988)

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by wbhart** [comment]
I believe I've updated this in Nemo, Hecke and Oscar. Apparently Singular.jl doesn't use powmod.

**Comment by thofma** [comment]
Can you add a deprecation? Then we can make it non-breaking.

**Comment by wbhart** [comment]
Yes, I'll add it tonight.

**Comment by wbhart** [comment]
I've added a deprecation, I think. Please check that I did it correctly, as this mechanism is new to me.

It does seem to work (without warning).

**Comment by thofma** [comment]
Thanks, looks good. The deprecation warnings are turned off by default (though they are always turned on when running tests as this uses julia --depwarn=yes).

**Comment by fingolfin** [comment]
So what's the hold up / what's the plan? Shouldn't this be merged, and a new AA release be made immediately afterwards, so that we can progress with the other PRs?!

**Comment by fingolfin** [comment]
Can we now make a release of AA with this change?

**Comment by thofma** [comment]
I am waiting for a decision here #767.

**Comment by wbhart** [comment]
You mean for the release; it's not tied to this ticket right?

**Comment by thofma** [comment]
Yes, for the release I mean.

**Pull request merged**
