### PR TITLE
Add characteristic 2 sqrt in LaurentSeries and square root functions for PuiseuxSeries

### PR DESCRIPTION
**Pull request by wbhart**
* Deal with characteristic 2 in LaurentSeries square root/issquare functions
* Add square root/issquare functions for PuiseuxSeries
* Deal with characteristic 2 in PuiseuxSeries square root/isssquare functions

### CODE REVIEW

**Comment by thofma** [comment]
There are some errors.

**Comment by wbhart** [comment]
Probably typos after I manually tested locally. I will fix.

**Comment by wbhart** [comment]
I give up. Codecov is off its head.

**Comment by thofma** [comment]
It says 100%. How you much do you want?

**Comment by wbhart** [comment]
For me it says 84.13% which is down from 84.15%, and it shows up as a failing test in the matrix. Pretty useless IMHO.

**Comment by thofma** [comment]
I only look at `The diff coverage is 100.00%.` in the second line, since the rest is indeed confusing! It might be related to the fact that we have randomized tests.

**Review by tthsqe12 — APPROVED** [review]
This is fine.

**Pull request merged**
