### PR TITLE
Add minimal Ring Interface example

### LINKED ISSUE #934: Document minimal example of a ring in Interfaces
People who want to implement their first ring satisfying the AbstractAlgebra Ring Interface have asked for a minimal example that they can cut and paste from.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #934

### CODE REVIEW

**Comment by thofma** [comment]
Would be great if for the printing it would implement `expressify`.

**Comment by wbhart** [comment]
Could I ask @tthsqe12 to add this, perhaps after this is merged. He is the real expert on doing this properly and there's no sense putting something incorrect or incomplete in the documentation which is meant for users.

**Comment by thofma** [comment]
I will merge this. At some point we should turn this into something that gets executed/tested.

**Comment by wbhart** [comment]
Agreed. I tried to do that myself, but each and every possibility turned out to be a disaster.

If we put it in the test code, we have to maintain in two places. Put it in a @jldoctest section and it just looks horribly messy compared to what we currently have. I tried both and pulled it back out for now until we decide how to do it nicely. We can't just put it in a file and test it or no one will read it.

**Comment by wbhart** [comment]
I did test by hand though.

**Pull request merged**
