### PR TITLE
add Matrix tests for multiplication by permutations

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by wbhart** [comment]
Seems to cause test failures. Could you possibly look into why. Ignore all the failed builds with an exclamation mark, just look at the ones with an X.

**Comment by rfourquet** [comment]
> Seems to cause test failures

Ah yes thanks for checking, this was due to a last second change beforfe pushing.

**Comment by rfourquet** [comment]
More errors, some of them will be automatically fixed if #504 is merged.

**Comment by wbhart** [comment]
The Julia 1.2 errors seem to be real, so I don't think we should merge this yet until we understand why they are happening. Are they using == instead of isapprox?

**Comment by rfourquet** [comment]
Yeah some errors look definitely real. I didn't investigate too closely, but something seems to have changed in some Julia versions in how `reduce(vcat, ...)` is handled. That's why I think #496 would solve the problem. If not, or if that PR doesn't get merged, I will look into changing the tests to make them pass.

**Comment by rfourquet** [comment]
> That's why I think #496 would solve the problem

Actually I think it will not, I will fix the problem here.

**Pull request merged**
