### PR TITLE
Remove duplicate Map documentation

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by thofma** [comment]
I guess this is fine. @wbhart any objections?

**Comment by wbhart** [comment]
I don't think this is an improvement from the user's perspective. But it makes it easier to maintain. So I will let someone else decide this.

**Comment by fingolfin** [comment]
As a user, I do think it is an improvement:
- I never noticed that these docs exist twice, I only knew about the incomplete version (which this PR deletes)
- the user now gets a link inside the "Maps" chapter pointing them at the complete Maps interface documentation which is in a separate chapter and thus might be overlooked

**Comment by fingolfin** [comment]
@fieker @thofma merge this before it bitrots? Then we can do it with other parts

**Pull request merged**
