### PR TITLE
Invariant factor decomposition

### PR DESCRIPTION
**Pull request by wbhart**
* Adds InvariantFactorDecomposition of a module
* Adds invariant_factors of a module
* Fixes some DomainErrors in Matrix.jl
* Adds isisomorphic for modules
* Adds more test cases

### CODE REVIEW

**Comment by wbhart** [comment]
The same issue occurs with nightlies as before. @thofma did you commit your changes? Or are we just waiting for the Julia guys to fix the problem?

**Comment by thofma** [comment]
I commited my changes, but they only changed this specific test. I think we would have to work around it here in the same way. I would not count on the julia people fixing it anytime soon (unless we find a small reproducing example).

**Comment by wbhart** [comment]
Did you report it at all?

**Comment by thofma** [comment]
I am currently trying to reduce it to a smaller example.

**Pull request merged**
