### PR TITLE
print 1 in the correct ring

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
I don't believe this patch is correct. It is in the section !show_minus_one, which means we do NOT want to show the ring value, but instead -1 (as the constant term).

Could you provide some code which demonstrates what you were trying to fix?

**Comment by wbhart** [comment]
I suppose it is broken for Z/1Z and is harmless otherwise.

**Comment by fieker** [comment]
On Wed, May 06, 2020 at 09:24:41AM -0700, wbhart wrote:
> I don't believe this patch is correct. It is in the section !show_minus_one, which means we do NOT want to show the ring value, but instead -1 (as the constant term).
> 
> Could you provide some code which demonstrates what you were trying to fix?
No, I can't but  can construct. But the point is
suppose you have a ring where
julia> one(R)
i^0
for whatever reason
now
julia> -one(R)
i^2

there is no reason to believe, think matrix algebra, that -1 or 1 prints
like -1 or 1.
> 
 was trying
 R = matrix_algebra(QQ, 1)
 Rx, x = PolynomialRing(R)

to get an example, but there seems to be trivia missing, but in Rx, I
expect to see
x-[1] or x + [-1], but never x-1

**Comment by wbhart** [comment]
In those rings you would set show_minus_one to true and this code would never be called.

But let's merge this and see if any damage is done.

**Comment by fieker** [comment]
On Thu, May 07, 2020 at 12:06:59AM -0700, wbhart wrote:
> In those rings you would set show_minus_one to true and this code would never be called.
> 
> But let's merge this and see if any damage is done.
> 
Sorry - you're right, but there won't be damage either.

**Pull request merged**
