### PR TITLE
Add isunit() for matrices and module homomorphisms.

### PR DESCRIPTION
**Pull request by hwjsnc**
The implementation for MatrixElem follows that for MatAlgElem.

If there's any problem with this patch, feel free to suggest or make edits, or disregard it entirely.

### CODE REVIEW

**Comment by wbhart** [comment]
Well, mxn matrices don't form a ring. So what is it a unit of?

**Comment by hwjsnc** [comment]
It doesn't make sense if n≠m of course. It could still be useful in the case n=m in my opinion. If you'd rather people use the matrix algebra types for that, I can edit the patch so that it only overloads isunit() for the linear homorphisms.

**Comment by wbhart** [comment]
The point is, it doesn't make sense for matrix spaces, even if n = m. It's not a ring mathematically, as an algebraic object. Yes it can be made into one, but that's what MatrixAlgebra's exist for.

As for homomorphisms, again we don't have a ring, so you are asking for whether something is a unit in something that isn't a ring mathematically. I don't personally see why that is useful.

I could understand asking if a homomorphism is invertible, and similarly for matrices.

**Comment by hwjsnc** [comment]
Point taken.

Indeed, my primary motivation is to see if a matrix is invertible / a homomorphism is an isomorphism.

**Pull request closed without merging**
