### PR TITLE
Fix bug in mpoly factorization

### PR DESCRIPTION
**Pull request by thofma**
Introduced in #1322 (cc: @fingolfin). I will add an upstream test once it is merged.

### CODE REVIEW

**Comment by fingolfin** [comment]
What is the actual bug, though?

The code being changed seems fine? Though I guess there could be an issue with downstream code which needs to be adapted? What am I missing?

**Comment by thofma** [comment]
https://github.com/thofma/Hecke.jl/actions/runs/4712624721/jobs/8357785881

**Comment by thofma** [comment]
One cannot use a ring element as the second argument of `polynomial_ring`.

**Comment by fingolfin** [comment]
Ahhh of course. Somehow I kept reading `gen` as `var`.

Can't we also add a test for this here?

**Comment by thofma** [comment]
No, unfortunately not.

**Pull request merged**
