### PR TITLE
change matrix API to matrix(array, ring, nrows, ncols)

### PR DESCRIPTION
**Pull request by rfourquet**
This is to make the order of arguments consistent with that
of similar and zero.

### CODE REVIEW

**Comment by wbhart** [comment]
Why would the array come first? I thought the convention was that the ring would come first, since it is like a type?

**Comment by rfourquet** [comment]
> I thought the convention was that the ring would come first, since it is like a type?

Yes, I agree that in this case there are conflicting point of vues. But 1) I find it important to have different functions with exactly the same arguments to have them in the same order (and `similar`'s argument order comes from `Base`), and 2), the Julia style guide mentions:

> Passing a type typically means that the output will have the given type

This is not the case here, the resulting matrix won't have the type passed as argument (or belong to the `Ring`), so it looks like this rule doesn't apply so strongly.

**Comment by wbhart** [comment]
I am going to have a terrible time remembering this.

My background is C where the convention is always that anything related to the output is on the left and anything related to the input comes next, with any options, flags, modifiers, optional arguments, etc. on the right.

These Julia conventions seem to have neither rhyme nor reason.

**Comment by wbhart** [comment]
What is the justification for putting the array argument first, anyway? I realise it matches the Julia similar function (not that I knew this already), but what is their justification?

**Comment by wbhart** [comment]
Actually, I don't see any Julia version of similar that requires the array to come before the ring (type).

Instead they seem to use optional keyword arguments. I would argue that if we are going to make this change to similar and to matrix, that we at least do it the same way, with an optional keyword argument.

```
similar(array, [element_type=eltype(array)], [dims=size(array)])
```

So for us that should be:

```
similar(a::MatrixElem, [base_ring=base_ring(a)], [dims=size(a)])
```

**Comment by thofma** [comment]
I don't see any point of changing this.

**Comment by rfourquet** [comment]
In `similar(array, [element_type=eltype(array)], [dims=size(array)])`, there are no keywords arguments, it may look like it because of an unresolved standard way to document optional argument with a default. This signature is exactly consistent with our current methods for `similar`: the array/matrix comes first, followed optionally by the eltype/base_ring, followed optionally by the dimensions.

> What is the justification for putting the array argument first, anyway?

I'm not sure. I would guess that the array is the only non-optional argument and the most important one, so is put in first position. So it reads naturally as "give me something `similar` to the matrix `mat`, (optionally with this `element_type` and `dims`)". Also the `element_type`, as I said above, albeit a type argument, does not refer to the type of the output (although it determines it).

**Comment by rfourquet** [comment]
> I don't see any point of changing this.

I think I gave a strong argument in favor: two functions which take the same kind of arguments, and return a matrix. But they currently take the arguments in a different order. This is a wart of the API that would be better fixed before a commitment to less breaking changes (e.g. `AbstractAlgebra` version 1). Unless of course if there is a strong argument for the status quo, but I fail to see any (except that it's breaking, but we are in a breaking phase).

If these function didn't exist yet, wouldn't you try to make them consistent?

**Comment by wbhart** [comment]
Ok, then we should also make sure the arguments to matrix are optional, since that seems to be the reason for the utterly bizarre order in Julia.

Could we also please post to the nemo-devel list with all breaking changes, after we do the release, so that people can easily have a way to look up what we've broken.

**Comment by thofma** [comment]
I don't see any strong argument. Types go first. You just told us that in the other thread and we agreed after consulting the documentation. We just made this adjustment everywhere else, e.g. change_base_ring.

Sorry, but I don't see the necessity of making this change. Feels like picking conventions arbitrarily.

**Comment by rfourquet** [comment]
> Ok, then we should also make sure the arguments to matrix are optional, since that seems to be the reason for the utterly bizarre order in Julia.

I had similar things in mind, in line with #437. For the `ring` argument to be optional, as a first step I propose to require that the passed array must be `AbstractArray{<:RingElem}` or `AbstractArray{BigInt}` so that we can infer the ring unambiguously. But this can be discussed in a separate PR.

> we also please post to the nemo-devel list with all breaking changes

I asked somewhere else whether we should have a file, like NEWS.md, to report breaking changes to downstream users. It could be in addition to nemo-devel, as `Nemo` is not the only package depending on AbstractAlgebra.

**Comment by wbhart** [comment]
We can also post it on oscar-dev, though at the moment there are more likely to be people on nemo-devel that care about this. Oscar mostly doesn't exist or mostly doesn't depend on what we did in AbstractAlgebra. But we should let them know anyway, just in case.

**Comment by thofma** [comment]
Let me reiterate that this change here is not going to happen.

**Comment by rfourquet** [comment]
> Let me reiterate that this change here is not going to happen.

OK it was not clear yet, you had voiced your opposition, not exressed your veto on this change. 

I understand that it can be seen as code churn, and would have of course offered to propagate the change to other packages. `matrix` may be used a lot in e.g. `Hecke` or `Nemo`, but it's still fast to change.

 > Feels like picking conventions arbitrarily.

I proposed this change because I felt obviously differently. Following a style guide is less important than internal consistency. So even if one interpretation of the guideline suggests types should go first, whatever choice is made, 2 functions taking basically the same kind of arguments, and returning the same kind of thing, should have their arguments in the same order. Doing otherwise is just a disservice to all future oscar users.

**Comment by wbhart** [comment]
I'm ok with changing code that uses Julia function names to be consistent with usage in Julia. But it's not ok to also change our own conventions to align things with some perceived set of arbitrary rules. That process will never converge as there will always be some perceived violation of some rule.

The rule, "two functions taking basically the same kind of arguments, and returning the same kind of thing, should have their arguments in the same order" is too open to individual interpretation and is not enforceable. It will simply lead to arguments about what constitutes "basically the same kind of arguments".

matrix is the way we construct matrices. similar exists for the benefit of Julia users. One should not be informed by the other. Otherwise, before long every type of object we construct will have its prototype changed because it is "similar to" some other case, and before long, the way Nemo has always worked will be completely different, which will be a massive disservice to all Nemo users.

**Pull request closed without merging**
