### PR TITLE
solve_fflu -> can_solve_with_solution_fflu + non-square/singular cases.

### PR DESCRIPTION
**Pull request by wbhart**
This changes solve_fflu to can_solve_with_solution_fflu.

The function also now supports non-square matrices and singular matrices.

I've also added test code for it, as it is quite complex.

I don't know if the algorithm is published or not. 

solve_lu, solve_ff should be easy to derive from can_solve_with_solution_fflu and I will work on these next. They will follow in a later PR.

I have not added can_solve_with_solution_fflu as a special case for solve at this stage. That will come in a later PR.

Of course the generic code will no longer call solve_fflu in Nemo. That will have to be changed to the new interface separately. That will require changes to Flint.

### CODE REVIEW

**Comment by wbhart** [comment]
Note that solve_fflu was not exported or in the official interface, therefore I have not marked this change as breaking. It's only used internally in pseudo_inv, solve_ff and solve_rational.

**Comment by wbhart** [comment]
I don't think the test failure is anything to do with me.

**Comment by thofma** [comment]
Great, thanks! There was no docstring before, but would you mind adding a short sentence on what this does or what it guarantees to return? I am also happy with a code comment, if we don't want to put a docstring.

**Comment by wbhart** [comment]
Sure. I'd prefer not to document the function at this point. It's not so clear if the interface might change again, and it really isn't meant to be user facing. But I will add some code comments.

**Pull request merged**
