### PR TITLE
feat: add broadcasting for MatElem

### PR DESCRIPTION
**Pull request by thofma**
Probably still a bit rough around the edges. Let's see how it fares in practice.

### CODE REVIEW

**Comment by thofma** [comment]
First have to fix the improper use in Singular.jl, see https://github.com/oscar-system/Singular.jl/pull/745.

This makes this here probably breaking.

**Comment by lgoettgens** [comment]
One of the more severe breakages is something like the following, where the output cannot be represented by a `MatElem`:
```julia
julia> A = ZZ[1 2; 3 4]
[1   2]
[3   4]

julia> string.(A)
ERROR: MethodError: no method matching parent(::String)

Closest candidates are:
  parent(::LinearAlgebra.UpperHessenberg)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/share/julia/stdlib/v1.10/LinearAlgebra/src/hessenberg.jl:60
  parent(::LocElem)
   @ AbstractAlgebra ~/code/julia/AbstractAlgebra.jl/src/generic/Misc/Localization.jl:124
  parent(::PermutedDimsArray)
   @ Base permuteddimsarray.jl:48
  ...

Stacktrace:
 [1] _promote_dest_func(f::typeof(string), a::Tuple{AbstractAlgebra.Generic.MatSpaceElem{BigInt}})
   @ AbstractAlgebra ~/code/julia/AbstractAlgebra.jl/src/broadcasting.jl:70
 [2] similar(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{…}, Tuple{…}, typeof(string), Tuple{…}}, ::Type{String})
   @ AbstractAlgebra ~/code/julia/AbstractAlgebra.jl/src/broadcasting.jl:124
 [3] copy
   @ Base.Broadcast ./broadcast.jl:928 [inlined]
 [4] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{…}, Nothing, typeof(string), Tuple{…}})
   @ Base.Broadcast ./broadcast.jl:903
 [5] top-level scope
   @ REPL[11]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by thofma** [comment]
We could make it return a `Matrix{String}` if we want. From the downstream tests, it seems that no one wants this functionality?

How about we merge it as is and decide later if we need it.

**Comment by lgoettgens** [comment]
> We could make it return a `Matrix{String}` if we want. From the downstream tests, it seems that no one wants this functionality?

This would then be the end of type stability. I am not opposed to this change, I just wanted to mention this.

> How about we merge it as is and decide later if we need it.

Agreed. Do you want to first get the OscarCI-matching running or fix it along the way?

**Comment by thofma** [comment]
I don't think it would not the end of type instability. The output type of `f.(A)` already depends on the typeof `f` and `A`.

**Pull request merged**
