### PR TITLE
Bump version to 0.18

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
Lets wait for #905.

**Comment by tthsqe12** [comment]
Should we be worried about something like this
https://github.com/Nemocas/AbstractAlgebra.jl/runs/2827133370?check_suite_focus=true

**Review by tthsqe12 — COMMENTED** [review]
wait - I need to figure out whose fault this is

```julia
julia> using Oscar
julia> typeof(PolynomialRing(QQ, 1)[1])
AbstractAlgebra.Generic.MPolyRing{fmpq}
```

**Comment by thofma** [comment]
Everything is fine, we just need to merge https://github.com/Nemocas/Nemo.jl/pull/1087 (after tagging 0.18) here.

**Pull request merged**
