### PR TITLE
Rename the leading_* functions

### PR DESCRIPTION
**Pull request by thofma**
Going back to good'ol `lm` and `lc` to allow more useful `leading_*` methods.

### CODE REVIEW

**Comment by tthsqe12** [comment]
Don't you have to rename all of the iterators as well?

**Comment by tthsqe12** [comment]
Halt. We are just going to avoid exporting `AA.terms` into Oscar, and have Oscar do its own things with terms. The old fast iterators will be available in oscar as `AA.terms`. No other packages need to be harmed this way.

**Comment by thofma** [comment]
I think we overload some of the functions like `leading_term` and `coefficients` also for univariate polynomials. Not exporting something does not help, because we want it to be exported.

**Comment by tthsqe12** [comment]
oops. typo. Halt again. exporting -> importing. Extending this list
https://github.com/oscar-system/Oscar.jl/blob/master/src/imports.jl#L150

**Comment by thofma** [comment]
Then the user who wants the fast version needs `AA.leading_term` instead of `leading_term`? This is just asking for trouble.

**Comment by tthsqe12** [comment]
A function named `lt` is also asking for trouble.

**Comment by thofma** [comment]
This is why we don't want to do `lt` but `leading_term_native`. You came up with that name.

Anyway, I think you are right and your proposal is a good solution. I guess you will add `Oscar.terms(x) = AA.terms(x)` as the fallback? Go ahead with the changes in Oscar.

**Comment by tthsqe12** [comment]
I am happy to take credit for the idea, but it was not mine. No, I will not be adding the fall back `Oscar.terms(x) = AA.terms(x) ` because the oscar is going to looks like
```
function terms(p::MPolyElem; ordering = default_ordering(parent(p)))
...

function terms(p::FreeAssAlgElem; ordering = default_ordering(parent(p)))
...
```
and this will overwrite any definition in AA.

**Comment by thofma** [comment]
The fallback is not for `MPolyElem`, but all the other types which have defined a `terms` function.

**Comment by tthsqe12** [comment]
Ok. Gotcha.

**Comment by thofma** [comment]
Ah, yes, `terms(x...; kw...) = AA.terms(x...; kw...)` or whatever the syntax is.

**Pull request closed without merging**
