### PR TITLE
Rename lufact -> lu, trace -> tr (Fix #138)

### LINKED ISSUE #138: More renaming
Base changed the following names:
`lufact` is now `lu` and similar for `lufact!`. And `trace` is now called `tr`. Should we follow?

### PR DESCRIPTION
**Pull request by thofma**
The import/export stuff needs to be cleaned up at some point, but I want to have a working version so that I can update Nemo.

### CODE REVIEW

**Comment by wbhart** [comment]
You've commited your .blah.swp files.

**Comment by thofma** [comment]
Yes this morning I accidentally add them. But I think here I am removing them. Can you confirm?

**Comment by wbhart** [comment]
That's not what I'm seeing. I'm seeing a bunch of modifications to add the changes for lufact to lu, etc, and I see two new files. If that is removing them, I'm not seeing it.

Did you do git rm to remove them from version control?

**Comment by thofma** [comment]
For me the two files show up as red, indicating that they are deleted. Are they showing up as green for you?

**Comment by wbhart** [comment]
Yeah, they are red for me. I guess that is confirmed then.

**Pull request merged**
