### PR TITLE
Fix incorrect reduction in powmod when exponent is 1.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes bug 10 reported on my repo (only just noticed this now).

### CODE REVIEW

**Comment by thofma** [comment]
Test error here looks real: https://travis-ci.org/Nemocas/AbstractAlgebra.jl/jobs/589981332

**Comment by wbhart** [comment]
That won't be fun to fix. It's unrelated to this PR though, as this PR should only affect printing.

**Comment by wbhart** [comment]
Oh, I see, this is quite odd indeed. I wonder if I even do any powmod's in that code. That won't be fun to track down at all!

**Comment by wbhart** [comment]
I think it might be unrelated to this PR. powmod is only used in generic for powering of Residue's, and no ResidueRing or ResidueField's are created anywhere in the Module code in generic or in its test code.

But I can't be sure of course without checking.

**Comment by thofma** [comment]
So I guess we should just merge it?

**Comment by wbhart** [comment]
I'll check shortly.

**Comment by wbhart** [comment]
I have checked and powmod is definitely not called in this test (unless it's some kind of weird corner case). I think you can go ahead and restart the tests and if they pass, just merge this. I've taken a copy of all the info I need from the bug report and will look at it now. If it is difficult to fix, I will open a ticket for it and look at it later.

**Pull request merged**
