### PR TITLE
fix #467, "docstring odditites

### LINKED ISSUE #467: Docstring oddities
I've noticed the appearance of docstrings in AbstractAlgebra (primarily in Matrix.jl) which give the return values in the prototype for the docstring. Is this actually supported by the Documenter?

In any event, I think we need uniformity, and a handful of such cases is a bad idea given that none of the other docstrings have this. We went to quite some trouble to check that the docstring matched the function prototype as much as possible (so that this could be checked automatically).

Also I note that some docstrings introduce an empty line after the prototype but before the actual docstring itself. Again, I'm not in favour of this on the grounds of uniformity.

### PR DESCRIPTION
**Pull request by rfourquet**
Thee commits (which make it easier to review, so github highlights the parts which changed)
1. align signature to 4 spaces (just one signature, the rest was fixed in a previous PR)
2. add a line between the signature and the description
3. remove `>` characters at the beginning of lines in docstrings.

I used Perl commands (included in the commit messages), so this limit the chance for human errors, but I'm not expert in regexes either... I also reviewed "manually", and this seems to have done what was expected.

### CODE REVIEW

**Comment by wbhart** [comment]
Looks like this causes the docs to stop building. See the documentation test on travis.

**Comment by fieker** [comment]
On Mon, Oct 26, 2020 at 03:15:51PM -0700, wbhart wrote:
> Looks like this causes the docs to stop building. See the documentation test on travis.

Not helpful, but looks like an error in documenter

**Comment by rfourquet** [comment]
> Not helpful, but looks like an error in documenter

Yes... I force-pushed on another PR to check if the build still passes there.

**Comment by rfourquet** [comment]
A painfully boring bisection allowed to find the problem, a `$\times $` in a docstring, documenter is not happy to have a space before the closing `$`. I'm not sure whether this is a bug in Documenter.jl (maybe it's documented?), but surely documenter could make it easier to find the problem (or did I miss an easier way to find it?)

**Comment by thofma** [comment]
The julia markdown parser is very brittle when it comes to `$`. There are is at least one open issue at the julia repository, not sure if it is related.

**Comment by rfourquet** [comment]
There is also this issue: https://github.com/JuliaDocs/Documenter.jl/issues/1020

**Pull request merged**
