### PR TITLE
function to convert MPoly to Poly

### PR DESCRIPTION
**Pull request by heiderich**
The purpose of this pull request is to coerce multivariate polynomials (MPoly) into univariate Polynomial rings, see #131. The following example illustrates its usage:

```
julia> using Nemo; K=Nemo.GF(2); R,(x,y) = PolynomialRing(K,["x","y"]); RR,xx = PolynomialRing(K,"x");

Welcome to AbstractAlgebra version 0.0.9

AbstractAlgebra comes with absolutely no warranty whatsoever


Welcome to Nemo version 0.8.5

Nemo comes with absolutely no warranty whatsoever


julia> RR(x)
x

julia> RR(y)
ERROR: The name y of the variable of y does not coincide with the name of the generator x of Univariate Polynomial Ring in x over Finite field F_2.
Stacktrace:
 [1] #call#133(::Bool, ::AbstractAlgebra.Generic.PolyRing{AbstractAlgebra.gfelem{Int64}}, ::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.gfelem{Int64}}) at /home/florian/.julia/v0.6/AbstractAlgebra/src/generic/MPoly.jl:3099
 [2] (::AbstractAlgebra.Generic.PolyRing{AbstractAlgebra.gfelem{Int64}})(::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.gfelem{Int64}}) at /home/florian/.julia/v0.6/AbstractAlgebra/src/generic/MPoly.jl:3087

julia> RR(y, check_variable_names=false)
x

julia> RR(x+y)
ERROR: Can only convert univariate polynomials of type MPoly.
Stacktrace:
 [1] #call#133(::Bool, ::AbstractAlgebra.Generic.PolyRing{AbstractAlgebra.gfelem{Int64}}, ::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.gfelem{Int64}}) at /home/florian/.julia/v0.6/AbstractAlgebra/src/generic/MPoly.jl:3088
 [2] (::AbstractAlgebra.Generic.PolyRing{AbstractAlgebra.gfelem{Int64}})(::AbstractAlgebra.Generic.MPoly{AbstractAlgebra.gfelem{Int64}}) at /home/florian/.julia/v0.6/AbstractAlgebra/src/generic/MPoly.jl:3087
```

I am not sure whether we want the variable name checking by default or not. Maybe we do need it at all.

Note that this does not work yet with the special univariate polynomial ring types from Nemo. See also https://github.com/Nemocas/Nemo.jl/pull/453.

### CODE REVIEW

**Comment by heiderich** [comment]
I believe that the failed test

https://travis-ci.org/Nemocas/AbstractAlgebra.jl/jobs/411677268

is not due to changes in this pull request, but rather due to a faulty test function. See also #133.

**Comment by wbhart** [comment]
Is it really reasonable to expect the user to define the target polynomial ring with a generator of the same name?

I think this is a case where overloading the call operator may not make any real sense.

**Comment by wbhart** [comment]
Sure. I think that to_univariate() might make more sense here. Exactly what you should have to pass, I'm not sure. But matybe just the univariate ring and the otherwise univariate poly?

**Comment by heiderich** [comment]
I changed the name to `to_univariate` and removed the check that the variable names coincide.

**Comment by wbhart** [comment]
Thanks. I'm just in the process of rewriting the MPoly module, so the timing is not brilliant, but I'll cope.

**Pull request merged**
