### PR TITLE
add some mpoly functions to poly

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Maybe add a test?

**Comment by thofma** [comment]
Oh no, this is breaking some doctests in Oscar :-( (docs with dictionaries ...)

**Comment by tthsqe12** [comment]
That doesn't make any sense.

**Comment by thofma** [comment]
The code for `homogenous_component` is using a build context as far as I remember. I restarted the tests. Can you investigate if it fails again?

**Comment by tthsqe12** [comment]
This has nothing to do with the changes here, c.f. failures in #1106. There were some doc tests added in the last 4 hours that do not work with AA master.

**Comment by tthsqe12** [comment]
BTW, I don't think you should restart the oscar tests - they take about 1 hour to run.

**Comment by thofma** [comment]
Yes, this will be the cause :(

**Pull request merged**
