### PR TITLE
feat: add residue ring/field maps

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
@lgoettgens Have you also encountered the following:
```
julia> using Revise, AbstractAlgebra

julia> R, f = residue_field(ZZ, 2)
(Residue field of integers modulo 2, Map: integers -> residue field)

julia> typeof(R)
AbstractAlgebra.Generic.EuclideanRingResidueField{BigInt}

julia> EuclideanRingResidueRing{BigInt} === AbstractAlgebra.Generic.EuclideanRingResidueRing{BigInt}
true

julia> EuclideanRingResidueRing{BigInt}
EuclideanRingResidueRing{BigInt}

julia> print(EuclideanRingResidueRing{BigInt})
EuclideanRingResidueRing{BigInt}
```
????

Is it correct, that I cannot make this type print nicely?

**Comment by lgoettgens** [comment]
I am not sure I understand the question. Is it about the `AbstractAlgebra.Generic` prefix only for one of the two types?

**Comment by lgoettgens** [comment]
I noticed that the following two lines are only in `AbstractAlgebra.jl` for EuclideanRingResidueRing and not *Field:
```julia
import .Generic: EuclideanRingResidueRing # line 658
export EuclideanRingResidueRing # line 865
```
and they are not there for things like `MPoly` or other `AbstractAlgebra.Generic.*` types.

Does this help for your question?

**Comment by lgoettgens** [comment]
Reacting to my comment above and your commit in-between: I would have rather removed the import/export shenanigans for `EuclideanRingResidueRing` instead of adding them for `EuclideanRingResidueField` as well, since for the other types in `Generic.` we don't export them as well (to keep the consistency).

Or do I remember correctly that you wanted to merge the abstract type and the concrete type for both of these? In this case I think one could argue that in this case they should no longer live inside of `Generic.` but outside and thus are allowed to be exported.

**Comment by thofma** [comment]
There is no corresponding `AbstractAlgebra.EuclideanBla` type, so there is no ambiguity when exporting them. `Generic` contains all concrete types, so I kept them there for now. I think there will eventually be no abstract type, but we can do this later.

**Review by lgoettgens — APPROVED** [review]

**Pull request merged**
