### PR TITLE
update TagBot.yml

### PR DESCRIPTION
**Pull request by rfourquet**
Cf. https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249.

Also, it seems tagbot didn't tag the last v0.11.1 release, did I miss a step? (I just invoked JuliaRegistrator [there](https://github.com/Nemocas/AbstractAlgebra.jl/commit/9ea809d7b8b2788cf11cd8cabb0d7fe707465ceb)).

### CODE REVIEW

**Comment by thofma** [comment]
The bot opened something here: https://github.com/Nemocas/AbstractAlgebra.jl/issues/676. But it did not tag anything?!

**Comment by rfourquet** [comment]
> The bot opened something here: #676. But it did not tag anything?!

I had forgotten about this issue... I was believing that TagBot opened issues only when TagBot.yml is updated like in this PR.

**Comment by thofma** [comment]
I triggered it manually, but I think it only looks at releases which are not older than 3 days. I think we might have to tag it ourselves.

**Comment by rfourquet** [comment]
It seems so. I will do it.

**Comment by rfourquet** [comment]
This is tagged now, it turned out you can trigger TagBot locally: https://github.com/JuliaRegistries/TagBot#local-usage.

**Comment by thofma** [comment]
Thanks.

**Pull request merged**
