### PR TITLE
Sqrt functions

### PR DESCRIPTION
**Pull request by wbhart**
Hopefully this implements the full complement of sqrt style functions with the interface in https://github.com/Nemocas/Nemo.jl/issues/862

Note this is breaking because the check=true argument was not a named argument previously.

### CODE REVIEW

**Comment by thofma** [comment]
Does the corresponding Nemo PR need flint 2.9 or is 2.8 sufficient?

**Comment by wbhart** [comment]
2.8 only.

**Comment by thofma** [comment]
Sorry, this needs a rebase now.

**Comment by wbhart** [comment]
Whichever of sqrt_functions and divides_functions you merge first will create a merge conflict for the other. But it's trivial for me to fix.

I think we should contact GitHub support about why you can't modify branches. It's probably from when we switched which is the main branch from my repo to Nemocas.

**Comment by thofma** [comment]
OK. Would be great if you could rebase and merge the other PR yourself.

**Pull request merged**
