### PR TITLE
Univariate polynomial residue rings

### LINKED ISSUE #629: Support residue rings of ZZ[x] with monic modulus
@thofma @fieker 

Both Magma and Sage support quotient rings of ZZ[x] by a monic modulus.

Both AbstractAlgebra and Nemo allow creation of the ring, but no operations can be performed due to mod and the like not supporting ZZ[x]. We previously decided they shouldn't, as it's not a Euclidean ring (I think; I am going to start putting decisions we make and their justification in Nemo developer documentation).

Should we allow creation of such residue rings? Should we allow mod and friends to work with ZZ[x] even though it is not Euclidean?

```
julia> R, x = PolynomialRing(ZZ, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> S = ResidueRing(R, 2x^2 + 1) # Magma rejects this as not monic, Sage rejects as not invertible leading coeff
Residue ring of Univariate Polynomial Ring in x over Integers modulo 2*x^2 + 1

julia> S = ResidueRing(R, x^2 + 1)
Residue ring of Univariate Polynomial Ring in x over Integers modulo x^2 + 1

julia> S(x)
ERROR: MethodError: no method matching mod(::AbstractAlgebra.Generic.Poly{BigInt}, ::AbstractAlgebra.Generic.Poly{BigInt})
Stacktrace:
 [1] (::AbstractAlgebra.Generic.ResRing{AbstractAlgebra.Generic.Poly{BigInt}})(::AbstractAlgebra.Generic.Poly{BigInt}) at /home/wbhart/.julia/dev/AbstractAlgebra/src/generic/Residue.jl:550
 [2] top-level scope at REPL[17]:1
```

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #629 

This could be controversial. Let me know if you want this. If so, I'll also add mod, rem, div, divrem, mulmod and powmod for Flint poly rings in Nemo so that this works with Nemo.

I've made this work simply by lifting the restriction to a field as the coefficient ring of mod, rem, divrem, div, mulmod and powmod for univariate polynomials. I didn't lift the restriction for invmod, gcdinv, gcdx, as this of course leads to incorrect results as it is not a Euclidean domain. This also means divexact is not available for residue rings of polynomial rings when not over a field (I'm not sure what it could actually do generically if I did implement that). This is the case even though divexact is part of our ring interface. (I could have it raise a not implemented error, but Julia will just as quickly tell you this.)

See what everyone thinks. If we decide we don't like this, we don't have to merge it.

I left the restriction to a field as coefficient ring in docstrings for the poly functions above so that people don't get too excited. Technically I could factor each of the functions out and have them check the leading coefficient is invertible whenever working over a ring, but I already only allow modulus with invertible leading coeff in the residue ring constructor, so it's not likely to cause too much of a problem and the code is cleaner. As far as I can tell the code won't return wrong answers in other cases. It will just raise an exception of some kind or another (e.g. inv not available over the coefficient ring).

### CODE REVIEW

**Comment by thofma** [comment]
The upstream tests revealed a bug in `RelSeries.jl` unrelated to this change here. Would be good to fix it first and then rerun the tests.

**Comment by wbhart** [comment]
Thanks. Will do.

**Comment by wbhart** [comment]
Oops, missed some. Let's try that again!

**Comment by wbhart** [comment]
I'm not sure if the new bugs showing up on the CI here are mine or to do with the GaloisGroups implementation. Could @fieker say something about this?

**Comment by thofma** [comment]
I will have a look. It seems that some function is creating `RelSeries{fmpq}` instead of `fmpq_rel_series`.

**Comment by wbhart** [comment]
Don't worry, I think it is expected because of the stuff that needs to go into Nemo

**Comment by wbhart** [comment]
I should have marked this PR as breaking, but didn't do so as I thought these were all new functions and therefore not potentially breaking anything. Somehow the GaloisGroups code used them before they were implemented by me, which is slightly concerning.

**Comment by wbhart** [comment]
Unfortunately we won't see green lights here because the other PR doesn't have a branch of the same name, since the bugs I just fixed here were actually for that branch there, since that one got merged already.

What I could do is remove those commits here, cherry-pick them back over to that branch, make a new PR based on those fixes alone, then when we see the lights green there, we should be ok (except that we'll need the Nemo PR merged before anything will go green here).

Do you want me to do that?

**Comment by thofma** [comment]
Let me have a look and then I will report back.

**Comment by wbhart** [comment]
Ok, by me, but those failures will remain until the Nemo stuff is in. If you are ok with that, so am I. Let's hope I didn't miss anything else!

**Comment by thofma** [comment]
I tried it locally, so it should "just work".

**Comment by fieker** [comment]
On Fri, May 21, 2021 at 08:09:43AM -0700, wbhart wrote:
> I should have marked this PR as breaking, but didn't do so as I thought these were all new functions and therefore not potentially breaking anything. Somehow the GaloisGroups code used them before they were implemented by me, which is slightly concerning.
Why is is concerning? Thats why we do upwards testing. Functionality
will always, among other things, be added by demand....

**Pull request merged**
