### PR TITLE
start LaurentMPolyElem

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
This seems to work without adhoc arithmetic and without promotions :)

**Comment by tthsqe12** [comment]
We needed one promote rule. If the automatic promotion from R[x,y] to R[x,1/x,y,1/y] is not acceptable, then the promotion system is broken. I hope it is acceptable.

**Comment by thofma** [comment]
Is it there in the univariate case?

**Comment by wbhart** [comment]
What does the canonical promotion do in this case? E.g. where is y sent?

**Comment by wbhart** [comment]
Or did you mean R[x, y] to R[x, y, 1/x, 1/y]?

**Comment by tthsqe12** [comment]
Yeah, maybe that. It is all as canonical as it can be.

**Comment by tthsqe12** [comment]
I think this is good now.

**Pull request merged**
