### PR TITLE
Add iroot and check parameter to root for Integer.

### LINKED ISSUE #556: Implement iroot
Currently Julia has isqrt for the integer floor of the square root of an integer. We propose adding iroot to both AbstractAlgebra and Nemo to give the floor of the integer root of its input, as we are going to make root raise an exception if the root is not exact.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #556 

Also see https://github.com/Nemocas/Nemo.jl/issues/862

This PR is the AbstractAlgebra counterpart to https://github.com/Nemocas/Nemo.jl/pull/1118 however I believe the two PR's to be completely independent.

It's technically breaking as it changes the semantics of root, but should not change any current use cases, so it is weakly breaking in that sense.

### CODE REVIEW

**Comment by fieker** [comment]
On Fri, Jul 16, 2021 at 07:22:05AM -0700, wbhart wrote:
> Fixes #556 
> 
> Also see https://github.com/Nemocas/Nemo.jl/issues/862
> 
> This PR is the AbstractAlgebra counterpart to https://github.com/Nemocas/Nemo.jl/pull/1118 however I believe the two PR&#39;s to be completely independent.
> 
> It&#39;s technically breaking as it changes the semantics of root, but should not change any current use cases, so it is weakly breaking in that sense.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Nemocas/AbstractAlgebra.jl/pull/939
> 
> -- Commit Summary --
> 
>   * Add iroot and check parameter to root for Integer.
> 
It is breaking as the current semantics is used to compute bounds...
So, once merged this will need Hecke and Oscar updating.
(I am not unhappy with the suggestion)

Am I missing s.th.? But this defines it for BigInt, not fmpz?
And the semantic for BigInt will be different than for fmpz?

**Comment by wbhart** [comment]
The new function does exactly the same thing as the old for any conceivable call. There was no check flag previously, and the default here is false, so.....

As for fmpz, that is handled in the Nemo PR linked above. And as you can see from the docstrings, they have identical semantics. 

The difference I am talking about is a technical difference with the original semantics which were to compute the truncated integer part of the root. That's no longer part of the definition of the root function (but still happens in practice anyway).

**Comment by wbhart** [comment]
Note that the iroot branch is not expected to pass until flint-2.9 is out (not 2.8), hence the failure on the iroot CI.

**Comment by thofma** [comment]
Does the corresponding Nemo PR need flint 2.9 or is 2.8 sufficient?

**Comment by wbhart** [comment]
2.8 only.

**Pull request merged**
