### PR TITLE
Fix docstring for hnf_with_trafo.

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by thofma** [comment]
Why remove the return types?

**Comment by wbhart** [comment]
I could be wrong, but I think the notation is incorrect. The arrow is used
for lambdas in Julia. At least a double colon should be used.

Also, the return type is a tuple, I think, so it isn't a valid return type
anyway.

I don't mind having return types, if it were done consistently everywhere
(could be a useful HiWi project, actually), but they should be valid Julia
types, with correct notation, so that any coverage parser can interpret
them. (Claus suggested we hire a HiWi to do something like a coverage
check, or even write a tool to check it for us.)

Note, I did change the _with_trafo string to specify what is returned,
which actually gives information about the order of the values returned,
which the types alone do not give. I actually prefer this, but am open to
other possibilities.

**Comment by thofma** [comment]
Here is an example from Base:
```julia
help?> length
search: length hooklength set_length! leglength pol_length

  length(A::AbstractArray) -> Integer

  Returns the number of elements in A.
```

**Comment by wbhart** [comment]
Yeah, that's a good example given that Integer is an abstract type. I don't
really understand the purpose of it, but I guess it has been deemed useful.

>

**Pull request merged**
