### PR TITLE
require g to be of type Function

### PR DESCRIPTION
**Pull request by heiderich**
in `change_base_ring` and `evaluate`

This should fix https://github.com/thofma/Hecke.jl/issues/36

In addition some of the function definitions are now in concordance with the docstrings.

### CODE REVIEW

**Comment by thofma** [comment]
This introduces more problem then it solves. Not all things that are callable are functions, for example all the map types in AbstractAlgebra are not functions.

```
struct A
end

(::A)(x::RingElement) = x + 1
```
Now anything of type `A` is callable but they are not subtypes of function.

I don't think this is a good idea. There is literally no advantage to ask users to always write `x -> f(x)` instead of just `f` everywhere.

**Comment by thofma** [comment]
The point of allowing `Any` in the first place is to be able to just pass the ring.

**Comment by thofma** [comment]
wrong button

**Comment by heiderich** [comment]
> The point of allowing Any in the first place is to be able to just pass the ring.

I explained in https://github.com/thofma/Hecke.jl/issues/36 and also last year in https://github.com/Nemocas/AbstractAlgebra.jl/issues/106 why I think it is a bad practice to pass a ring instead of a function or a ring homomorphism to `change_base_ring`.

However I was not aware of the Map types. On my system (linux) all the tests pass. So I did not notice possible regressions.

@thofma Could you provide an example of one of "all the map types in AbstractAlgebra" that would not work anymore? Maybe it would be worth to add such an example to the tests. So it could prevent people like me from making such kind of breaking changes.

As I have not seen such examples yet, the following is just a speculation. But could we introduce a new type that would be a supertype of "all the map types in AbstractAlgebra" and `Function`? Maybe this one could be used instead of `Function` for `g` here.

**Comment by wbhart** [comment]
You could use the following in the change_base_ring function:

Union{AbstractAlgebra.Ring, Function, AbstractAlgebra.Map, AbstractAlgebra.PolyElem, AbstractAlgebra.MPolyElem}

I think this would cover the important cases. I don't think adding yet another type just for this is helpful. The problem is, every time someone wants to use this is a new way, they can't, without getting the type changed.

**Comment by heiderich** [comment]
@wbhart I do not insist in having a new type. However there are already 5 functions affected (including  `evaluate`). If new ones should get added, we would probably have to make sure that those unions are always changed in every place. So having this union defined somewhere central might not be such a bad idea.

Also I think that "every time someone wants to use this is a new way" we should check whether this use is actually meaningful. Having a type would help to keep track.


I have two remarks concerning the list of types you propose:

1) I am not sure whether we should have `AbstractAlgebra.MPolyElem` in that list. If the polynomial is not univariate, how is the result of the "call" defined? There should probably also be a restriction on the base ring (this also applies to `AbstractAlgebra.PolyElem`).
2) I strongly suggest not to add `AbstractAlgebra.Ring` to that list. One motivation for this pull request was actually to make sure that `change_base_ring` does not get called with `g` a ring. I explained my reasoning in thofma/Hecke.jl#36 and in #106.

**Comment by wbhart** [comment]
Then we should not allow Function either. Can you tell me what the result of a change_base_ring would be with the following function:

function bill(a::Int, b::Int)
   printf("This is an evil function")
end

**Comment by thofma** [comment]
The docstring makes it pretty clear what is happening. Apply the second argument to all coefficients.
There is no way to restrict the input to morphisms or "useful functions" using only type annotations. Additionally there is no gain of restricting the type signature. It reduces the flexibility of the approach and literally has no gain. As Bill shows, people would still be able to shoot themselves in the foot.

The syntax `change_base_ring(_, R)` with `R` a ring will stay. Otherwise this function should have been "apply_map_coeffcientwise" or a similar abomination.

**Comment by heiderich** [comment]
> Additionally there is no gain of restricting the type signature. It reduces the flexibility of the approach and literally has no gain.

The aim is to avoid accidental misuse. The example of Bill produces an error, giving the user a hint that he is using the function in an unintended way. Passing a ring for `g` can work, but may not be what a user expects. 

> The syntax change_base_ring(_, R) with R a ring will stay. 

I understood your comment in https://github.com/thofma/Hecke.jl/issues/36#issuecomment-508540809 in such a way that you would also discourage that notion. Did you change your mind?

> Otherwise this function should have been "apply_map_coeffcientwise" or a similar abomination.

I would suggest providing an exact mathematical specification and chose a function name that expresses it. If one allows to pass everything that callable, this is of course difficult.

I believe that more explicit specifications will be an advantage as a system grows. As you seem to prefer convenience, I am closing this PR.

**Comment by kalmarek** [comment]
how expensive is creation of anonymous function `x->R(x)`? If it's cheap (as I'd guess), then a simple solution is to provide the generic `change_base_ring(..., ::Function)` and divert 
```julia
change_base_ring(..., R::T) where T <:Union{Ring,....} = change_base_ring(..., x->R(x))
```
Everybody is happy ans it's a one-liner.

**Comment by thofma** [comment]
What is the difference to the status quo?

**Comment by wbhart** [comment]
I don't recommend that. Creation of a lambda requires a heap allocation, which could incur the wrath of the garbage collector. I already thought about this, and I don't think it is a good idea for performance reasons, though admittedly for occasional use it wouldn't be a problem.

**Comment by kalmarek** [comment]
that when user passes a `c::Cat` as the second argument he's greeted with `MethodError`, which suggests what can be put as the second argument; It's much better than an error saying that `Poly` can not be coerced to `Cat`s ;)

and as I understood this issue was only about UX and/or discoverability.

@wbhart any benchmarks supporting this claim?

```
julia> change(v::AbstractVector, R::AbstractAlgebra.Ring) = [R(a) for a in v]
change (generic function with 1 method)

julia> change2(v::AbstractVector, f::Function) = [f(a) for a in v]
change2 (generic function with 2 methods)

julia> change2(v::AbstractVector, R::AbstractAlgebra.Ring) = change2(v, x->R(x))
change2 (generic function with 2 methods)

julia> R, x = PolynomialRing(zz, "x")
(Univariate Polynomial Ring in x over Integers, x)

julia> using BenchmarkTools

julia> v = [1,2,3];

julia> change(v, R); change2(v,R);

julia> @allocated change(v, R)
528

julia> @allocated change2(v,R)
544

julia> w = rand(-1000:1000, 10_000);

julia> @allocated change(w,R)
1360064

julia> @allocated change2(w,R)
1360080
```

**Comment by wbhart** [comment]
It's hard to provide a benchmark for this, as in trivial cases the compiler can use what I think the computer science people call lambda lifting to make the allocation go away, which is probably what happens here.

**Comment by kalmarek** [comment]
great, but do you have an example of a non-trivial lambda function which is in the class we're discussing here (namely: coercion or evaluation) to actually see if it stills incurs the divine retribution...yyy the wrath of GC i mean ;-)

**Comment by wbhart** [comment]
No, I don't. But I know how lambda's are implemented in compilers in general. The case where it has to create a closure will incur an allocation.

Is there any point to this discussion?

What would the change actually accomplish anyway? I really think we need to drop this discussion. There is far too much important work this is keeping us all from. Oscar is far from a release and there is so much functionality that needs to be implemented, tested, documented, and there is so much infrastructure work that needs to be done that we don't have time to argue the toss about tiny details that there isn't broad concensus on.

I don't see how any solution here can address *all* of the concerns people have. Therefore we should settle on a solution that we can all live with, even if we would have personally done it differently.

**Pull request closed without merging**
