### PR TITLE
add factor docs

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by thofma** [comment]
Pease replace `(p, e) in a.fac` by `(p, e) in a`. Don't touch the private parts.

**Comment by fieker** [comment]
On Wed, Sep 15, 2021 at 05:49:12AM -0700, Tommy Hofmann wrote:
> Please replace `(p, e) in a.fac` by `(p, e) in a`. Don't touch the private parts.
> 

Great!!! I never knew that (p,e) in a works!!!

**Comment by thofma** [comment]
Maybe we could mention that they satisfy the iterator interface, like here: https://nemocas.github.io/Nemo.jl/dev/factor/

**Comment by tthsqe12** [comment]
Huh? I did this...
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1017/files#diff-79418cea5c9129850b58b87c86de744d56096f0900774757a8b47919ba1d303aR15-R23

**Comment by tthsqe12** [comment]
and this goes into the online docs too (in the docs/src/ring.md)

**Comment by thofma** [comment]
I overlooked it, thanks.

**Pull request merged**
