### PR TITLE
Improve coefficients_of_univariate_MPoly

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by wbhart** [comment]
Why not write two functions, one of which returns the coefficients of a univariate polynomial in terms of variable i, then a second function, main_variable, say (see the generic code in AbstractAlgebra where such a function already exists for generic polys), which computes which variable it is a univariate in. This way if the user knows which variable it is, they can get the answer efficiently without creating three arrays and looping over all exponents.

Also, can you place spaces after commas, and not place additional spaces inside [] and (), e.g. [x for x in blah] not [ x for x in blah ]. These are just the conventions we are using elsewhere.

**Comment by heiderich** [comment]
If `p` is an `MPoly` in one variable, then `vars(p)[1]` gives you this variable. Therefore I am not sure whether one really needs a function `main_variable`.

The first array `vars_p` is created for two reasons:
- to check its length (if it is greater then 1 we throw an error)
- to extract the "main variable" from it as `vars_p[1]`

In daf3c5c4de18ad293d556604460706ff94b7a4f0 I replaced summing over the exponents by accessing the entry corresponding to the "main variable", assuming that the order of the variables in `gens(parent(p))` is the same as that in `exponent_vector`. However we only need only one coefficient of this exponent vector. Therefore I added functions to access these exponents of single variables individually in 1773b08ddedb7f79b123fa206861f175544cbb28 and replaced the use of `exponent_vector` by `exponent` in b1c9043979d40a35ff6c3bc0c941c3decabd966d.

I guess the final loop over these exponents is necessary.

**Comment by wbhart** [comment]
So, I don't understand this line:

```
var_index = findfirst(isequal(vars_p[1]), gens(parent(p)))
```

It looks like you are creating all the generators of the polynomial ring than comparing with them. I think this will be costly. Wouldn't it make more sense to look for the first exponent that is nonzero? Also, I don't quite get the bracketing. Shouldn't isequal take two arguments?

Also, can you put spaces before and after + and - signs. Again, this is a convention we use just to make the code look consistent.

**Comment by wbhart** [comment]
I'm also still concerned about the complexity here. If there are n variables and m terms, this takes O(mn) operations because of the check at the beginning that the polynomial is univariate (it has to check every exponent of every term). But in some cases you could get away with only O(n + m) operations (e.g. if the poly is dense).

On average you could do O(n) checks to determine which is the variable that is nonzero (at most one of the terms can have all zero exponents), and then you can write out the coefficients in O(m) operations (in the dense case), so long as you were prepared to drop the test for univariate.

Also, I don't believe the MPoly type name should appear in the function name. We may have similar functions in other multivariate polynomial modules, and they should be distinguished by the types of their parameters, not by their names. E.g. we don't have gcd_Int, gcd_Rational_Int, gcd_fmpz, etc., but just gcd.

**Comment by heiderich** [comment]
> So, I don't understand this line:
> 
> ```
> var_index = findfirst(isequal(vars_p[1]), gens(parent(p)))
> ```
> 
> It looks like you are creating all the generators of the polynomial ring than comparing with them. I think this will be costly. Wouldn't it make more sense to look for the first exponent that is nonzero? Also, I don't quite get the bracketing. Shouldn't isequal take two arguments?

This was by the documentation of `findfirst(predicate::Function, A)`.

> Also, can you put spaces before and after + and - signs. Again, this is a convention we use just to make the code look consistent.

I hope I caught all of them.

**Comment by heiderich** [comment]
> I'm also still concerned about the complexity here. If there are n variables and m terms, this takes O(mn) operations because of the check at the beginning that the polynomial is univariate (it has to check every exponent of every term). But in some cases you could get away with only O(n + m) operations (e.g. if the poly is dense).
> 
> On average you could do O(n) checks to determine which is the variable that is nonzero (at most one of the terms can have all zero exponents), and then you can write out the coefficients in O(m) operations (in the dense case), so long as you were prepared to drop the test for univariate.

What do you propose to do instead? Rely on the user providing a univariate polynomial?

I would prefer the check to be carried out by default. How about an optional or keyword argument to turn it off?

> Also, I don't believe the MPoly type name should appear in the function name. We may have similar functions in other multivariate polynomial modules, and they should be distinguished by the types of their parameters, not by their names. E.g. we don't have gcd_Int, gcd_Rational_Int, gcd_fmpz, etc., but just gcd.

I also do not like the name. However I think that simply `coefficients` would not be suggestive enough. Do you have a better idea?

**Comment by wbhart** [comment]
> > I'm also still concerned about the complexity here. If there are n variables and m terms, this takes O(mn) operations because of the check at the beginning that the polynomial is univariate (it has to check every exponent of every term). But in some cases you could get away with only O(n + m) operations (e.g. if the poly is dense).
> > On average you could do O(n) checks to determine which is the variable that is nonzero (at most one of the terms can have all zero exponents), and then you can write out the coefficients in O(m) operations (in the dense case), so long as you were prepared to drop the test for univariate.
> 
> What do you propose to do instead? Rely on the user providing a univariate polynomial?
> 
> I would prefer the check to be carried out by default. How about an optional or keyword argument to turn it off?

Yeah a default argument would be good.

> 
> > Also, I don't believe the MPoly type name should appear in the function name. We may have similar functions in other multivariate polynomial modules, and they should be distinguished by the types of their parameters, not by their names. E.g. we don't have gcd_Int, gcd_Rational_Int, gcd_fmpz, etc., but just gcd.
> 
> I also do not like the name. However I think that simply `coefficients` would not be suggestive enough. Do you have a better idea?

I was just thinking coefficients_of_univariate or univariate_coeffs or something like that. I don't think we can do much better than a descriptive name like that. It's just the type I don't think is necessary in the name.

**Comment by wbhart** [comment]
> > So, I don't understand this line:
> > ```
> > var_index = findfirst(isequal(vars_p[1]), gens(parent(p)))
> > ```
> > It looks like you are creating all the generators of the polynomial ring than comparing with them. I think this will be costly. Wouldn't it make more sense to look for the first exponent that is nonzero? Also, I don't quite get the bracketing. Shouldn't isequal take two arguments?
> 
> This was by the documentation of `findfirst(predicate::Function, A)`.

Oh, I see. It is some kind of currying. That's fine I guess.

**Comment by heiderich** [comment]
Commit introduced a switch to turn off the check whether the polynomial is univariate in 
732d07a.

**Comment by heiderich** [comment]
Note that there is also `Base.exponent`. So I guess exporting the new `exponent` might be a problem. Maybe we could change its name. Ideas?

**Comment by wbhart** [comment]
Yeah, once again we are screwed by a floating point function of the same name.

In this case, though, I don't see much potential for conflict. I think we could live with using exponent. We have to import it from Base though in AbstractAlgebra.jl.

**Comment by heiderich** [comment]
So should I export it?

**Comment by wbhart** [comment]
Yes, it should be imported, then exported as normal.

**Comment by wbhart** [comment]
This is looking good. There is still an = around line 716 in the test file without spaces before and after. But I think that is the last problem I see.

**Comment by wbhart** [comment]
Oh, except you didn't change the name of the function yet to remove the MPoly (perhaps the test function also needs renaming?).

Also, is it necessary to use a parameter after the semicolon? I think these use a dictionary. It is probably much faster to use an ordinary optional parameters after a comma.

**Comment by wbhart** [comment]
Or alternatively create a Univariate section, since I guess the main function doesn't really do a conversion as such.

**Comment by heiderich** [comment]
I think my last commits address all your comments, @wbhart.

**Comment by wbhart** [comment]
They do indeed, thanks.

**Pull request merged**
