### PR TITLE
add generic mpoly factor algos

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
Well, I still have to change at least one thing and figure out how to test this stuff.

**Comment by wbhart** [comment]
It might be helpful if you put [WIP] in the title of PR's here and elsewhere that are not finished, so that we know not to merge them yet. Alternatively you could use the GitHub draft facility, which is designed for this purpose.

**Comment by tthsqe12** [comment]
I am actually done now. The code is unfortunately not testable from within AA, but it is working with nemo and hecke.

**Comment by wbhart** [comment]
Ok, then post a link here with the Nemo tests when done. Then we know it will continue to be tested. No rush of course.

**Comment by tthsqe12** [comment]
This is a pretty good test of this code https://github.com/thofma/Hecke.jl/pull/116

**Review by wbhart — APPROVED** [review]

**Pull request merged**
