### PR TITLE
Centralize import/export statements and clean up main file

### PR DESCRIPTION
**Pull request by lgoettgens**
Nemocas/Nemo.jl#1601 for AbstractAlgebra

Edit: some parts have already been merged as https://github.com/Nemocas/AbstractAlgebra.jl/pull/1556

### CODE REVIEW

**Comment by lgoettgens** [comment]
Most of the work was already done by @fingolfin in #1281.

Some open questions on how to proceed:
1. Why are there two long export lists in `AbstractAlgebra.jl` (one starting around line 220, the other around line 790)?
2. For the submodules (`Generic` and `PrettyPrinting`) there is currently a mix of exporting their functions from the submodule and importing into the main `AbstractAlgebra` module. Which of the two is the one to use?

**Comment by fingolfin** [comment]
> 1. Why are there two long export lists in `AbstractAlgebra.jl` (one starting around line 220, the other around line 790)?

Probably historic reasons? I would try to merge everything into the first list and see what happens.

> 2. For the submodules (`Generic` and `PrettyPrinting`) there is currently a mix of exporting their functions from the submodule and importing into the main `AbstractAlgebra` module. Which of the two is the one to use?

Maybe I am missing something in your question, but I don't think the two are interchangeable in general?
- if `foo` is defined before `module Generic` is loaded, then `Generic` must import it
- if `foo` is only defined *after `module Generic`, then `Generic` cannot import it; and if code outside `Generic` is supposed to use `foo` or even install methods for it, then `Generic` but must export it

**Comment by lgoettgens** [comment]
> > 2. For the submodules (`Generic` and `PrettyPrinting`) there is currently a mix of exporting their functions from the submodule and importing into the main `AbstractAlgebra` module. Which of the two is the one to use?
> 
> Maybe I am missing something in your question, but I don't think the two are interchangeable in general?
> 
> * if `foo` is defined before `module Generic` is loaded, then `Generic` must import it
> * if `foo` is only defined *after `module Generic`, then `Generic` cannot import it; and if code outside `Generic` is supposed to use `foo` or even install methods for it, then `Generic` but must export it

I am both times talking about the flow `Generic` -> `AbstractAlgebra`. Sometimes, `Generic` exports stuff to `AbstractAlgebra` and sometimes `AbstractAlgebra` imports stuff from `Generic`.

**Comment by fingolfin** [comment]
Maybe wait a bit with this, as the GroupsCore PR is getting closer to being finished and it'll touch the exports a bit, too, so there are conflicts

**Comment by fingolfin** [comment]
Ah, so I indeed misunderstood, sorry. Well, we never do `using .Generic`, do we? So I would expect all those `export` statements in `Generic` to have no effect?

**Comment by lgoettgens** [comment]
> Ah, so I indeed misunderstood, sorry. Well, we never do `using .Generic`, do we? So I would expect all those `export` statements in `Generic` to have no effect?

Ah true... So I will delete them (without semantical change)

**Comment by fingolfin** [comment]
@lgoettgens this can in principle be updated and merged, right? Nothing I should do, is there?

I realize you may have more important things to do right now, I just want to make sure that *I* am not unwittingly the blocker :-).

**Comment by lgoettgens** [comment]
I think there is basically nothing really no to do here (apart from merging the two export lists). But as long as this is not compatible with Oscar master, I am afraid to break things due to the OscarCI not running. So I would only start to work on this after https://github.com/oscar-system/Oscar.jl/pull/3231

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
