### PR TITLE
Add promote rules for finite fields.

### PR DESCRIPTION
**Pull request by HechtiDerLachs**
I hope, I spotted the correct place. Otherwise please let me know where this goes.

### CODE REVIEW

**Comment by thofma** [comment]
Can you point me to the Oscar PR that needs that? (Just for testing purposes)

**Comment by HechtiDerLachs** [comment]
That should be [this one](https://github.com/HechtiDerLachs/Oscar.jl/tree/Schemes_for_Oscar); but it has the three lines already built in as a patch.

**Comment by thofma** [comment]
OK, thanks! And the test will fail if the three lines are missing, right?

**Comment by HechtiDerLachs** [comment]
Sorry, but I wouldn't rely on the tests there for the moment. This branch is very much work in progress for now and can not be trusted with anything. But I can provide some tests especially for that later today.

**Comment by HechtiDerLachs** [comment]
Alternatively, one could probably replace `QQ` by `GF(17)` here in [this test](https://github.com/oscar-system/Oscar.jl/blob/65ccb59118fe4f1b5c7ceaf0fa0147744fc9a927/test/Rings/mpoly-localizations.jl#L13)

**Comment by thofma** [comment]
Thanks, I will test it.

**Comment by thofma** [comment]
I could not reproduce an error, so an example which fails would be good. The last promote rule you added should in principle not be necessary, so I would like to see where it fails.

**Comment by thofma** [comment]
I think I fixed this in Nemo. Feel free to reopen if you encounter other things which do not promote (but they should).

**Pull request closed without merging**
