### PR TITLE
add one(::NCRingElem) and zero(::NCRingElem)

### PR DESCRIPTION
**Pull request by rfourquet**
This is WIP (no tests nor documentation yet) as I don't know if this has a chance.

The meaning of `one(a)` is to give an multiplicative identity element, which is well defined even in non-commutatice rings. This also adds `zero(a)`. For example, if `p` was an `NCPoly`, `zero(p)` didn't work, but `0*p` did...

For `one` on matrices, I required that they are square, as otherwise an `identity` element doesn't exist. 

I think `one(::MatrixSpace))` should also check for square-ness, for the same reason. 
(And maybe similarly for `identity_matrix`, we could have a `diagonal_matrix` function which doesn't require square-ness).

### CODE REVIEW

**Comment by wbhart** [comment]
I'm not too fussed if we require matrices to be square or not. I don't use the other behaviour. @fieker is also fine with this.

@thofma might have a need for it though, so let's see if he agrees with this restriction.

There's certainly no reason why zero for NCPoly shouldn't work. I'm actually surprised there wasn't test code for that already. But if it is really broken, then it should certainly be fixed. Thanks for picking that up.

But I don't understand why you need the union of NCRingElem and RingElem. Every RingElem should be an NCRingElem, since RingElem <: NCRingElem, or at least it was the case when I implemented it!

**Comment by wbhart** [comment]
On the other hand, all our matrix algorithms currently require a commutative ring, so I don't think you can lift that restriction in many places in Matrix (in case you have been thinking of doing so).

**Comment by wbhart** [comment]
Yeah I implemented them to give 1's down the diagonal, even for non-square matrices.

Obviously there is no such thing as a "multiplicative identity" in a matrix space. So mathematically the "one" function shouldn't exist for matrix spaces. But this will cause confusion, so let's put it in (to cause confusion) and just make it only work for square matrices.

**Comment by wbhart** [comment]
Whoops. @rfourquet I did not mean to merge this until you had fixed the issues I raised above. Could you open a separate PR to fix those.

**Comment by rfourquet** [comment]
> But I don't understand why you need the union of NCRingElem and RingElem

Sorry I got confused. I was definitely expecting `RingElem <: NCRingElem`, which is true indeed, but was led to believe otherwise for some reason.

> so I don't think you can lift that restriction in many places in Matrix (in case you have been thinking of doing so).

I have not been thinking of doing so. I was just needing this `one` function in generic code, hence this PR.

> Obviously there is no such thing as a "multiplicative identity" in a matrix space.

When `nrows == ncols`, I guess this depends on how you look at it, but if `I * M == M * I == M` for all matrix `M` in a given matrix space `S`, then we can call `I` a multiplicative identity for `S` without too much stretch, and create it via `one(M)`.

So if I understand you correctly, you are fine that I also add the restriction to `one(S::MatSpace)` that `S` must contain square matrices? (in this PR, the restriction is only for `one(M::MatSpaceElem)`.

**Comment by wbhart** [comment]
@rfourquet A matrix space is not a ring, mathematically, so it makes no sense to define a multiplicative identity. That's why we have matrix algebras, which are rings.

But yeah, let's just define one to do the "obvious" thing, and restrict it to nxn, which no one seems to have a major problem with.

**Comment by rfourquet** [comment]
Tests and update of `one(::MatSpace)` at #516.

> A matrix space is not a ring, mathematically, so it makes no sense to define a multiplicative identity

I know that `MatSpace <: Ring` is false, but a matrix space containing square matrices, and which defines multiplication, models a mathematical ring.  BTW, `one` doesn't require a ring, it must just return an object which is neutral for multiplication `*`. E.g. `"a string" * one("a string") == "a string"`.

**Comment by wbhart** [comment]
Yes, but there is no multiplication in a vector space.

**Comment by rfourquet** [comment]
> Yes, but there is no multiplication in a vector space.

I understand, it's just that this particular vector space also defines multiplication, so it's an algebra. Anyway, we don't need to agree on these subtle semantics, as we agree on the technical outcome :)

**Comment by rfourquet** [comment]
> > But I don't understand why you need the union of NCRingElem and RingElem

> Sorry I got confused. I was definitely expecting RingElem <: NCRingElem, which is true indeed, but was led to believe otherwise for some reason.

Oh I know what I did: `RingElement <: NCRingElem` is `false`, so I confused `RingElement` for `RingElem`.

**Pull request merged**
