### PR TITLE
map_coeffs: do not map on zero coeffs (as per docstring)

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by thofma** [comment]
Does this work if the codomain of `f` is different to the base ring of the polynomial?

**Comment by rfourquet** [comment]
Ah good catch. I have a fix, which would not work well if the applied function can return values of different types on different coefficients, is it fine?

**Comment by rfourquet** [comment]
Sorry, scratch that, the fix is fine, I will push it there in a minute.

**Comment by thofma** [comment]
It is doing what the docstring says, so looks good to me. Maybe @wbhart wants to have a quick look before merging.

**Comment by wbhart** [comment]
I really don't like the use of underscore as a first character in a function name. But I can live with it if there is a good reason for it.

Otherwise this is fine to merge.

**Comment by rfourquet** [comment]
> I really don't like the use of underscore as a first character in a function name.

This is a typical convention to indicate internal functions, which also seems quite used in this project. I tend to use it in particular for very local functions, which are helper for (and defined next to, in the same file as) other functions.

**Pull request merged**
