### PR TITLE
Move stuff from Oscar to AbstractAlgebra

### PR DESCRIPTION
**Pull request by fingolfin**
- add `@attributes` mutable struct MPolyRing
- generic `iszero` for ideals
- Dan's code for gcd, factor for nested polynomial rings

### CODE REVIEW

**Comment by thofma** [comment]
Hm, whats up with the doctest?

**Comment by fingolfin** [comment]
> Hm, whats up with the doctest?

I am not sure what that refers to? All doctests seem to pass? Or maybe something was broken and you restarted it and I only saw the fixed result?

**Comment by thofma** [comment]
https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/6758369870/job/18369942519?pr=1494

**Comment by fingolfin** [comment]
Ah. That doctest failure is caused by Singular.jl changes. I've changed the Singular.jl version in the repo to 0.19.0-DEV now to avoid this.

**Pull request merged**
