### PR TITLE
Clean up poly_to_power_sums and power_sums_to_poly a little.

### PR DESCRIPTION
**Pull request by wbhart**
Probably still completely broken (see [1]), but at least it's broken much better now.

[1] https://github.com/Nemocas/AbstractAlgebra.jl/issues/883

### CODE REVIEW

**Comment by wbhart** [comment]
This can be merged as is. I will make a later PR to clean it up further and move the functions into src/generic/Poly.jl once #873 #884 #886 and probably others, are done.

Fixes #883

**Comment by wbhart** [comment]
Oh my gosh: "first" was added in Julia 1.6?

What is the equivalent in 1.5?

**Comment by thofma** [comment]
Still something off on julia < 1.6.

**Comment by wbhart** [comment]
Looks like the Galois groups stuff is failing. Should I be concerned about this @fieker ?

Does that code use power_sums_to_polynomial and friends in a way that doesn't satisfy the restrictions we just placed on it?

**Comment by wbhart** [comment]
Actually, let's see if the latest commit I made fixes that.

**Pull request merged**
