### PR TITLE
Add quo shorthand for residue rings.

### LINKED ISSUE #998: Perhaps add a shorthand for `ResidueRing(R, x)`?
It would be kinda nice to have a shorthand for `ResidueRing(R, x)`. This is certainly not highly important, but in interactive use at least, I'd find it quite convenient if I could abbreviate to something like one of these (I am *not* saying all of these should be added, to the contrary; but perhaps one of them could be):
- `R % x` -- this is akin to the GAP syntax `Integers mod 6` and is based on the idea that `set mod N := { a mod N : a\in set }`
- `mod(R, x)` -- same idea; but since `%` maps to `rem`, this is perhaps more faithful mathematically
-  `R / x` or `R // x`: based on the mathematical notation `R / xR` (note that I also would like to allow `x*R` to form the principal ideal, but since AA has no ideals, I am not asking for it here; moreover, even then, `R / x*R` would be parsed as `(R/x)*R`; and writing `R/(x*R)` is somewhat awkward)

### PR DESCRIPTION
**Pull request by wbhart**
Fixes #998 

Obviously only works for residue rings, not residue fields.

### CODE REVIEW

**Comment by fieker** [comment]
Step i the right direction. However, I thought that `quo` should always return 2 results, the second being the projection map (which allows pointwise inverse)?

**Comment by wbhart** [comment]
Oh you want an actual map so that we can also implement preimage or something like that?

That's a really ugly issue with our system that the residue ring object is not an actual map. Surely we aren't going to do this with all parent objects?

And surely you don't want ResidueRing itself to also return a map as well. That is going to require changing a lot of code which currently uses ResidueRing.

**Comment by thofma** [comment]
The proposal is not to make `ResidueRing` return a map. At the moment `quo` for modules (within AbstractAlgebra) s returning the map and so does everything else in Oscar land. For consistency would make sense to have it always return the map, including here.

**Comment by wbhart** [comment]
Ok, I'll add the map. I guess we'll have to come up with other function names for other kinds of parents where we want a version of the parent object which is a genuine map. If that's what's consistent with what is elsewhere, that makes sense.

**Comment by fieker** [comment]
On Thu, Mar 17, 2022 at 09:38:11AM -0700, wbhart wrote:
> Wouldn't a better solution be to write a function to construct a map from the parent or to add a map field to the parent object. That would mean ResidueRing and quo behave the same way, and we'll be able to use a similar solution elsewhere if needed.
It wouldn't be better - or lets say it might have been the same.
However, all but 1 or 2 quo constructors through the system return the
map, same for sub(...)
ResidueRing is completely random. There is also the minor problem that
in general neither the residue ring nor the full ring uniquely determine
the quotient:
Take any maximal order and a totally split prime p. Then for all prime
ideals above, we have ResidueRing(R, P) = GF(p). Unless we really want
several GF(p) and rely on the GF(p)'s to be different, we cannot infer
the map from GF(p) and R. If I do this for Z[\sqrt -1] (of class 
number 1, and euclidean) I can demonstrate this even without ideals.

To me: ResidueRing is used too much to have hope to make this uniform,
so I can (and have to) live with sometimes using lift(x) or lift(ZZ, x)
or similar.
However, quo is much more controlled (so far), so there is a hope on
insisiting to get a map.

For ResidueField, a suggestion might be quo(Field, R, P).
Currently, my code has to do:

    x = ResidueField(parent(d), d)
    if isa(x, Tuple)
      R, mR = x
    else
      R = x
      mR = MapFromFunc(x->R(x), x->lift(x), parent(d), R)
    end

**Comment by wbhart** [comment]
If quo is designed to give a map elsewhere, that is enough for me. I'll see if I can at least make it work generically for the residue rings I'm familiar with. If there are special requirements for other cases, I'm sure the generic definition can be overridden in that case.

**Comment by wbhart** [comment]
I've added what I think is the minimal generic solution. If you want something more involved than this, let me know.

**Comment by wbhart** [comment]
For example, do you want to always have the lift function (not that I am sure this is always currently defined).

**Comment by fieker** [comment]
On Fri, Mar 18, 2022 at 06:46:38AM -0700, wbhart wrote:
> For example, do you want to always have the lift function (not that I am sure this is always currently defined).
> 
No, generically, lift can not be well defined by the two rings either.
If the projection allows a pointwise inverse, that's perfect. If this is
implemented in the "classical" cases by calling lift rep. Q(x): fine.

Thanks

**Comment by wbhart** [comment]
Oh sorry, I think I miscommunicated. What I meant to ask is do you want to always have the pointwise inverse defined generically for the map? Or do you just want the projection with no pointwise inverse by default?

**Comment by fieker** [comment]
On Fri, Mar 18, 2022 at 07:42:46AM -0700, wbhart wrote:
> Oh sorry, I think I miscommunicated. What I meant to ask is do you want to always have the pointwise inverse defined generically for the map? Or do you just want the projection with no pointwise inverse by default?
For all quotient maps a pointwise inverse shuold be available -
otherwise, it would needs some version of lift to work....

**Comment by wbhart** [comment]
Ok, then I'll add this. I'll put WIP on the PR until I get that done.

**Comment by wbhart** [comment]
If the tests pass this is ok to go. It currently relies on `lift()`, which in turn generically relies on `data()`, but that should be implemented.

Obviously that is only for residue rings and not for quo constructions in general.

**Comment by fieker** [comment]
On Thu, Mar 17, 2022 at 09:25:26AM -0700, wbhart wrote:
> I am not sure what you mean. The returned object R can be used like a map for projection (if I understand what you meant).

To add to my earlier/ later post:
In general, 
R = ResidueRing(S, a)
cannot support R(S(x)) I think: There are (euclidean) rings where (R, S)
do not determine the map uniquely. Even in our system, there is somewhere
a type for GaussianIntegers, Z[i]. This is euclidean.
Take a = 2+i and b = 2-i, then 

ResidueRing(Z[i], a) = ResidueRing(Z[i], b) = GF(5), but
ResidueRing(Z[i], a)(i) = -2, while
ResidueRing(Z[i], b)(i) = 2

I do not see how to handle this without a map.

I fully agree that changing ResidueRing everywhere to do a map is not
feasable (anymore), however quo should do this always. In situations
where the map in known (in advance) to be superflous, one can use
ResidueRing
(or R(x) and lift)

**Pull request merged**
