### PR TITLE
add some Groebner machinery for FreeAssociativeAlgebra

### PR DESCRIPTION
**Pull request by tthsqe12**
pinging @julien-schanz for more test examples that exercise all parts of the added code.

### CODE REVIEW

**Comment by thofma** [comment]
@julian-schanz, do you have a test example, that was failing before? If so, could you add it to the tests?

**Comment by thofma** [comment]
@tthsqe12 are you in contact with @julien-schanz? What is the status here?

**Comment by tthsqe12** [comment]
Yes. The status is: still looking/implementing algos that can compute some examples.
I will try to find the above example for the test code.

**Comment by fingolfin** [comment]
@julien-schanz I think your PR #1292 makes this obsolete, is that right?

**Comment by julien-schanz** [comment]
> @julien-schanz I think your PR #1292 makes this obsolete, is that right?

Yes, I think so too.

**Pull request closed without merging**
