### PR TITLE
Add `coefficients(a::AbsPowerSeriesRingElem)`

### PR DESCRIPTION
**Pull request by lgoettgens**

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Looks plausible. Of course no test, so I am going to trust that you need this and verified it works "as expected" (whatever that means)

**Comment by thofma** [comment]
@fieker does that make sense?

**Comment by lgoettgens** [comment]
Ok, so what I wanted to add is a function that gives me all coefficients (as `coeff` does for a single one), but skipping the infinite sequence of zeros in the end.

**Comment by fieker** [comment]
you need to be thinking about what you want: you want the leading zeros? If the element has a valuation? @lgoettgens  what do you need/ want? I think for polys we allow access past the degree - to get 0, for power series (and Laurent) even going to -infty would make sense

**Comment by lgoettgens** [comment]
I don't really care about leading zeros.
I think having `coefficients(a)[i] == coeff(a, i-1)` work for all indices of `coefficients(a)` would be nice (this is as it is for polys).

**Comment by lgoettgens** [comment]
Bump

**Comment by thofma** [comment]
It is not clear to me that this right thing. `length` is not part of the interface and exporting `pol_length` was a terrible mistake from the beginning.

 A faithful representation of the power series would need to include the coefficients up `precision(x) - 1`.

**Comment by lgoettgens** [comment]
That's true. I adapted the function an tests accordingly.

**Comment by fingolfin** [comment]
Off-topic, but: this function looks to me like another example of an `extrep` function as proposed in https://github.com/oscar-system/Oscar.jl/issues/4151. Which then raises the natural question: do we also have a reverse that takes such a coefficient list and turns it back into a series? E.g. `a == parent(a)(coefficients(a))` ?

**Comment by thofma** [comment]
@fieker this now goes up to `precision(x) -1`. Are you happy with this?

**Review by fieker — APPROVED** [review]

**Comment by lgoettgens** [comment]
Unfortunately, due to branch names being weird, this has to get force-merged. @fingolfin @thofma could you do the favor?

**Review by thofma — APPROVED** [review]

**Pull request merged**
