### PR TITLE
Improve conformance tests

### PR DESCRIPTION
**Pull request by fingolfin**
- don't leak the final @testset from the various conformance test functions
- workaround for `characteristic(R)` returning -1 (see #993 )
- test that ring element types are subtypes of RingElement
- add some comments
- invoke conformance tests from the test files for the respective rings
- add a central file `test/conformance-tests.jl`: In the future, we may want to move things around, and e.g. move the field specific tests from `Rings-conformance-tests.jl` to a new file `Fields-conformance-tests.jl`; or we may want to move all tests tests into a subdirectory. But this constitutes a breaking change for the "conformance test API". By providing `test/conformance-tests.jl`, 3rd party packages can just include that and are then unaffected by any renaming changes.

To support this, I also added a tweak to make `rand(QQ, big(1):big(5))` work (previously only `rand(QQ, 1:5)` was supported).

### CODE REVIEW

**Comment by wbhart** [comment]
There seem to be some test failures now. Are they expected?

**Comment by fingolfin** [comment]
Weird, it fails in a test for `issquare`. I don't (yet) see how my changes here could affect that. I also cannot reproduce this locally. Weird?!

**Comment by fingolfin** [comment]
OK, good, now I am seeing different errors in CI which are caused by missing `rand` methods. That's at least something I can understand, as opposed to those `issquare` errors, which magically seem to be gone after rebasing this PR and thus re-running the tests. Weird.

I'll see if I can repro the test failures now -- but actually, now running the AA test suite *crashed Julia* for me... Huhhhh???
```
...
Generic.RationalFunctionField.manipulation |    8      8
Test Summary:                           | Pass  Total
Generic.RationalFunctionField.unary_ops |    1      1
Test Summary:                            | Pass  Total
Generic.RationalFunctionField.binary_ops |  400    400

signal (11): Segmentation fault: 11
in expression starting at /Users/mhorn/Projekte/OSCAR/AbstractAlgebra.jl/test/generic/RationalFunctionField-test.jl:97
_ZN4llvm11Instruction15eraseFromParentEv at /Users/mhorn/Applications/Julia-1.6.2.app/Contents/Resources/julia/lib/julia/libLLVM.dylib (unknown line)
_ZN12_GLOBAL__N_18AllocOpt13runOnFunctionERN4llvm8FunctionE at /Users/mhorn/Applications/Julia-1.6.2.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.dylib (unknown line)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /Users/mhorn/Applications/Julia-1.6.2.app/Contents/Resources/julia/lib/julia/libLLVM.dylib (unknown line)
```
Alternate version of this backtrace, from Apple's Crash Reporter:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libLLVM.dylib                 	0x000000010645ca96 llvm::Instruction::eraseFromParent() + 38
1   libjulia-internal.1.dylib     	0x0000000105d14b79 (anonymous namespace)::AllocOpt::runOnFunction(llvm::Function&) + 473
2   libLLVM.dylib                 	0x000000010648270c llvm::FPPassManager::runOnFunction(llvm::Function&) + 1116
3   libLLVM.dylib                 	0x0000000106488243 llvm::FPPassManager::runOnModule(llvm::Module&) + 67
4   libLLVM.dylib                 	0x0000000106482c99 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 825
5   libjulia-internal.1.dylib     	0x0000000105cd0d53 JuliaOJIT::CompilerT::operator()(llvm::Module&) + 1715
6   libLLVM.dylib                 	0x0000000107972d32 llvm::orc::IRCompileLayer::emit(llvm::orc::MaterializationResponsibility, llvm::orc::ThreadSafeModule) + 114
7   libLLVM.dylib                 	0x000000010797afb9 llvm::orc::BasicIRLayerMaterializationUnit::materialize(llvm::orc::MaterializationResponsibility) + 393
8   libLLVM.dylib                 	0x0000000107950b6a llvm::orc::ExecutionSession::materializeOnCurrentThread(std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility) + 106
9   libLLVM.dylib                 	0x0000000107956ea8 decltype(std::__1::forward<void (*&)(std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility)>(fp)(std::__1::forward<std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> > >(fp0), std::__1::forward<llvm::orc::MaterializationResponsibility>(fp0))) std::__1::__invoke<void (*&)(std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility), std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility>(void (*&&&)(std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility), std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >&&, llvm::orc::MaterializationResponsibility&&) + 120
10  libLLVM.dylib                 	0x000000010794aa99 llvm::orc::ExecutionSession::dispatchMaterialization(std::__1::unique_ptr<llvm::orc::MaterializationUnit, std::__1::default_delete<llvm::orc::MaterializationUnit> >, llvm::orc::MaterializationResponsibility) + 137
...
```


Looks like a bug in the Julia codegen / JIT? I'll try again on a Linux machine.

**Comment by fingolfin** [comment]
Tests are passing now, yay!

Unfortunately I still can't run the full test suite on my macBook in Julia 1.6.2, I keep getting that crash :-(. Same on a Ubuntu 20.04 machine -- and the crashes also happen with master, so it's not caused by this PR. I'll open an issue.

**Comment by fingolfin** [comment]
The other PRs were merged, and this is ready for merging, @wbhart @thofma

**Review by wbhart — APPROVED** [review]

**Pull request merged**
