### PR TITLE
Travis: test also on Julia 1.4 and 1.5

### PR DESCRIPTION
**Pull request by rfourquet**
And stop testing on Julia 1.2

### CODE REVIEW

**Comment by fieker** [comment]
On Tue, Sep 22, 2020 at 02:51:25AM -0700, Rafael Fourquet wrote:
> And stop testing on Julia 1.2
> You can view, comment on, or merge this pull request online at:

It is agreed that we do not support 1.2 any more? For Oscar this is
true, but for AA and N I am not sure

**Comment by rfourquet** [comment]
> It is agreed that we do not support 1.2 any more? 

Not as far as I know, I followed Nemo's example here: 1.0 is still tested, but not 1.1 nor 1.2. My guess was that it's to save time while testing, and that tests passing on 1.0 and 1.3-1.5 was a hint that they probaby pass on 1.1 and 1.2, plus that users on 1.1 and 1.2 are probably in the minority (1.1 and 1.2 are not LTS and 3 releases behind the latest 1.5).

**Comment by fieker** [comment]
On Tue, Sep 22, 2020 at 03:38:39AM -0700, Rafael Fourquet wrote:
> > It is agreed that we do not support 1.2 any more? 
> 
> Not as far as I know, I followed Nemo's example here: 1.0 is still tested, but not 1.1 nor 1.2. My guess was that it's to save time while testing, and that tests passing on 1.0 and 1.3-1.5 was a hint that they probaby pass on 1.1 and 1.2, plus that users on 1.1 and 1.2 are probably in the minority (1.1 and 1.2 are not LTS and 3 releases behind the latest 1.5). 
> 
OK then...

**Comment by thofma** [comment]
FWIW, we also dropped julia 1.2 support in Hecke because of a weird bug in julia 1.2 which makes the tests fail.

**Pull request merged**
