### PR TITLE
Weighted multivariate power series.

### PR DESCRIPTION
**Pull request by wbhart**
Allows one to create multivariate power series where the variables are weighted as specified by a vector of `Int`s and to have truncation wrt an overall precision (after weighting, pun intended).

The following still need to be done:

- [X] Test code
- [x] Documentation
- [x] Print output in weighted order
- [ ] ~~Add valuation function (but I'm not sure what it means in this context)~~
- [ ] ~~Division and inversion (not sure if this is possible)~~
- [X] Random function
- [ ] ~~Do we want power series to have individual precisions or is a precision on the ring sufficient?~~

```
julia> using AbstractAlgebra
[ Info: Precompiling AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]

julia> R, (x, y) = PowerSeriesRing(ZZ, [2, 3], 7, ["x", "y"])
(Multivariate power series ring in x, y over Integers, AbstractAlgebra.Generic.AbsMSeries{BigInt, AbstractAlgebra.Generic.MPoly{BigInt}}[x + O(7), y + O(7)])

julia> 3x^3
3*x^3 + O(7)

julia> 3x^4
O(7)

julia> 2x*y^2
O(7)

julia> evaluate(3*x*y + x + y, [2x+y, y-1])
-1 - y + 3*y^2 - 4*x + 6*y*x + O(7)
```

### CODE REVIEW

**Comment by wbhart** [comment]
Perhaps @jankoboehm can look at this an confirm it does what he wants.

I believe it is ready to go now.

**Comment by fingolfin** [comment]
@jankoboehm (and perhaps @wdecker, @fieker ) any thoughts on this? Would be a shame to let it go to waste :-)

**Comment by thofma** [comment]
We have an application for this, so I will merge once green.

**Comment by tthsqe12** [comment]
I am not sure why inv is not allowed on the weighted series. Are you going to use this?

**Comment by thofma** [comment]
Yes, I think so. (Can you confirm @JHanselman?)

**Comment by JHanselman** [comment]
> Yes, I think so. (Can you confirm @JHanselman?)

Yeah, I need to use divexact at some point.

**Comment by thofma** [comment]
Thanks, that would be great @tthsqe12

**Pull request merged**
