### PR TITLE
Ensure rising_factorial(::Int,::Int) detects overflows

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by thofma** [comment]
Is it then still faster?

**Comment by fingolfin** [comment]
Yes. The timings actually were taken with the overflow detection on (should have mentioned that).

**Comment by fingolfin** [comment]
(Note that the FLINT method does *not* detect overflows)

**Comment by fingolfin** [comment]
@thofma OK to merge?

**Pull request merged**
