### PR TITLE
Enh/perm length

### PR DESCRIPTION
**Pull request by kalmarek**
add `length(::perm)`

instead of writing `parent(p).n` there should be some canonical method of getting the `n` of `S_n`/

I'm not particularly happy with `length` but couldn't find anything better (e.g. in GAP `length` is not really defined: permutations of different lengths could be multiplied by automatic embedding into larger of parents)

### CODE REVIEW

**Comment by thofma** [comment]
I agree that the name is not the best.

Sage calls it "size" and "length" refers to the Coxeter length.
http://doc.sagemath.org/html/en/reference/combinat/sage/combinat/permutation.html#sage.combinat.permutation.Permutation.size

Magma calls it "Degree" (on the parent), e.g., "Degree(Parent(Sigma))".

**Comment by kalmarek** [comment]
to be consistent with julia size should return `(n,)`. 

And `length` for `GroupElements` asks to be related to word-length

**Comment by fieker** [comment]
I don't think 
 - length(::perm) is a good choice (see other posts)
 - this is a property of the parent not of the permutation I'd say
 - degree(GrpPerm) is possible fine
 - I'd ageree that having this also apply to an element is convenient,
   but I don't think this is a good idea

Greetings
 Claus

**Comment by kalmarek** [comment]
since there no better alternative was found I think we could close this

**Pull request closed without merging**
