### PR TITLE
Mpoly missing

### PR DESCRIPTION
**Pull request by wbhart**
This adds all the functionality to AbstractAlgebra MPoly that is in the new fmpq_mpoly interface that Tommy and I worked out.

In particular, there is now a way to construct polynomials efficiently in library code and to interact with the exponents of a polynomial through an interface (hiding the underlying implementation).

Many of the existing exceedingly inefficient functions added recently by others can now be rewritten for efficiency.

Note I have not updated the actual docs in the docs directory. This will have to be done in a later PR, as I've run out of time to work on the AbstractAlgebra code, and I want this code to be in use as soon as possible, as it is long overdue, and quite clearly causing serious problems.

### CODE REVIEW

**Comment by wbhart** [comment]
Also fixes #177

**Comment by wbhart** [comment]
I would hold off merging this until we can discuss the issues raised by PR 502 in Nemo. I think we are allowing too much bug prone, unsafe behaviour with this interface.

**Comment by wbhart** [comment]
This is ready to merge now. I've added the necessary constructor as discussed on Nemo PR 502 and a missing setcoeff! function.

**Comment by wbhart** [comment]
This is ready to merge now @thofma 

I've added the necessary constructor as discussed on Nemo PR 502 and a missing setcoeff! function.

**Comment by thofma** [comment]
Thanks.

**Pull request merged**
