### PR TITLE
Divides functions

### PR DESCRIPTION
**Pull request by wbhart**
This adds isdivisible_by for integers and adds the check=true keyword arg for divexact everywhere (and makes the tests pass).

### CODE REVIEW

**Comment by wbhart** [comment]
It's possible I broke the new promotion system when I did a rebase. @thofma could you possibly check the changes I made to Rings.jl look ok to you. That seems to be the cause of the issue seen in inter-package CI.

**Comment by thofma** [comment]
No, it is unrelated to the changes of promotion system. There is no
```
divexact(x::ca, y::ca; check::Bool=false)
```
defined in Nemo, so when calling `divexact(x::RingElem, y::RingElem; check::Bool=false)` for two `ca` it is hitting the fallback in Rings.jl:96, which results in the recursion.

**Comment by wbhart** [comment]
Thanks for looking into it. I will work on the Nemo changes as soon as I can (hopefully I begin work on that today).

**Comment by thofma** [comment]
I just retriggered the downstream Nemo tests (with both `divides_functions` branches and it seems that there is still a problem.

**Comment by wbhart** [comment]
Yeah there's going to be lots of these bugs. I have no way to find divexact functions that are defined without the function keyword, e.g.

```
divexact(a::ca, b::ca) = a//b
```

Git grep doesn't have a way to look for occurrences of "divexact" that start on a new line. So I have missed all these.

**Comment by thofma** [comment]
I think `git grep "^divexact"` might do it.

**Comment by wbhart** [comment]
So it does, and there are literally hundreds of cases I missed this way. 

[OT] Why do people define divexact in terms of // (or worse still, div) instead of the other way around. Only one of these is in the required interface.

**Comment by thofma** [comment]
Also needs a rebase. Still don't know why I am not allowed to rebase it myself.

**Comment by wbhart** [comment]
Will merge when green.

**Pull request merged**
