### PR TITLE
Add pfaffian

### PR DESCRIPTION
**Pull request by 8d1h**
Hi!

I was looking for Pfaffians in Oscar, but since this works for generic matrices, it's probably better to make it available in AbstractAlgebra.

There is a recursive algorithm (taken from Macaulay2) that computes the Pfaffian as well as k-Pfaffians (like k-minors). A second algorithm (by Bär-Faddeev-LeVerrier, available in Sage) is faster over QQ but requires division so is not always applicable.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Faddeev-LeVerrier for determinants can be sped up using baby-step giant-step approach; see https://arxiv.org/abs/2011.12573

I guess this should work for Pfaffians too?

**Comment by wbhart** [comment]
Great! Could you also add some docstrings and invoke them in docs/src/matrix.md

Normally I'd also ask you to export pfaffians as well, but there is no point yet due to a massive rework we are doing to AbstractAlgebra which will be finished hopefully early next week.

Unfortunately this PR will cause a merge conflict and you are likely going to have to move the implementation to a different file to resolve it, but at least it is not a huge effort to do so when the time comes. I'll comment on the PR when the time comes and let you know where it should go.

**Comment by thofma** [comment]
`popat!` requires >= 1.5 :-(

**Comment by 8d1h** [comment]
> Great! Could you also add some docstrings and invoke them in docs/src/matrix.md

Sure. I think `minors` is also not in the docs. They should probably go together.

> 
> Normally I'd also ask you to export pfaffians as well, but there is no point yet due to a massive rework we are doing to AbstractAlgebra which will be finished hopefully early next week.
> 
> Unfortunately this PR will cause a merge conflict and you are likely going to have to move the implementation to a different file to resolve it, but at least it is not a huge effort to do so when the time comes. I'll comment on the PR when the time comes and let you know where it should go.

Sure!

> `popat!` requires >= 1.5 :-(

Er... Then what should be the correct way to do it?

**Comment by thofma** [comment]
> > `popat!` requires >= 1.5 :-(
> 
> Er... Then what should be the correct way to do it?

Replace `x = popat!(v, i)` should be equivalent to `x = v[i]; deleteat!(v, i)`.

**Comment by wbhart** [comment]
One other very minor thing, for consistency, we usually put spaces before and after minus signs when used as a binary operation (a - b rather than a-b). It's not terribly important, but something to remember for next time perhaps. It just tends to make the code a little easier for some people to read.

**Comment by wbhart** [comment]
> `popat!` requires >= 1.5 :-(

Wow, they still don't have an LTS based in 1.5 or higher!

**Comment by 8d1h** [comment]
> Faddeev-LeVerrier for determinants can be sped up using baby-step giant-step approach; see https://arxiv.org/abs/2011.12573
> 
> I guess this should work for Pfaffians too?

Thanks for the reference! Indeed this speeds up quite a bit for large matrices.

**Comment by wbhart** [comment]
We've now made the required changes to AbstractAlgebra to split it between abstract types in src and generic types in src/generic. It looks like you've coded this to the Matrix interface which means it belongs in the former.

Could you now move the file over to src/Matrix.jl (no need to adjust the test code).

Also, can you export all the new functions at the top of that file.

**Comment by wbhart** [comment]
Note that you can remove AbstractAlgebra from the front of function names when you move it.

You should also be able to add a Pfaffians section in docs/src/matrix.jl in an appropriate place, with an example or two. Just follow the format of other similar sections.

**Comment by wbhart** [comment]
Looks good. We can merge when green.

**Comment by 8d1h** [comment]
Sorry. Actually I have a question: right now when the matrix is over `ZZ` or `ZZ[x]`, since division is not defined, `pfaffian` fallbacks to recursion which is slow when the matrix is big. But it would be natural to extend the coefficients to `QQ`, compute using the fast algorithm there, and then lift back to `ZZ`. Is there a solution to do this generically?

**Comment by wbhart** [comment]
You could use change_base_ring to convert the matrix to a matrix over Q or Q[x].

Going the other way I am not sure if there is a lift function for matrices or not. But you could use map_entries and a function for lifting from QQ to ZZ. I'm not sure this is what we call a lift or not. You could always use numerator though, although that is not very safe in that it doesn't check the denominators are 1.

Perhaps something like:

```
map_entries(x -> isone(denominator(x, false)) ? numerator(x, false) : error("Unable to lift), M)
```

modulo typos.

**Comment by thofma** [comment]
There is no way to make it specialize for integers. By this I mean you cannot write a signature which would accept integer matrices, like the ones coming from Nemo.

**Comment by 8d1h** [comment]
Thanks. What I have in mind is some sort of tensoring with `QQ` over `ZZ`, which will then work for all rings of char 0. But this may be too much too ask...

For now, at least the wrong result in Nemo should be fixed. What is the right way to determine if a ring is divisible by integers?

**Comment by wbhart** [comment]
Unfortunately there is no tensoring or divisible ring testing. It may be worth adding both, but tensoring is complex in that everything has to work recursively over tensored rings, so it's quite a project.

The other sounds like a bug/inconsistency. Can you post some exact code snippets on a ticket.

**Comment by wbhart** [comment]
We probably should add integer_type which returns the integer type for the current package. That would make specialising things for integers possible (I think).

**Comment by 8d1h** [comment]
> The other sounds like a bug/inconsistency. Can you post some exact code snippets on a ticket.

https://github.com/Nemocas/Nemo.jl/issues/1090

I think maybe the problem is not with `AbstractAlgebra` or this PR, and should be fixed in `Nemo` / `Hecke`.

**Comment by wbhart** [comment]
Correct. The first one is a bug in Nemo. You may want to make a copy of the other one on the Hecke issue tracker. I doubt that has to do with either AbstractAlgebra or Nemo.

**Comment by thofma** [comment]
Is this good to go @8d1h?

**Comment by 8d1h** [comment]
> Is this good to go @8d1h?

Yeah. The optimization for `ZZ` can be added later.

**Comment by thofma** [comment]
Thanks!

**Pull request merged**
