### PR TITLE
Add constant_coefficient function for Poly.

### PR DESCRIPTION
**Pull request by wbhart**
This is expected to break Hecke. A PR to fix Hecke is available.

### CODE REVIEW

**Comment by wbhart** [comment]
Rebasing now.

**Comment by wbhart** [comment]
Hmm, if we merge this now, there's no way to get upstream (Hecke) working without all the patches at once.

I can only run AbstractAlgebra and Nemo tests locally for this.

**Comment by wbhart** [comment]
AbstractAlgebra passes locally. Now testing Nemo.

**Comment by wbhart** [comment]
Nemo passes locally. So by my reckoning this can be merged now (up to the concerns about needing to rebase 218 on 217 when we get up to Hecke.

**Comment by thofma** [comment]
I combined both in Hecke here: https://github.com/thofma/Hecke.jl/pull/221

**Comment by wbhart** [comment]
Great. That solves that then.

**Pull request merged**
